'use strict';function u(k,a,b,g){k.P.ce(k.bc,a,b,g,void 0)}function w(k,a,b){return k.P.Qf(k.bc,a,b,void 0,void 0)}function A(k,a,b,g){k.P.Rb?u(k,a,b,g):k.P.uj()._OnMessageFromDOM({type:"event",component:k.bc,handler:a,dispatchOpts:g||null,data:b,responseId:null})}function B(k,a,b){k.P.R(k.bc,a,b)}function C(k,a){for(const [b,g]of a)B(k,b,g)}function D(k){k.vd||(k.P.dj(k.Sg),k.vd=!0)}window.ab=class{constructor(k,a){this.P=k;this.bc=a;this.vd=!1;this.Sg=()=>this.ka()}Bf(){}ka(){}};
function E(k){-1!==k.Qb&&(self.clearTimeout(k.Qb),k.Qb=-1)}window.zi=class{constructor(k,a){this.Me=k;this.xl=a;this.Qb=-1;this.wd=-Infinity;this.Tg=()=>{this.Qb=-1;this.wd=Date.now();this.ic=!0;this.Me();this.ic=!1};this.ug=this.ic=!1}l(){E(this);this.Tg=this.Me=null}};"use strict";
function aa(k,a){const b=a.elementId,g=k.Mc(b,a);k.Ca.set(b,g);a.isVisible||(g.style.display="none");g.addEventListener("focus",()=>{G(k,"elem-focused",b)});g.addEventListener("blur",()=>{G(k,"elem-blurred",b)});k.ld&&document.body.appendChild(g)}function H(k,a,b){B(k,a,g=>{const p=k.Ca.get(g.elementId);return b(p,g)})}function G(k,a,b,g){g||(g={});g.elementId=b;u(k,a,g)}function I(k,a,b,g){g||(g={});g.elementId=b;A(k,a,g)}
window.Ud=class extends self.ab{constructor(k,a){super(k,a);this.Ca=new Map;this.ld=!0;C(this,[["create",b=>aa(this,b)],["destroy",b=>{{b=b.elementId;const g=this.Ca.get(b);this.ld&&g.parentElement.removeChild(g);this.Ca.delete(b)}}],["set-visible",b=>{this.ld&&(this.Ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.ld){var g=this.Ca.get(b.elementId);g.style.left=b.left+"px";g.style.top=b.top+"px";g.style.width=b.width+"px";g.style.height=b.height+"px";b=b.fontSize;
null!==b&&(g.style.fontSize=b+"em")}}],["update-state",b=>{{const g=this.Ca.get(b.elementId);this.mb(g,b)}}],["focus",b=>this.Ge(b)],["set-css-style",b=>{this.Ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Ca.get(b.elementId).removeAttribute(b.name)}]]);H(this,"get-element",b=>b)}Mc(){throw Error("required override");}mb(){throw Error("required override");}Ge(k){const a=this.Ca.get(k.elementId);k.focus?
a.focus():a.blur()}};"use strict";
{var J=function(n){return e.has(n)},K=function(n){return new Promise((l,q)=>{const r=new FileReader;r.onload=t=>l(t.target.result);r.onerror=t=>q(t);r.readAsArrayBuffer(n)})},ba=async function(n){n=await K(n);return(new TextDecoder("utf-8")).decode(n)},L=function(n){if(n.Jl){const l=document.createElement("script");l.async=!1;l.textContent=n.Ml;document.head.appendChild(l)}else return new Promise((l,q)=>{const r=document.createElement("script");r.onload=l;r.onerror=q;r.async=!1;r.src=n;document.head.appendChild(r)})};
const k=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=new Audio;const b={"audio/webm; codecs=opus":!!a.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!a.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!a.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!a.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!a.canPlayType("audio/mp4"),"audio/mpeg":!!a.canPlayType("audio/mpeg")};a=null;const g=[];let p=0;window.RealFile=
window.File;const m=[],f=new Map,c=new Map;let h=0;const d=[];self.Xl=function(n){if("function"!==typeof n)throw Error("runOnStartup called without a function");d.push(n)};const e=new Set(["cordova","playable-ad","instant-games"]);window.ya=class n{constructor(l){this.Rb=l.Ol;this.gb=null;this.va="";this.nf=l.Ll;this.Kc={};this.Ib=this.Jc=null;this.rd=[];this.pc=this.ba=this.Ob=null;this.Nb=-1;this.Dl=()=>this.jk();this.Mb=[];this.ca=l.Ug;J(this.ca)&&this.Rb&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.Rb=!1);this.uf=!1;this.Bd=this.Va=null;"html5"!==this.ca&&"playable-ad"!==this.ca||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.R("runtime","cordova-fetch-local-file",q=>this.Lj(q));this.R("runtime","create-job-worker",()=>this.Mj());"cordova"===this.ca?document.addEventListener("deviceready",()=>this.fg(l)):this.fg(l)}l(){this.pe();this.gb&&
(this.gb=this.gb.onmessage=null);this.Jc&&(this.Jc.terminate(),this.Jc=null);this.Ib&&(this.Ib.l(),this.Ib=null);this.ba&&(this.ba.parentElement.removeChild(this.ba),this.ba=null)}Of(){return k&&"cordova"===this.ca}Uc(){return k&&J(this.ca)||navigator.standalone}async fg(l){if("playable-ad"===this.ca){this.Va=self.c3_base64files;this.Bd={};await this.ij();for(let r=0,t=l.Tb.length;r<t;++r){var q=l.Tb[r].toLowerCase();this.Bd.hasOwnProperty(q)?l.Tb[r]={Jl:!0,Ml:this.Bd[q]}:this.Va.hasOwnProperty(q)&&
(l.Tb[r]=URL.createObjectURL(this.Va[q]))}}l.Gl?this.va=l.Gl:(q=location.origin,this.va=("null"===q?"file:///":q)+location.pathname,q=this.va.lastIndexOf("/"),-1!==q&&(this.va=this.va.substr(0,q+1)));if(l.Ql)for(const [r,t]of Object.entries(l.Ql))this.Kc[r]=URL.createObjectURL(t);q=new MessageChannel;this.gb=q.port1;this.gb.onmessage=r=>this._OnMessageFromRuntime(r.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(r=>this.ak(r));this.pc=new self.ii(this);await this.pc.di();this.Pf();
"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this.ql();this.Rb?await this.Bj(l,q.port2):await this.Aj(l,q.port2)}se(l){return this.Kc.hasOwnProperty(l)?this.Kc[l]:l.endsWith("/workermain.js")&&this.Kc.hasOwnProperty("workermain.js")?this.Kc["workermain.js"]:"playable-ad"===this.ca&&this.Va.hasOwnProperty(l.toLowerCase())?URL.createObjectURL(this.Va[l.toLowerCase()]):l}async Td(l,q,r){if(l.startsWith("blob:"))return new Worker(l,
r);if(this.Of()&&"file:"===location.protocol)return l=await this.Sd(this.nf+l),new Worker(URL.createObjectURL(new Blob([l],{type:"application/javascript"})),r);l=new URL(l,q);if(location.origin!==l.origin){l=await fetch(l);if(!l.ok)throw Error("failed to fetch worker script");l=await l.blob();return new Worker(URL.createObjectURL(l),r)}return new Worker(l,r)}Pf(){if(this.Uc()){const l=document.documentElement.style,q=document.body.style,r=window.innerWidth<window.innerHeight,t=r?window.screen.width:
window.screen.height;q.height=l.height=(r?window.screen.height:window.screen.width)+"px";q.width=l.width=t+"px"}}eg(l){return{baseUrl:this.va,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:n.$d(),projectData:l.Wl,previewImageBlobs:window.cr_previewImageBlobs||this.Va,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:l.Ug,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Vl,jobScheduler:this.pc.Wh(),
supportedAudioFormats:b,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.nf+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.nf+"opus.wasm.wasm",isiOSCordova:this.Of(),isiOSWebView:this.Uc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Bj(l,q){var r=this.se(l.Pl);this.Jc=await this.Td(r,this.va,{name:"Runtime"});this.ba=document.createElement("canvas");this.ba.style.display="none";r=this.ba.transferControlToOffscreen();document.body.appendChild(this.ba);window.c3canvas=
this.ba;this.Jc.postMessage(Object.assign(this.eg(l),{type:"init-runtime",isInWorker:!0,messagePort:q,canvas:r,workerDependencyScripts:l.zf||[],engineScripts:l.Tb,projectScripts:window.Ul,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[q,r,...this.pc.Xh()]);this.rd=m.map(t=>new t(this));this.dg();self.c3_callFunction=(t,v)=>this.Ob.Cj(t,v);"preview"===this.ca&&(self.goToLastErrorScript=()=>this.ce("runtime","go-to-last-error-script"))}async Aj(l,q){this.ba=document.createElement("canvas");this.ba.style.display=
"none";document.body.appendChild(this.ba);window.c3canvas=this.ba;this.rd=m.map(t=>new t(this));this.dg();const r=l.Tb.map(t=>"string"===typeof t?(new URL(t,this.va)).toString():t);Array.isArray(l.zf)&&r.unshift(...l.zf);await Promise.all(r.map(t=>L(t)));if(l.ah&&0<l.ah.length){const t=self.C3_ProjectScriptsStatus;try{if(await Promise.all(l.ah.map(v=>L(v[1]))),Object.values(t).some(v=>!v)){self.setTimeout(()=>this.og(t),100);return}}catch(v){console.error("[Preview] Error loading project scripts: ",
v);self.setTimeout(()=>this.og(t),100);return}}"preview"===this.ca&&"object"!==typeof self.Rl.Sl?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(l=Object.assign(this.eg(l),{isInWorker:!1,messagePort:q,canvas:this.ba,runOnStartupFunctions:d}),this.Ib=self.C3_CreateRuntime(l),await self.C3_InitRuntime(this.Ib,l))}og(l){l=
`Failed to load project script '${Object.entries(l).filter(q=>!q[1]).map(q=>q[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+l);alert(l)}async Mj(){const l=await this.pc.ag();return{outputPort:l,transferables:[l]}}uj(){if(this.Rb)throw Error("not available in worker mode");return this.Ib}ce(l,q,r,t,v){this.gb.postMessage({type:"event",component:l,handler:q,dispatchOpts:t||null,data:r,responseId:null},this.uf?void 0:v)}Qf(l,q,r,t,v){const z=h++,y=new Promise((x,
F)=>{c.set(z,{resolve:x,reject:F})});this.gb.postMessage({type:"event",component:l,handler:q,dispatchOpts:t||null,data:r,responseId:z},this.uf?void 0:v);return y}["_OnMessageFromRuntime"](l){const q=l.type;if("event"===q)return this.Rj(l);if("result"===q)this.mk(l);else if("runtime-ready"===q)this.pk();else if("alert"===q)alert(l.message);else throw Error(`unknown message '${q}'`);}Rj(l){const q=l.component,r=l.handler,t=l.data,v=l.responseId;if(l=f.get(q))if(l=l.get(r)){var z=null;try{z=l(t)}catch(y){console.error(`Exception in '${q}' handler '${r}':`,
y);null!==v&&this.fd(v,!1,""+y);return}if(null===v)return z;z&&z.then?z.then(y=>this.fd(v,!0,y)).catch(y=>{console.error(`Rejection from '${q}' handler '${r}':`,y);this.fd(v,!1,""+y)}):this.fd(v,!0,z)}else console.warn(`[DOM] No handler '${r}' for component '${q}'`);else console.warn(`[DOM] No event handlers for component '${q}'`)}fd(l,q,r){let t;r&&r.transferables&&(t=r.transferables);this.gb.postMessage({type:"result",responseId:l,isOk:q,result:r},t)}mk(l){const q=l.responseId,r=l.isOk;l=l.result;
const t=c.get(q);r?t.resolve(l):t.reject(l);c.delete(q)}R(l,q,r){let t=f.get(l);t||(t=new Map,f.set(l,t));if(t.has(q))throw Error(`[DOM] Component '${l}' already has handler '${q}'`);t.set(q,r)}static Ga(l){if(m.includes(l))throw Error("DOM handler already added");m.push(l)}dg(){for(const l of this.rd)if("runtime"===l.bc){this.Ob=l;return}throw Error("cannot find runtime DOM handler");}ak(l){this.ce("debugger","message",l)}pk(){for(const l of this.rd)l.Bf()}static $d(){return!!(document.fullscreenElement||
document.webkitFullscreenElement||document.mozFullScreenElement)}dj(l){this.Mb.push(l);this.Je()}Rk(l){l=this.Mb.indexOf(l);if(-1===l)throw Error("invalid callback");this.Mb.splice(l,1);this.Mb.length||this.pe()}Je(){-1===this.Nb&&this.Mb.length&&(this.Nb=requestAnimationFrame(this.Dl))}pe(){-1!==this.Nb&&(cancelAnimationFrame(this.Nb),this.Nb=-1)}jk(){this.Nb=-1;for(const l of this.Mb)l();this.Je()}lb(l){this.Ob.lb(l)}Cb(l){this.Ob.Cb(l)}Ie(){this.Ob.Ie()}Yc(l){this.Ob.Yc(l)}fi(){return!!b["audio/webm; codecs=opus"]}async vl(l){l=
await this.Qf("runtime","opus-decode",{arrayBuffer:l},null,[l]);return new Float32Array(l)}ei(l){return/^(?:[a-z]+:)?\/\//.test(l)||"data:"===l.substr(0,5)||"blob:"===l.substr(0,5)}gi(l){return!this.ei(l)}async Lj(l){const q=l.filename;switch(l.as){case "text":return await this.Ch(q);case "buffer":return await this.Sd(q);default:throw Error("unsupported type");}}Hf(l){const q=window.cordova.file.applicationDirectory+"www/"+l.toLowerCase();return new Promise((r,t)=>{window.resolveLocalFileSystemURL(q,
v=>{v.file(r,t)},t)})}async Ch(l){l=await this.Hf(l);return await ba(l)}qe(){if(g.length&&!(8<=p)){p++;var l=g.shift();this.jj(l.filename,l.Nl,l.Il)}}Sd(l){return new Promise((q,r)=>{g.push({filename:l,Nl:t=>{p--;this.qe();q(t)},Il:t=>{p--;this.qe();r(t)}});this.qe()})}async jj(l,q,r){try{const t=await this.Hf(l),v=await K(t);q(v)}catch(t){r(t)}}async ij(){const l=[];for(const [q,r]of Object.entries(this.Va))l.push(this.hj(q,r));await Promise.all(l)}async hj(l,q){if("object"===typeof q)this.Va[l]=
new Blob([q.str],{type:q.type}),this.Bd[l]=q.str;else{let r=await this.rj(q);r||(r=this.lj(q));this.Va[l]=r}}async rj(l){try{return await (await fetch(l)).blob()}catch(q){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",q),null}}lj(l){l=this.Kk(l);return this.gj(l.data,l.Kl)}Kk(l){var q=l.indexOf(",");if(0>q)throw new URIError("expected comma in data: uri");
var r=l.substring(q+1);q=l.substring(5,q).split(";");l=q[0]||"";const t=q[2];r="base64"===q[1]||"base64"===t?atob(r):decodeURIComponent(r);return{Kl:l,data:r}}gj(l,q){var r=l.length;let t=r>>2,v=new Uint8Array(r),z=new Uint32Array(v.buffer,0,t),y,x;for(x=y=0;y<t;++y)z[y]=l.charCodeAt(x++)|l.charCodeAt(x++)<<8|l.charCodeAt(x++)<<16|l.charCodeAt(x++)<<24;for(r&=3;r--;)v[x]=l.charCodeAt(x),++x;return new Blob([v],{type:q})}ql(){let l=null;const q=new Promise(v=>l=v),r=new ArrayBuffer(1),t=new MessageChannel;
t.port2.onmessage=v=>{v.data&&v.data.arrayBuffer||(this.uf=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));l()};t.port1.postMessage({arrayBuffer:r},[r]);return q}}}"use strict";
{var ca=function(){const c=document.activeElement;if(!c)return!1;const h=c.tagName.toLowerCase(),d=new Set("email number password search tel text url".split(" "));return"textarea"===h?!0:"input"===h?d.has(c.type.toLowerCase()||"text"):M(c)},da=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(c){return!1}},N=function(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()},O=function(c){m.has(c.target.tagName.toLowerCase())&&c.preventDefault()},M=function(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;
c=c.parentNode}while(c);return!1},fa=async function(c,h,d){if(!/firefox/i.test(navigator.userAgent))return await P(c);var e=await ea(c);e=(new DOMParser).parseFromString(e,"image/svg+xml");const n=e.documentElement;if(n.hasAttribute("width")&&n.hasAttribute("height")){const l=n.getAttribute("width"),q=n.getAttribute("height");if(!l.includes("%")&&!q.includes("%"))return await P(c)}n.setAttribute("width",h+"px");n.setAttribute("height",d+"px");e=(new XMLSerializer).serializeToString(e);c=new Blob([e],
{type:"image/svg+xml"});return await P(c)},ea=function(c){return new Promise((h,d)=>{let e=new FileReader;e.onload=n=>h(n.target.result);e.onerror=n=>d(n);e.readAsText(c)})},P=async function(c){c=URL.createObjectURL(c);try{return await ha(c)}finally{URL.revokeObjectURL(c)}},ha=function(c){return new Promise((h,d)=>{const e=new Image;e.onload=()=>h(e);e.onerror=n=>d(n);e.src=c})},ia=function(c){return new Promise((h,d)=>{const e=document.createElement("link");e.onload=()=>h(e);e.onerror=n=>d(n);e.rel=
"stylesheet";e.href=c;document.head.appendChild(e)})},Q=function(c){return c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents};const k=self.ya,a=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),b={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},p={dispatchRuntimeEvent:!0},m=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(c){c=
await P(c);if(0<c.width&&0<c.height)return[c.width,c.height];{c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const h=c.getBoundingClientRect();document.body.removeChild(c);return[h.width,h.height]}};self.C3_RasterSvgImageBlob=async function(c,h,d,e,n){c=await fa(c,h,d);const l=document.createElement("canvas");l.width=e;l.height=n;l.getContext("2d").drawImage(c,0,0,h,d);return l};let f=!1;document.addEventListener("pause",()=>
f=!0);document.addEventListener("resume",()=>f=!1);k.Ga(class extends self.ab{constructor(c){super(c,"runtime");this.Bg=!0;this.Pb=-1;this.sf="any";this.pg=this.qg=!1;this.bf=this.Bc=this.tb=null;c.R("canvas","update-size",e=>this.Ik(e));c.R("runtime","invoke-download",e=>this.Zj(e));c.R("runtime","raster-svg-image",e=>this.kk(e));c.R("runtime","get-svg-image-size",e=>this.Uj(e));c.R("runtime","set-target-orientation",e=>this.qk(e));c.R("runtime","register-sw",()=>this.lk());c.R("runtime","post-to-debugger",
e=>this.kg(e));c.R("runtime","go-to-script",e=>this.kg(e));c.R("runtime","before-start-ticking",()=>this.Ij());c.R("runtime","debug-highlight",e=>this.Nj(e));c.R("runtime","enable-device-orientation",()=>this.fj());c.R("runtime","enable-device-motion",()=>this.ej());c.R("runtime","add-stylesheet",e=>this.Gj(e));c.R("runtime","alert",e=>this.xe(e));c.R("runtime","hide-cordova-splash",()=>this.Wj());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",e=>{const n=e.target;
h.has(n.tagName.toLowerCase())||M(n)||e.preventDefault()});const d=c.ba;window.addEventListener("selectstart",O);window.addEventListener("gesturehold",O);d.addEventListener("selectstart",O);d.addEventListener("gesturehold",O);window.addEventListener("touchstart",O,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",O,{passive:!1}),d.addEventListener("pointerdown",O)):d.addEventListener("touchstart",O);this.uc=0;window.addEventListener("mousedown",e=>{1===e.button&&
e.preventDefault()});window.addEventListener("mousewheel",N,{passive:!1});window.addEventListener("wheel",N,{passive:!1});window.addEventListener("resize",()=>this.Jk());c.Uc()&&window.addEventListener("focusout",()=>{ca()||(document.scrollingElement.scrollTop=0)});this.Jb=new Set;this.Cd=new WeakSet;this.fb=!1}Ij(){"cordova"===this.P.ca?(document.addEventListener("pause",()=>this.He(!0)),document.addEventListener("resume",()=>this.He(!1))):document.addEventListener("visibilitychange",()=>this.He(document.hidden));
return{isSuspended:!(!document.hidden&&!f)}}Bf(){window.addEventListener("focus",()=>this.gd("window-focus"));window.addEventListener("blur",()=>{this.gd("window-blur",{parentHasFocus:da()});this.uc=0});window.addEventListener("fullscreenchange",()=>this.Ae());window.addEventListener("webkitfullscreenchange",()=>this.Ae());window.addEventListener("mozfullscreenchange",()=>this.Ae());window.addEventListener("fullscreenerror",h=>this.Be(h));window.addEventListener("webkitfullscreenerror",h=>this.Be(h));
window.addEventListener("mozfullscreenerror",h=>this.Be(h));window.addEventListener("keydown",h=>this.hg("keydown",h));window.addEventListener("keyup",h=>this.hg("keyup",h));window.addEventListener("dblclick",h=>this.Ee("dblclick",h,b));window.addEventListener("wheel",h=>this.ck(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",h=>{this.te(h);this.$b("pointerdown",h)}),this.P.Rb&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Bc=new self.zi(()=>this.pj(),
5),this.Bc.ug=!0,window.addEventListener("pointerrawupdate",h=>this.hk(h))):window.addEventListener("pointermove",h=>this.$b("pointermove",h)),window.addEventListener("pointerup",h=>this.$b("pointerup",h)),window.addEventListener("pointercancel",h=>this.$b("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.te(h);this.Fe("pointerdown",h)}),window.addEventListener("mousemove",h=>this.Fe("pointermove",h)),window.addEventListener("mouseup",h=>this.Fe("pointerup",h)),window.addEventListener("touchstart",
h=>{this.te(h);this.ed("pointerdown",h)}),window.addEventListener("touchmove",h=>this.ed("pointermove",h)),window.addEventListener("touchend",h=>this.ed("pointerup",h)),window.addEventListener("touchcancel",h=>this.ed("pointercancel",h)));const c=()=>this.Ie();window.addEventListener("pointerup",c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0)}gd(c,h){u(this,c,h||null,p)}cd(){return Math.max(window.innerWidth,
1)}bd(){return Math.max(window.innerHeight,1)}Jk(){const c=this.cd(),h=this.bd();this.gd("window-resize",{innerWidth:c,innerHeight:h,devicePixelRatio:window.devicePixelRatio});this.P.Uc()&&(-1!==this.Pb&&clearTimeout(this.Pb),this.lg(c,h,0))}Sk(c,h,d){-1!==this.Pb&&clearTimeout(this.Pb);this.Pb=setTimeout(()=>this.lg(c,h,d),48)}lg(c,h,d){const e=this.cd(),n=this.bd();this.Pb=-1;e!=c||n!=h?this.gd("window-resize",{innerWidth:e,innerHeight:n,devicePixelRatio:window.devicePixelRatio}):10>d&&this.Sk(e,
n,d+1)}qk(c){this.sf=c.targetOrientation}rl(){const c=this.sf;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(c):screen.webkitLockOrientation?h=screen.webkitLockOrientation(c):screen.mozLockOrientation?h=screen.mozLockOrientation(c):screen.msLockOrientation&&(h=screen.msLockOrientation(c));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",
h)}}Ae(){const c=k.$d();c&&"any"!==this.sf&&this.rl();u(this,"fullscreenchange",{isFullscreen:c,innerWidth:this.cd(),innerHeight:this.bd()})}Be(c){console.warn("[Construct 3] Fullscreen request failed: ",c);u(this,"fullscreenerror",{isFullscreen:k.$d(),innerWidth:this.cd(),innerHeight:this.bd()})}He(c){c?this.P.pe():this.P.Je();u(this,"visibilitychange",{hidden:c})}hg(c,h){"Backspace"===h.key&&O(h);const d=a.get(h.code)||h.code;A(this,c,{code:d,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,
ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},b)}ck(c){u(this,"wheel",{clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,deltaX:c.deltaX,deltaY:c.deltaY,deltaZ:c.deltaZ,deltaMode:c.deltaMode,timeStamp:c.timeStamp},b)}Ee(c,h,d){Q(h)||A(this,c,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},d)}Fe(c,h){if(!Q(h)){var d=this.uc;"pointerdown"===c&&0!==d?c="pointermove":"pointerup"===
c&&0!==h.buttons&&(c="pointermove");A(this,c,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},b);this.uc=h.buttons;this.Ee(h.type,h,g)}}$b(c,h){if(this.Bc&&"pointermove"!==c){var d=this.Bc;d.ic||(E(d),d.wd=Date.now())}d=0;"mouse"===h.pointerType&&(d=this.uc);A(this,c,{pointerId:h.pointerId,pointerType:h.pointerType,
button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},b);"mouse"===h.pointerType&&(d="mousemove","pointerdown"===c?d="mousedown":"pointerup"===c&&(d="pointerup"),this.Ee(d,h,g),this.uc=h.buttons)}hk(c){this.bf=c;c=this.Bc;if(-1===c.Qb){var h=Date.now(),d=h-c.wd,e=c.xl;
d>=e&&c.ug?(c.wd=h,c.ic=!0,c.Me(),c.ic=!1):c.Qb=self.setTimeout(c.Tg,Math.max(e-d,4))}}pj(){this.$b("pointermove",this.bf);this.bf=null}ed(c,h){for(let d=0,e=h.changedTouches.length;d<e;++d){const n=h.changedTouches[d];A(this,c,{pointerId:n.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:n.clientX,clientY:n.clientY,pageX:n.pageX,pageY:n.pageY,width:2*(n.radiusX||n.webkitRadiusX||0),height:2*(n.radiusY||n.webkitRadiusY||0),pressure:n.force||n.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:n.rotationAngle||0,timeStamp:h.timeStamp},b)}}te(c){window!==window.top&&window.focus();this.gg(c.target)&&document.activeElement&&!this.gg(document.activeElement)&&document.activeElement.blur()}gg(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}fj(){this.qg||(this.qg=!0,window.addEventListener("deviceorientation",c=>this.Pj(c)),window.addEventListener("deviceorientationabsolute",c=>this.Qj(c)))}ej(){this.pg||(this.pg=!0,window.addEventListener("devicemotion",
c=>this.Oj(c)))}Pj(c){u(this,"deviceorientation",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp,webkitCompassHeading:c.webkitCompassHeading,webkitCompassAccuracy:c.webkitCompassAccuracy},b)}Qj(c){u(this,"deviceorientationabsolute",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp},b)}Oj(c){let h=null;var d=c.acceleration;d&&(h={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=c.accelerationIncludingGravity;e&&(d={x:e.x||
0,y:e.y||0,z:e.z||0});e=null;const n=c.rotationRate;n&&(e={alpha:n.alpha||0,beta:n.beta||0,gamma:n.gamma||0});u(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:d,rotationRate:e,interval:c.interval,timeStamp:c.timeStamp},b)}Ik(c){const h=this.P,d=h.ba;d.style.width=c.styleWidth+"px";d.style.height=c.styleHeight+"px";d.style.marginLeft=c.marginLeft+"px";d.style.marginTop=c.marginTop+"px";h.Pf();this.Bg&&(d.style.display="",this.Bg=!1)}Zj(c){const h=c.url;c=c.filename;const d=document.createElement("a"),
e=document.body;d.textContent=c;d.href=h;d.download=c;e.appendChild(d);d.click();e.removeChild(d)}async kk(c){var h=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);h=h?await createImageBitmap(c,h):await createImageBitmap(c);return{imageBitmap:h,transferables:[h]}}async Uj(c){return await self.C3_GetSvgImageSize(c.blob)}async Gj(c){await ia(c.url)}Ie(){var c=[...this.Jb];this.Jb.clear();if(!this.fb)for(const h of c)(c=h.play())&&
c.catch(()=>{this.Cd.has(h)||this.Jb.add(h)})}lb(c){if("function"!==typeof c.play)throw Error("missing play function");this.Cd.delete(c);let h;try{h=c.play()}catch(d){this.Jb.add(c);return}h&&h.catch(()=>{this.Cd.has(c)||this.Jb.add(c)})}Cb(c){this.Jb.delete(c);this.Cd.add(c)}Yc(c){this.fb=!!c}Wj(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Nj(c){if(c.show){this.tb||(this.tb=document.createElement("div"),this.tb.id="inspectOutline",document.body.appendChild(this.tb));
var h=this.tb;h.style.display="";h.style.left=c.left-1+"px";h.style.top=c.top-1+"px";h.style.width=c.width+2+"px";h.style.height=c.height+2+"px";h.textContent=c.name}else this.tb&&(this.tb.style.display="none")}lk(){window.C3_RegisterSW&&window.C3_RegisterSW()}kg(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}Cj(c,h){return w(this,"js-invoke-function",{name:c,params:h})}xe(c){alert(c.message)}})}"use strict";
{const k=document.currentScript.src;self.ii=class{constructor(a){this.Gd=a;this.va=k?k.substr(0,k.lastIndexOf("/")+1):a.va;this.zl=Math.min(navigator.hardwareConcurrency||2,16);this.Pe=null;this.Cg=[];this.kf=this.Ye=null}async di(){if(this.wl)throw Error("already initialised");this.wl=!0;var a=this.Gd.se("dispatchworker.js");this.Pe=await this.Gd.Td(a,this.va,{name:"DispatchWorker"});a=new MessageChannel;this.Ye=a.port1;this.Pe.postMessage({type:"_init","in-port":a.port2},[a.port2]);this.kf=await this.ag()}async ag(){const a=
this.Cg.length;var b=this.Gd.se("jobworker.js");b=await this.Gd.Td(b,this.va,{name:"JobWorker"+a});const g=new MessageChannel,p=new MessageChannel;this.Pe.postMessage({type:"_addJobWorker",port:g.port1},[g.port1]);b.postMessage({type:"init",number:a,"dispatch-port":g.port2,"output-port":p.port2},[g.port2,p.port2]);this.Cg.push(b);return p.port1}Wh(){return{inputPort:this.Ye,outputPort:this.kf,maxNumWorkers:this.zl}}Xh(){return[this.Ye,this.kf]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ya({Ol:!1,Pl:"workermain.js",Tb:["scripts/c3runtime.js"],Ll:"scripts/",zf:[],Ug:"html5"}));"use strict";function R(k){k.stopPropagation()}function S(k){const a=document.createElement("option");a.text=k;return a}function T(k){const a=k.selectedIndex,b=[];for(let g=0,p=k.length;g<p;++g)k.options[g].selected&&b.push(g);return{selectedIndex:a,selectedIndices:b}}
self.ya.Ga(class extends self.Ud{constructor(k){super(k,"list");H(this,"set-selected-index",(a,b)=>{a.selectedIndex=b.selectedIndex});H(this,"add-item",(a,b)=>{{const g=b.index;b=S(b.text);0>g?a.add(b):a.add(b,g)}});H(this,"remove-item",(a,b)=>{a.remove(b.index)});H(this,"set-item",(a,b)=>{a.options[b.index].text=b.text});H(this,"clear",a=>{a.innerHTML=""});H(this,"load-state",(a,b)=>this.De(a,b))}Mc(k,a){const b=a.isDropdown,g=a.isMultiSelect,p=a.items,m=document.createElement("select");m.style.position=
"absolute";m.style.userSelect="none";m.style.webkitUserSelect="none";m.multiple=g;b||(m.size=2);for(const f of p)m.add(S(f));m.addEventListener("touchstart",R);m.addEventListener("touchmove",R);m.addEventListener("touchend",R);m.addEventListener("mousedown",R);m.addEventListener("mouseup",R);m.addEventListener("click",f=>{f.stopPropagation();I(this,"click",k,T(m))});m.addEventListener("dblclick",f=>{f.stopPropagation();I(this,"dblclick",k,T(m))});m.addEventListener("change",()=>G(this,"change",k,
T(m)));a.id&&(m.id=a.id);this.mb(m,a);return m}mb(k,a){k.title=a.title;k.disabled=!a.isEnabled;k.multiple=!!a.isMultiSelect}De(k,a){k.innerHTML="";for(const b of a.items)k.add(S(b));k.selectedIndex=a.selectedIndex;for(const b of a.selectedIndices)if(a=k.options[b])a.selected=!0}});"use strict";function U(k){k.stopPropagation()}
self.ya.Ga(class extends self.Ud{constructor(k){super(k,"button")}Mc(k,a){const b=document.createElement("input");var g=b;a.isCheckbox?(b.type="checkbox",g=document.createElement("label"),g.appendChild(b),g.appendChild(document.createTextNode("")),g.style.fontFamily="sans-serif",g.style.userSelect="none",g.style.webkitUserSelect="none",g.style.display="inline-block",g.style.color="black"):b.type="button";g.style.position="absolute";g.addEventListener("touchstart",U);g.addEventListener("touchmove",
U);g.addEventListener("touchend",U);g.addEventListener("mousedown",U);g.addEventListener("mouseup",U);g.addEventListener("keydown",U);g.addEventListener("keyup",U);b.addEventListener("click",()=>I(this,"click",k,{isChecked:b.checked}));a.id&&(b.id=a.id);this.mb(g,a);return g}mb(k,a){const b="input"===k.tagName.toLowerCase()?k:k.firstChild;b.checked=a.isChecked;b.disabled=!a.isEnabled;k.title=a.title;k===b?b.value=a.text:k.lastChild.textContent=a.text}});"use strict";
function V(k){13!==k.which&&27!==k.which&&k.stopPropagation()}function W(k){k.stopPropagation()}
self.ya.Ga(class extends self.Ud{constructor(k){super(k,"text-input");H(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}Mc(k,a){let b;const g=a.type;"textarea"===g?(b=document.createElement("textarea"),b.style.resize="none"):(b=document.createElement("input"),b.type=g);b.style.position="absolute";b.autocomplete="off";b.addEventListener("touchstart",W);b.addEventListener("touchmove",W);b.addEventListener("touchend",W);b.addEventListener("mousedown",W);b.addEventListener("mouseup",W);b.addEventListener("keydown",
V);b.addEventListener("keyup",V);b.addEventListener("click",p=>{p.stopPropagation();I(this,"click",k)});b.addEventListener("dblclick",p=>{p.stopPropagation();I(this,"dblclick",k)});b.addEventListener("input",()=>G(this,"change",k,{text:b.value}));a.id&&(b.id=a.id);this.mb(b,a);return b}mb(k,a){k.value=a.text;k.placeholder=a.placeholder;k.title=a.title;k.disabled=!a.isEnabled;k.readOnly=a.isReadOnly;k.spellcheck=a.spellCheck;a=a.maxLength;0>a?k.removeAttribute("maxlength"):k.setAttribute("maxlength",
a)}});"use strict";
{var la=function(f,c,h){const d=ja(f,c);return ka(c,f)?X(f+d*h):X(f-d*h)},ka=function(f,c){return 0>=Math.cos(f)*Math.sin(c)-Math.sin(f)*Math.cos(c)},ja=function(f,c){if(f===c)return 0;f=Math.sin(f)*Math.sin(c)+Math.cos(f)*Math.cos(c);return 1<=f?0:-1>=f?Math.PI:Math.acos(f)},ma=function(f,c,h){return f===c?0:(h-f)/(c-f)},na=function(f,c,h){return f+h*(c-f)},oa=function(f,c,h){return f<c?c:f>h?h:f},X=function(f){f%=a;0>f&&(f+=a);return f};const k=[],a=2*Math.PI;class b{constructor(f,c,h,d,e,n){this.jc=
f;this.kc=c;this.hb=h;this.Z=d;this.Md=e;this.vg=n}Bb(){return{tag:this.Z,interp:this.kc,userData:this.Md,cvt:this.vg}}bb(){return this.kc}bi(){return"undefined"!==typeof this.Md}Ff(f){switch(this.hb){case 0:return f;case 1:return Math.fround(f);case 2:return 2===this.kc&&(f=X(f),f/=Math.PI,f=32767*(f-1)),oa(f|0,-32768,32767);case 3:return 2===this.kc&&(f=X(f),f/=a,f*=255),oa(f|0,0,255);default:return f}}Yf(f,c,h){switch(this.hb){case 0:f.setFloat64(c,h);c+=8;break;case 1:f.setFloat32(c,h);c+=4;break;
case 2:f.setInt16(c,h);c+=2;break;case 3:f.setUint8(c,h);c+=1;break;default:f.setFloat32(c,h),c+=4}return c}Vc(f){if(2!==this.kc)return f;2===this.hb?f=(f/32767+1)*Math.PI:3===this.hb&&(f=f/255*a);return f}static Rc(f,c,h,d,e){switch(f){case 0:return e?h:c;case 1:return na(c,h,d);case 2:return la(c,h,d);default:return e?h:c}}}class g{constructor(f,c){this.timestamp=f;this.data=c}}class p{constructor(f,c,h){this.ta=f;this.b=f.b;this.H=c;this.T=h;this._data=[];this._data.length=this.ta.xa.length;this.df=
this.xd=0;this.Ag=this.Kd=!1;this.$=[];this.L=this.C=this.Fa=null}Bb(){var f=[];for(let h=0,d=this.ta.xa.length;h<d;++h)f.push(this.bb(this.ta.Hd,h));f={id:this.H,nid:this.T,isTimedOut:this.hi(),interpValues:f,latestUpdate:null};const c=this.Qh();c&&(f.latestUpdate={timestamp:c.timestamp,data:c.data});return f}Sf(f){this.Ag=!!f}ne(f,c){f=f.netValues;var h=this.ta.xa;const d=h.length;this.Kd=!1;for(let e=0;e<d;++e){const n=h[e].Ff(f[e]);this._data[e]!==n&&(this._data[e]=n,this.xd=c,this.ta.Gi(c))}f=
c-this.xd;c-=this.df;h=this.ta.rg;(this.Kd=100>f&&0===h?!0:1E3>f&&1>=h?95<=c:495<=c)&&this.ta.ci()}oe(f,c,h){const d=this.ta.xa;this.df=h;f.setUint16(c,this.T);c+=2;for(let e=0,n=this._data.length;e<n;++e)c=d[e].Yf(f,c,this._data[e]);return c}Qd(f,c){for(let h=0,d=this.$.length;h<d;++h){const e=this.$[h];if(e.timestamp===f)return;if(e.timestamp>f){this.$.splice(h,0,new g(f,c));return}}this.$.push(new g(f,c))}hi(){return 0===this.$.length?!1:this.$[this.$.length-1].timestamp<this.ta.Hd-3E3}ka(){for(;2<
this.$.length&&this.$[0]!==this.Fa&&this.$[0]!==this.C&&this.$[0]!==this.L;)this.$.shift();const f=this.ta.Hd;if(!(this.L&&this.L.timestamp>f&&this.C&&this.C.timestamp<f)){this.L=null;for(let c=0,h=this.$.length;c<h;++c){const d=this.$[c];if(d.timestamp<=f){if(!this.C||d.timestamp>this.C.timestamp)this.Fa=this.C,this.C=d}else{this.L=d;break}}}}Qh(){return 0===this.$.length?null:this.$[this.$.length-1]}bb(f,c){if(!this.L&&!this.C)return 0;if(this.L&&!this.C)return this.L.data[c];const h=this.ta.xa;
let d,e,n;if(!this.L&&this.C){if(this.Fa){var l=this.Fa.timestamp;d=this.Fa.data[c];e=this.C.timestamp;n=this.C.data[c];f>this.C.timestamp+this.ta.td&&(f=this.C.timestamp+this.ta.td);l=ma(l,e,f);return b.Rc(h[c].bb(),d,n,l,!0)}return this.C.data[c]}l=this.C.timestamp;d=this.C.data[c];e=this.L.timestamp;n=this.L.data[c];l=ma(l,e,f);return b.Rc(h[c].bb(),d,n,l,!1)}}class m{constructor(f,c,h,d){this.b=f;this.Fc=c;this.Gc=h;this.T=this.b.Uh();this.rg=d;this.Md={};this.Oa=0;this.td=250;switch(this.rg){case 1:this.td=
500;break;case 2:this.td=2500}this.xa=[];this.Da=[];this.ub=new Map;this.Sb=new Set;this.xc=this.df=this.xd=this.vc=0;this.Gb=!1;this.od=[];this.wc=new Map;this.Hd=0;this.b.gh(this)}ob(f){this.T=f}Gi(f){this.xd=f}ci(){this.xc++}al(){this.Gb=!0}$a(f,c,h,d,e){f=new b(this.xa.length,f,c,h,d,e);switch(c){case 0:this.Oa+=8;break;case 1:this.Oa+=4;break;case 2:this.Oa+=2;break;case 3:this.Oa+=1}this.xa.push(f)}Qd(f,c,h){this.Sh(c).Qd(f,h)}ka(){this.Hd=this.b.Qc();for(const f of this.Da)f.ka()}Th(){const f=
[];for(const c of this.xa){const h={tag:c.Z,precision:c.hb,interp:c.bb(),clientvaluetag:c.vg};c.bi()&&(h.userdata=c.Md);f.push(h)}return f}Ii(f){this.Oa=this.xa.length=0;for(const c of f)this.$a(c.interp,c.precision,c.tag,c.userdata,c.clientvaluetag)}Sh(f){let c=this.wc.get(f);if(c)return c;c=new p(this,-1,f);this.wc.set(f,c);this.Da.push(c);return c}Rh(f){let c=this.ub.get(f);if(c)return c;c=new p(this,f,this.ih());this.ub.set(f,c);this.Da.push(c);return c}ih(){do this.vc++,65535<this.vc&&(this.vc=
0);while(this.Sb.has(this.vc));const f=this.vc;this.Sb.add(f);return f}ee(f){const c=f.H,h=f.T;this.b.j()&&!this.Gb&&this.od.push(h);this.ub.delete(c);this.wc.delete(h);this.Sb.delete(h);f=this.Da.indexOf(f);-1<f&&this.Da.splice(f,1)}Bh(){this.od.length=0;this.ub.clear();this.wc.clear();this.Sb.clear();this.Da.length=0}ne(f,c){this.xc=0;for(var h of this.Da)h.Sf(!1);for(let d=0,e=f.length;d<e;++d){h=f[d];const n=this.Rh(h.uid);n.Sf(!0);n.ne(h,c)}for(const d of this.Da)d.Ag||k.push(d);for(const d of k)this.ee(d);
k.length=0}oe(f,c,h){f.setUint16(c,this.T);c+=2;let d=0;this.Gb&&(d=1);f.setUint8(c,d);c+=1;f.setUint16(c,this.xc);c+=2;f.setUint16(c,this.Oa);c+=2;for(const e of this.Da)e.Kd&&(c=e.oe(f,c,h));return c}yi(f,c){if(this.ub.has(f))console.warn("OverrideNid passed id "+f+" which is already in use and cannot be overridden");else if(this.Sb.has(c))console.warn("OverrideNid passed nid "+c+" which is already in use and cannot be overridden");else{var h=new p(this,f,c);this.ub.set(f,h);this.Sb.add(c);this.Da.push(h);
this.Gb=!0}}fe(f){(f=this.ub.get(f))&&this.ee(f)}ge(f){(f=this.wc.get(f))&&this.ee(f)}Bb(){return{hasOverriddenNids:this.Gb,netValues:this.xa.map(f=>f.Bb()),netInstances:this.Da.map(f=>f.Bb())}}Zh(){return{roId:this.Fc,sid:this.Gc,netValues:this.xa.map(f=>f.Bb())}}}self.Ef=b;self.wh=g;self.yh=m}"use strict";
{var pa=function(m,f,c){return m===f?0:(c-m)/(f-m)},Y=function(m){if(m)try{m.close()}catch(f){}};const k=self.wh,a=self.Ef,b=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection,g=[];class p{constructor(m,f,c){this.b=m;this.H=f;this.T=0;this.ea=c;this.qb=this.J=null;this.lc=!1;this.rb=null;this.nc=!1;this.sb=null;this.Te=this.Ic=this.hc=this.Fb=this.oc=!1;this.sd=this.wg=this.af=0;this.Jg=[];this.Gg=this.Fg=0;this.wa=[];this.L=this.C=this.Fa=
null;this.Dg=0;this.Le=!1;this.cf=1;this.yd=[];this.Mg=this.zd=0;this.b.bj(this)}ob(m){this.T=m}j(){return this===this.b.O}Sc(){return this===this.b.N}cl(){this.Fg=performance.now()}dl(m){this.Gg=m}$c(m,f){m.binaryType="arraybuffer";m.onopen=()=>{"o"===f?this.lc=!0:"r"===f?this.nc=!0:"u"===f&&(this.oc=!0);this.Fj()};m.onmessage=c=>{this.$j(f,c)};m.onerror=c=>{console.error("Peer '"+this.H+"' datachannel '"+f+"' error: ",c);this.b.Ia(this,c);this.b.j()&&!this.j()&&this.S("network error")};m.onclose=
()=>{this.S("disconnect")}}Gf(){if(!this.Sc()){var m=this.b.j();this.hc=this.Fb=this.oc=this.nc=this.lc=!1;this.wg=performance.now();this.J=new b({iceServers:this.b.Xe});this.J.onicecandidate=c=>{c.candidate&&this.b.Ha({message:"icecandidate",toclientid:this.H,icecandidate:c.candidate})};this.J.onsignalingstatechange=()=>{this.J&&"closed"===this.J.signalingState&&this.S("disconnect")};this.J.oniceconnectionstatechange=()=>{this.J&&("failed"!==this.J.iceConnectionState&&"closed"!==this.J.iceConnectionState||
this.S("disconnect"))};this.J.onconnectionstatechange=()=>{if(this.J){var c=this.J.connectionState;"failed"!==c&&"closed"!==c||this.S("disconnect")}};var f=`c2mp_${this.b.Kh()}_${this.b.Lh()}_${this.b.Mh()}`;m?(this.T=this.b.Af(),this.qb=this.J.createDataChannel("o",{ordered:!0,protocol:f}),this.$c(this.qb,"o"),this.rb=this.J.createDataChannel("r",{ordered:!1,protocol:f}),this.$c(this.rb,"r"),this.sb=this.J.createDataChannel("u",{ordered:!1,maxRetransmits:0,protocol:f}),this.$c(this.sb,"u"),this.J.createOffer().then(c=>
{this.J.setLocalDescription(c);this.b.Ha({message:"offer",toclientid:this.H,offer:c})}).catch(c=>{console.error("Host error creating offer for peer '"+this.H+"': ",c);this.b.Ia(this,"could not create offer for peer")})):this.J.ondatachannel=c=>{if(c.channel.protocol!==f)console.error("Unexpected datachannel protocol '"+c.channel.protocol+"', should be '"+f+"'"),this.b.Ia(this,"unexpected datachannel protocol '"+c.channel.protocol+"', should be '"+f+"'");else{var h=c.channel.label;"o"===h?this.qb=
c.channel:"r"===h?this.rb=c.channel:"u"===h?this.sb=c.channel:(console.error("Unknown datachannel label: "+c.channel.label),this.b.Ia(this,"unknown datachannel label '"+c.channel.label+"'"));this.$c(c.channel,h)}}}}async aj(m){if(this.J)try{await this.J.addIceCandidate(m)}catch(f){console.warn("[Multiplayer] Error adding ICE candidate: ",f)}}ai(){return!!this.J}Fj(){!this.Fb&&this.nc&&this.oc&&this.lc&&(this.dk(),this.Fb=!0,this.hc=!1)}dk(){this.af=performance.now();if(this.b.j()){this.b.Wb("o",JSON.stringify({c:"j",
i:this.H,n:this.T,a:this.ea}),this);this.cb("o",JSON.stringify({c:"hi",hn:this.b.O.T,n:this.T,d:this.b.Ba,u:this.b.zc,objs:this.b.Yh(),cvs:this.b.Jh()}));for(const m of this.b.Ka)!m.j()&&m!==this&&m.be()&&this.cb("o",JSON.stringify({c:"j",i:m.H,n:m.T,a:m.ea}))}else this.Te=!0,this.j()&&this.ie(performance.now(),!0);this.b.jg(this)}Ej(m){!this.hc&&this.Fb&&(this.ye(m),this.hc=!0,this.Fb=!1)}ye(m){this.b.j()&&!this.Sc()&&this.b.Wb("o",JSON.stringify({c:"l",i:this.H,a:this.ea,r:m}),this);this.Sc()||
this.b.ig(this,m)}be(){return this.Fb&&!this.hc}cb(m,f){this.b.Xi();var c=0;f.length?c=f.length:f.byteLength&&(c=f.byteLength);this.b.Vi(c);c=this.b.qf;const h=this.b.pf,d=this.b.rf;if(!(0<c&&"u"===m&&Math.random()<c))if(0===h&&0===d)this.cg(m,f);else{let e=1;"u"!==m&&Math.random()<c&&(e=3);setTimeout(()=>this.cg(m,f),h*e+Math.random()*d*e)}}cg(m,f){try{"o"===m?this.lc&&this.qb&&this.qb.send(f):"r"===m?this.nc&&this.rb&&this.rb.send(f):"u"===m&&this.oc&&this.sb&&this.sb.send(f)}catch(c){this.Ic||
(this.b.j()?"o"===m||"r"===m?("string"===typeof f?(console.error("Error sending "+f.length+"-char string on '"+m+"' to '"+this.ea+"', host kicking: ",c),console.log("String that failed to send from previous error was: "+f)):console.error("Error sending "+(f.length||f.byteLength)+"-byte binary on '"+m+"' to '"+this.ea+"', host kicking: ",c),this.S("network error")):(this.sd++,10<=this.sd&&("string"===typeof f?(console.error("Too many errors ("+this.sd+") sending data on '"+m+"' to '"+this.ea+"', kicking; last error was for sending "+
f.length+"-char string: ",c),console.log("String that failed to send from previous error was: "+f)):console.error("Too many errors ("+this.sd+") sending data on '"+m+"' to '"+this.ea+"', kicking; last error was for sending "+(f.length||f.byteLength)+"-byte binary: ",c),this.S("network error"))):console.error("Error sending data on '"+m+"': ",c))}}ie(m,f){this.Ic||(!f&&!this.be()&&this.J&&25E3<m-this.wg?(console.warn("Timed out '"+this.ea+"', could not establish connection after 25sec"),this.S("timeout")):
!f&&this.be()&&2E4<m-this.af?(console.warn("Timed out '"+this.ea+"', not heard from for 20sec"),this.S("timeout")):(this.Dg=m,this.Le=!0,this.cf++,this.cb("u","ping:"+this.cf)))}Ci(m){m="pong:"+m.substr(5);this.b.j()&&(m=m+"/"+Math.round(performance.now()).toString());this.cb("u",m)}ik(m){if(this.Le){var f=m.indexOf(":");if(-1<f){if(parseFloat(m.substr(f+1))===this.cf){f=performance.now();this.Le=!1;var c=(f-this.Dg)/2;this.yd.push(c);10<this.yd.length&&this.yd.shift();g.push(...this.yd);g.sort((n,
l)=>n-l);this.Mg=g[g.length-1]-g[0];var h=0,d=g.length;4<=g.length&&6>=g.length?(++h,--d):6<g.length&&(h+=2,d-=2);var e=0;for(let n=h;n<d;++n)e+=g[n];this.zd=e/(d-h);g.length=0;this.b.j()||(h=m.indexOf("/"),-1<h?(m=parseFloat(m.substr(h+1)),isFinite(m)?this.b.fh(m,f,c,this.zd):console.warn("Invalid host time from pong response")):console.warn("Cannot parse off host time from pong response"))}}else console.warn("Cannot parse off ping ID from pong")}}$j(m,f){const c=this.b.qf,h=this.b.pf,d=this.b.rf;
if(!(0<c&&"u"===m&&Math.random()<c))if(0===h&&0===d)this.bg(m,f);else{let e=1;"u"!==m&&Math.random()<c&&(e=3);setTimeout(()=>this.bg(m,f),h*e+Math.random()*d*e)}}bg(m,f){if(!this.Ic){this.af=performance.now();this.b.Wi();var c=0;f.data.length?c=f.data.length:f.data.byteLength&&(c=f.data.byteLength);this.b.Ui(c);if("string"===typeof f.data){if(!(""===f.data.trim()||4>f.data.length))if(m=f.data.substr(0,4),"ping"===m)this.Ci(f.data);else if("pong"===m)this.ik(f.data);else{try{var h=JSON.parse(f.data)}catch(d){this.b.Ia(this,
d);this.b.j()?(console.error("Error parsing message as JSON for peer '"+this.H+"', host kicking: ",d),this.S("data error")):console.error("Error parsing message as JSON for peer '"+this.H+"': ",d);console.log("String that failed to parse from previous error: "+f.data);return}if(h)try{h.c&&"m"!==h.c?this.Kj(h):this.b.fk(this,h)}catch(d){this.b.Ia(this,d),this.b.j()?(console.error("Error handling message for peer '"+this.H+"', host kicking: ",d),this.S("data error")):console.error("Error handling message for peer '"+
this.H+"': ",d)}}}else{!this.Te&&this.b.j()&&"u"===m&&(this.Te=!0,this.b.Oi(this.H));try{this.Jj(f.data)}catch(d){this.b.Ia(this,d),this.b.j()?(console.error("Error handling binary update for peer '"+this.H+"', host kicking: ",d),this.S("data error")):console.error("Error handling binary update for peer '"+this.H+"': ",d)}}}}Kj(m){switch(m.c){case "disconnect":m.k&&u(this.b,"peer-kicked");var f=!this.b.j()&&!this.j();this.S(m.r);f&&this.b.le();break;case "hi":this.b.j()||(this.b.O.ob(m.hn),this.b.N.ob(m.n),
this.b.Fi(m.d),this.b.Ki(m.u),this.b.ni(m.objs),this.b.mi(m.cvs));break;case "j":this.b.j()||(f=new p(this.b,m.i,m.a),f.ob(m.n),this.b.jg(f));break;case "l":!this.b.j()&&(f=this.b.Pc(m.i))&&(f.Sc()||this.b.ig(f,m.r),f.S(m.r));break;default:console.error("Unknown control message from peer '"+this.H+"': "+m.c),this.b.Ia(this,"unknown control message '"+m.c+"'")}}Jj(m){this.b.j()?this.Xj(m):this.gk(m)}Xj(m){m=new DataView(m);let f=0;var c=m.getUint32(f);f+=4;if(1664249200!==c)console.warn("Rejected packet with incorrect magic number (received '"+
c+"', expected '1664249200'");else if(c=m.getFloat64(f),f+=8,c+=this.zd,!(3E3<=Math.abs(c-performance.now()))){m.getUint8(f);f+=1;var h=m.getUint8(f);f+=1;var d=[],e=this.b.Ja;for(let l=0;l<h;++l)if(l>=e.length)d.push(0);else{var n=e[l];switch(n.hb){case 0:n=m.getFloat64(f);f+=8;break;case 1:n=m.getFloat32(f);f+=4;break;case 2:n=n.Vc(m.getInt16(f));f+=2;break;case 3:n=n.Vc(m.getUint8(f));f+=1;break;default:n=m.getFloat32(f),f+=4}d.push(n)}this.$i(c,d)}}$i(m,f){for(let c=0,h=this.wa.length;c<h;++c){const d=
this.wa[c];if(d.timestamp===m)return;if(d.timestamp>m){this.wa.splice(c,0,new k(m,f));return}}this.wa.push(new k(m,f))}ka(m){if(0!==this.wa.length){for(;2<this.wa.length&&this.wa[0]!==this.Fa&&this.wa[0]!==this.C&&this.wa[0]!==this.L;)this.wa.shift();if(!(this.L&&this.L.timestamp>m&&this.C&&this.C.timestamp<m)){this.L=null;for(let f=0,c=this.wa.length;f<c;++f){const h=this.wa[f];if(h.timestamp<=m){if(!this.C||h.timestamp>this.C.timestamp)this.Fa=this.C,this.C=h}else{this.L=h;break}}}}}gk(m){m=new DataView(m);
let f=0;var c=m.getUint32(f);f+=4;1664249200!==c?console.warn("Rejected packet with incorrect magic number (received '"+c+"', expected '1664249200'"):(c=m.getUint32(f),f+=4,0===c?this.zj(m,f):1===c?this.yj(m,f):console.warn("Ignoring packet with incorrect flags (received "+c+", expected 0 or 1"))}zj(m,f){const c=m.getFloat64(f);f+=8;const h=m.getUint16(f);f+=2;for(let l=0;l<h;++l){var d=m.getUint16(f);f+=2;var e=m.getUint8(f);f+=1;let q=null,r=0;const t=this.b.Lf(d);t?(q=t.xa,r=q.length,1===e&&t.al()):
console.warn("Don't know which object corresponds to NID "+d);d=m.getUint16(f);f+=2;e=m.getUint16(f);f+=2;for(let v=0;v<d;++v){const z=m.getUint16(f);f+=2;if(t){const y=[];let x=f;for(let F=0;F<r;++F){var n=q[F];switch(n.hb){case 0:n=m.getFloat64(x);x+=8;break;case 1:n=m.getFloat32(x);x+=4;break;case 2:n=n.Vc(m.getInt16(x));x+=2;break;case 3:n=n.Vc(m.getUint8(x));x+=1;break;default:n=m.getFloat32(x),x+=4}y.push(n)}t.Qd(c,z,y)}f+=e}}}yj(m,f){const c=m.getFloat64(f);f+=8;const h=m.getUint16(f);f+=2;
for(let e=0;e<h;++e){var d=m.getUint16(f);f+=2;const n=this.b.Lf(d);n||console.warn("Don't know which object corresponds to NID "+d);d=m.getUint16(f);f+=2;for(let l=0;l<d;++l){const q=m.getUint16(f);f+=2;n&&!n.Gb&&(this.b.Yj(n,q,c),n.ge(q))}}}S(m,f){this.Ic||(this.Ic=!0,this.Ej(m),this.cb("o",JSON.stringify({c:"disconnect",r:m,k:!!f})),Y(this.qb),Y(this.rb),Y(this.sb),Y(this.J),this.J=this.sb=this.rb=this.qb=null,this.oc=this.nc=this.lc=!1,this.b.Pk(this))}Ph(m){m=m.jc;if(!this.L&&!this.C)return 0;
if(this.L&&!this.C){var f=this.L.data;return 0>m||m>=f.length?0:f[m]}var c=this.b.Qc();let h,d;if(!this.L&&this.C){if(this.Fa){var e=this.Fa.timestamp;f=this.Fa.data[m];h=this.C.timestamp;d=this.C.data[m];c>this.C.timestamp+250&&(c=this.C.timestamp+250);e=pa(e,h,c);return a.Rc(this.b.Ja[m].bb(),f,d,e,!0)}f=this.C.data;return 0>m||m>=f.length?0:f[m]}e=this.C.timestamp;f=this.C.data[m];h=this.L.timestamp;d=this.L.data[m];e=pa(e,h,c);return a.Rc(this.b.Ja[m].bb(),f,d,e,!1)}}self.xh=p}"use strict";
{const k=self.Ef,a=self.xh,b=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection,g=window.RTCSessionDescription||window.webkitRTCSessionDescription||window.mozRTCSessionDescription||window.msRTCSessionDescription,p=window.RTCIceCandidate||window.webkitRTCIceCandidate||window.mozRTCIceCandidate||window.msRTCIceCandidate,m=window.RTCDataChannel||window.webkitRTCDataChannel||window.mozRTCDataChannel||window.msRTCDataChannel,f=[{urls:"stun:stun.l.google.com:19302"}];
let c=!1;const h=[];self.ya.Ga(class extends self.ab{constructor(d){super(d,"multiplayer");this.Xe=[];this.U=null;this.sa=this.Pa=!1;this.El={bh:0,version:0,name:"",Yg:"",Xg:""};this.la=this.Re=this.Qe=this.hf=this.jf="";this.Ka=[];this.Wa=new Map;this.Kb=0;this.Ld=new Set;this.O=this.N=null;this.Ba=80;this.zc=this.We=30;this.Ig=0;this.yb={Lc:0,$g:0,xf:0,Zg:0,Pd:0,Wg:0,wf:0,Vg:0,Od:0};this.nd=new ArrayBuffer(262144);this.Oe=new DataView(this.nd);this.Aa=[];this.Bl=1;this.Cc=new Map;this.Dc=new Map;
this.qf=this.rf=this.pf=0;this.vb=[];this.da=this.Qa=0;this.ma=this.Ya=this.Ba;this.Ja=[];this.md=new Map;this.mf=!1;this.we(f);setInterval(()=>this.nj(),2E3);window.addEventListener("unload",()=>this.Zb("quit"));B(this,"get-supported",()=>this.Tj());B(this,"add-ice-servers",e=>this.we(e.list));B(this,"simulate-latency",e=>this.Hi(e.latency,e.pdv,e.loss));B(this,"set-bandwidth-profile",e=>this.Ei(e.updateRate,e.delay));B(this,"tick",e=>this.ka(e));B(this,"alert",e=>this.hh(e));B(this,"signalling-connect",
e=>this.Pi(e.url));B(this,"signalling-disconnect",()=>this.Xf());B(this,"signalling-login",e=>this.Ri(e.alias));B(this,"signalling-join-room",e=>this.Qi(e.game,e.instance,e.room,e.maxClients));B(this,"signalling-auto-join-room",e=>this.Ni(e.game,e.instance,e.room,e.maxClients,e.lock));B(this,"signalling-leave-room",()=>this.le());B(this,"signalling-list-game-instances",e=>this.Si(e.game));B(this,"signalling-list-rooms",e=>this.Ti(e.game,e.instance,e.which));B(this,"disconnect-room",()=>this.Jf(!0));
B(this,"peer-send-message",e=>this.si(e));B(this,"host-broadcast",e=>this.pi(e));B(this,"kick-peer",e=>this.ri(e));B(this,"sync-object",e=>this.xi(e));B(this,"sync-inst-var",e=>this.wi(e));B(this,"associate-object",e=>this.oi(e));B(this,"remove-object-id",e=>this.fe(e.uid));B(this,"remove-net-insts",e=>this.ti(e));B(this,"remove-object-nid",e=>this.vi(e));B(this,"set-client-state",e=>this.Tf(e.tag,e.value));B(this,"add-client-input-value",e=>this.dh(e.tag,e.precision,e.interp))}tj(d){return d?"string"===
typeof d?d:"string"===typeof d.message?d.message:"string"===typeof d.details?d.details:"string"===typeof d.data?d.data:"string"===typeof d.type?d.type:"unknown error":"unknown error"}ae(){return this.Pa&&this.sa}Xb(){return this.ae()&&this.la}j(){return this.Xb()&&this.N&&this.O===this.N}Kh(){return this.ae()?this.Qe:""}Lh(){return this.ae()?this.Re:""}Mh(){return this.Xb()?this.la:""}Hi(d,e,n){this.pf=Math.max(d,0);this.rf=Math.max(e,0);this.qf=Math.max(n,0)}Tj(){return{isSupported:!(!b||!m)}}Pi(d){if(!this.U&&
!this.Pa){try{this.U=new WebSocket(d,"c2multiplayer")}catch(e){this.U=null;this.nb(e);return}this.U.onopen=()=>{-1===this.U.protocol.indexOf("c2multiplayer")?(this.nb("server does not support 'c2multiplayer' protocol"),this.U.close(1002,"'c2multiplayer' protocol required"),this.U=null,this.Pa=!1):this.Pa=!0};this.U.onclose=()=>{this.rk();this.sa=this.Pa=!1;this.U=null};this.U.onerror=e=>{console.error("Signalling server error: ",e);this.nb(e)};this.U.onmessage=e=>{this.sk(e)}}}Xf(){this.U&&this.Pa&&
(this.U.close(),this.U=null,this.Pa=!1)}sk(d){let e;try{e=JSON.parse(d.data)}catch(n){this.nb(n);return}switch(e.message){case "welcome":this.Ek(e);break;case "login-ok":this.zk(e);break;case "join-ok":this.wk(e);break;case "leave-ok":this.yk();break;case "kicked":this.xk();break;case "peer-joined":this.Bk(e);break;case "peer-quit":this.Ck(e);break;case "icecandidate":this.uk(e);break;case "offer":this.Ak(e);break;case "answer":this.tk(e);break;case "instance-list":this.vk(e);break;case "room-list":this.Dk(e);
break;case "error":this.nb(e.details);break;default:this.nb("received unknown signalling message")}}$h(d){for(const e of this.Xe)if(e.urls===d.urls)return!0;return!1}we(d){if(d)for(let e of d)"string"===typeof e&&(e={urls:e}),this.$h(e)||(e.hasOwnProperty("url")||(e.url=e.urls),this.Xe.push(e))}nb(d){u(this,"signalling-error",{message:this.tj(d)})}rk(){u(this,"signalling-close")}Ek(d){if(1>d.protocolrev||1<d.protocolrev)this.nb("signalling server protocol revision not supported"),this.Xf();else{this.jf=
d.clientid;var e=this.El;e.bh=d.protocolrev;e.version=d.version;e.name=d.name;e.Yg=d.operator;e.Xg=d.motd;this.we(d.ice_servers);u(this,"signalling-welcome",{myid:this.jf,sigservinfo:{protocolrev:e.bh,version:e.version,name:e.name,operator:e.Yg,motd:e.Xg}})}}zk(d){this.hf=d.alias;this.sa=!0;u(this,"signalling-login-ok",{myalias:this.hf})}Uh(){return this.Bl++}Af(){if(this.j()){do this.Kb++,65535<this.Kb&&(this.Kb=0);while(this.Ld.has(this.Kb));var d=this.Kb;this.Ld.add(d);return d}}Hh(d){this.j()&&
this.Ld.delete(d)}wk(d){this.Zb("disconnect");this.Qe=d.game;this.Re=d.instance;this.la=d.room;this.N=new a(this,this.jf,this.hf);d.host?(this.O=this.N,this.Kb=0,this.Ld.clear(),this.O.ob(this.Af())):(this.da=this.Qa=this.vb.length=0,this.Ba=80,this.zc=this.We=30,this.ma=this.Ya=this.Ba,this.O=new a(this,d.hostid,d.hostalias),this.O.Gf());u(this,"signalling-join-ok",{isHost:!!d.host,hostId:this.O.H,hostAlias:this.O.ea,game:this.Qe,gameInstance:this.Re,room:this.la})}yk(){this.la="";u(this,"signalling-leave-ok")}xk(){this.Jf();
this.la="";u(this,"signalling-kicked")}Bk(d){if(this.sa&&this.la&&this.j()){var e=this.Wa.get(d.peerid);e&&e.S("rejoin");(new a(this,d.peerid,d.peeralias)).Gf()}}Ck(d){if(this.sa&&this.la&&this.j()){var e=this.Wa.get(d.id);e&&e.S(d.reason)}}uk(d){if(this.sa&&this.la){var e=this.Wa.get(d.from);e&&e.aj(new p(d.icecandidate))}}Ak(d){if(this.sa&&this.la&&!this.j()&&this.N&&this.O&&this.O.ai()&&d.from===this.O.H){var e=this.O.J;e.setRemoteDescription(new g(d.offer)).then(()=>{e.createAnswer().then(n=>
{e.setLocalDescription(n);this.Ha({message:"answer",toclientid:this.O.H,answer:n})}).catch(n=>{console.error("Peer error creating answer: ",n);this.Ia(this.N,"could not create answer to host offer")})}).catch(n=>{console.error("Peer error setting remote description: ",n);this.Ia(this.N,"could not set remote description")})}}tk(d){if(this.sa&&this.la&&this.j()){var e=this.Wa.get(d.from);e&&e.J.setRemoteDescription(new g(d.answer)).catch(n=>{console.error("Host error setting remote description: ",n)})}}vk(d){u(this,
"signalling-instance-list",{list:d.list})}Dk(d){u(this,"signalling-room-list",{list:d.list})}Ha(d){this.U&&this.Pa&&this.U.send(JSON.stringify(d))}Ri(d){this.sa||this.Ha({message:"login",protocolrev:1,alias:d})}Qi(d,e,n,l){this.sa&&!this.la&&this.Ha({message:"join",game:d,instance:e,room:n,max_clients:l})}Ni(d,e,n,l,q){this.sa&&!this.la&&this.Ha({message:"auto-join",game:d,instance:e,room:n,max_clients:l,lock_when_full:q})}le(){this.sa&&this.Ha({message:"leave"})}Oi(d){this.sa&&this.j()&&this.Ha({message:"confirm-peer",
id:d})}Si(d){this.U&&this.Pa&&this.Ha({message:"list-instances",game:d})}Ti(d,e,n){this.U&&this.Pa&&this.Ha({message:"list-rooms",game:d,instance:e,which:n})}Jf(d){this.da=this.Qa=this.vb.length=0;this.Zb("disconnect");for(const e of this.Aa)e.Bh();d&&this.le()}bj(d){this.Ka.push(d);this.Wa.set(d.H,d);u(this,"add-peer",{id:d.H,alias:d.ea})}Pk(d){u(this,"remove-peer",{id:d.H});this.j()&&this.Hh(d.T);const e=this.Ka.indexOf(d);-1<e&&this.Ka.splice(e,1);this.Wa.delete(d.H);this.O===d&&(this.O=null,this.Zb("host quit"));
this.N===d&&(this.N=null,this.la="",this.Zb("disconnect"))}Zb(d){if(!c){for(c=!0;this.Ka.length;)this.Ka[0].S(d);c=!1}}Pc(d){return this.Wa.get(d)||null}Ih(d){return(d=this.Wa.get(d))?d.ea:""}pi(d){const e=d.fromId,n=d.tag,l=d.message;d=d.mode;const q=this.Pc(e);this.Wb(d,JSON.stringify({c:"m",t:n,f:e,m:l}),q)}Wb(d,e,n){if(this.j()){var l=this.Ka.slice(0);for(const q of l)q&&q!==this.N&&q!==n&&q.cb(d,e)}}nj(){const d=performance.now();if(this.j()){h.push(...this.Ka);for(const e of h)e&&e!==this.N&&
e.ie(d,!1);h.length=0}else this.O&&this.O.ie(d,!1)}gh(d){this.Aa.push(d);this.Dc.set(d.Fc,d);this.Cc.set(d.T,d)}Yh(){const d={};for(const [e,n]of this.Cc.entries())d[n.Gc]={nid:e,nvs:n.Th()};return d}ni(d){this.Cc.clear();for(const e of this.Aa)if(d.hasOwnProperty(e.Gc.toString())){const n=d[e.Gc.toString()];e.ob(n.nid);this.Cc.set(n.nid,e);e.Ii(n.nvs)}else console.warn("Could not map object SID '"+e.Gc+"' - host did not send NID for it"),e.ob(-1)}Lf(d){return this.Cc.get(d)||null}ka(d){if(!this.Xb())return null;
d=d.dt;const e=performance.now();e-this.Ig>=1E3/(this.j()?this.We:this.zc)-5&&(this.Di(e),this.Ig=e);const n=this.yb;1E3<=e-n.Lc&&(n.$g=n.xf,n.Zg=n.Pd,n.Wg=n.wf,n.Vg=n.Od,n.xf=0,n.Pd=0,n.wf=0,n.Od=0,n.Lc+=1E3,500<e-n.Lc&&(n.Lc=e),u(this,"stats",{stats:{outboundPerSec:n.$g,outboundBandwidthPerSec:n.Zg,inboundPerSec:n.Wg,inboundBandwidthPerSec:n.Vg}}));this.j()||(this.da<this.Qa?(this.da+=10*d,this.da>this.Qa&&(this.da=this.Qa)):this.da>this.Qa&&(this.da-=10*d,this.da<this.Qa&&(this.da=this.Qa)),this.ma<
this.Ya?(this.ma+=30*d,this.ma>this.Ya&&(this.ma=this.Ya)):this.ma>this.Ya&&(this.ma-=30*d,this.ma<this.Ya&&(this.ma=this.Ya)));d=this.Qc();for(const l of this.Ka)l.ka(d);for(const l of this.Aa)l.ka();return{simulationTime:this.Qc(),hostInputArrivalTime:this.Oh(),clientDelay:this.Ba,peerData:this.vj(),roData:this.wj(),isReadyForInput:this.Nf()}}vj(){const d={};for(const e of this.Ka){const n={};for(const l of this.Ja)n[l.Z]=e.Ph(l);d[e.H]={nid:e.T,latency:e.zd,pdv:e.Mg,clientState:n}}return d}wj(){const d=
{};for(const e of this.Aa)d[e.Fc]=e.Bb();return d}async Di(d){this.j()?(await this.Wk(d),this.Vk(d)):await this.Uk(d)}async Hj(){const d=await w(this,"before-client-update");for(const e of d.clientStateUpdates)this.Tf(e.tag,e.value)}async Uk(d){this.Nf()&&await this.Hj();if(this.N&&this.mf){var e=this.Oe,n=0,l=this.Ja,q=this.N.Jg,r=d-this.N.Fg,t=d-this.N.Gg;if(100>r||(1E3>r?95<=t:495<=t)){e.setUint32(n,1664249200);n+=4;e.setFloat64(n,d+this.da);n+=8;e.setUint8(n,0);n+=1;e.setUint8(n,l.length);n+=
1;for(let v=0,z=l.length;v<z;++v)r=l[v],t=0,v<q.length&&(t=r.Ff(q[v])),n=r.Yf(e,n,t);this.N.dl(d);this.O.cb("u",new Uint8Array(this.nd,0,n))}}}async Wk(d){const e=this.Oe;let n=0,l=0;const q=await w(this,"get-object-info",{ros:this.Aa.map(r=>r.Zh())});for(const r of this.Aa){const t=r.Fc;q.hasOwnProperty(t)&&(r.ne(q[t],d),0<r.xc&&l++)}if(0!==l){e.setUint32(n,1664249200);n+=4;e.setUint32(n,0);n+=4;e.setFloat64(n,d);n+=8;e.setUint16(n,l);n+=2;for(const r of this.Aa)0<r.xc&&(n=r.oe(e,n,d));this.Wb("u",
new Uint8Array(this.nd,0,n),null)}}Vk(d){const e=this.Oe;let n=0,l=0;for(const q of this.Aa)q.od.length&&l++;if(0!==l){e.setUint32(n,1664249200);n+=4;e.setUint32(n,1);n+=4;e.setFloat64(n,d);n+=8;e.setUint16(n,l);n+=2;for(const q of this.Aa)if(d=q.od,d.length){e.setUint16(n,q.T);n+=2;e.setUint16(n,d.length);n+=2;for(const r of d)e.setUint16(n,r),n+=2;d.length=0}this.Wb("r",new Uint8Array(this.nd,0,n),null)}}fh(d,e,n,l){if(!this.j()){this.Ya=l+this.Ba;d=d+n-e;0===this.vb.length&&(this.da=d,this.ma=
this.Ya);this.vb.push(d);30<this.vb.length&&this.vb.shift();h.push(...this.vb);h.sort((q,r)=>q-r);d=0;e=h.length;4<=h.length&&6>=h.length?(++d,--e):6<h.length&&19>=h.length?(d+=2,e-=2):19<h.length&&(d+=5,e-=5);n=0;for(l=d;l<e;++l)n+=h[l];this.Qa=n/(e-d);h.length=0}}Qc(){return this.j()?performance.now()-this.Ba:performance.now()+this.da-this.ma}Oh(){return this.j()?performance.now():performance.now()+this.da+this.ma}Tf(d,e){if(!this.j()&&this.N&&this.mf&&(d=this.md.get(d))){d=d.jc;var n=this.N.Jg;
n.length<d+1&&(n.length=d+1);n[d]!==e&&(n[d]=e,this.N.cl())}}dh(d,e,n){e=new k(this.Ja.length,n,e,d,null);this.md.set(d,e);this.Ja.push(e)}Jh(){const d=[];for(const e of this.Ja)d.push({tag:e.Z,precision:e.hb,interp:e.bb()});return d}mi(d){this.md.clear();this.Ja.length=0;for(let n=0,l=d.length;n<l;++n){var e=d[n];e=new k(n,e.interp,e.precision,e.tag,null);this.md.set(e.Z,e);this.Ja.push(e)}this.mf=!0}fe(d){for(const e of this.Aa)e.fe(d)}Nf(){return this.Xb()?this.j()?!0:0!==this.Qa:!1}Ei(d,e){this.Xb()||
(this.zc=this.We=d,this.Ba=e)}jg(d){u(this,"peer-open",{id:d.H,alias:d.ea})}si(d){const e=d.tag,n=d.message,l=d.mode;(d=this.Pc(d.id))&&d.cb(l,JSON.stringify({c:"m",t:e,m:n}))}ig(d,e){u(this,"peer-close",{id:d.H,alias:d.ea,reason:e||"unknown"})}Ia(d,e){console.error(`[Multiplayer] Peer '${d.ea}' (${d.H}) error: `,e)}fk(d,e){d=e.f||d.H;u(this,"peer-message",{tag:e.t,fromId:d,fromAlias:this.Ih(d),content:e.m})}Yj(d,e,n){u(this,"instance-destroyed",{roId:d.Fc,nid:e,timestamp:n})}ri(d){if(this.j()){var e=
d.reason;(d=this.Pc(d.id))&&d.S(e,!0)}}Xi(){this.yb.xf++}Vi(d){this.yb.Pd+=d}Wi(){this.yb.wf++}Ui(d){this.yb.Od+=d}Fi(d){this.Ba=d}Ki(d){this.zc=d}xi(d){const e=d.data,n=d.precision,l=d.bandwidth;for(const q of d.objectClasses)d=new self.yh(this,q.roId,q.sid,l),1===e?(d.$a(1,n,"x"),d.$a(1,n,"y")):2===e?d.$a(2,n,"a"):3===e&&(d.$a(1,n,"x"),d.$a(1,n,"y"),d.$a(2,n,"a"))}hh(d){alert(d.message)}wi(d){const e=d.precision,n=d.interp,l=d.cvt;for(const q of d.syncData)this.Dc.get(q.roId).$a(n,e,"iv",q.varIndex,
l)}oi(d){var e=d.peerId;const n=d.instUid;d=this.Dc.get(d.roId);e=this.Wa.get(e);d&&e&&this.j()&&d.yi(n,e.T)}ti(d){for(const [e,n]of Object.entries(d))if(d=this.Dc.get(parseInt(e,10)))for(const l of n)d.ge(l)}vi(d){const e=d.nid;(d=this.Dc.get(d.roId))&&d.ge(e)}})}"use strict";
async function qa(k){if(!k.xb)try{k.xb=await navigator.wakeLock.request("screen"),k.xb.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");k.xb=null;u(k,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),u(k,"wake-lock-acquired")}catch(a){console.warn("[Construct 3] Failed to acquire screen wake lock: ",a),u(k,"wake-lock-error")}}
function ra(){var k=document.body;const a=k.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");k=getComputedStyle(k);k=[k.getPropertyValue("--temp-sai-top"),k.getPropertyValue("--temp-sai-right"),k.getPropertyValue("--temp-sai-bottom"),k.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);
return isFinite(b)?b:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return k}
self.ya.Ga(class extends self.ab{constructor(k){super(k,"platform-info");C(this,[["get-initial-state",()=>this.Ce()],["request-wake-lock",()=>qa(this)],["release-wake-lock",()=>{this.xb&&(this.xb.release(),this.xb=null)}]]);window.addEventListener("resize",()=>{u(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:ra()})});this.xb=null}Ce(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:ra(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";
{const k=180/Math.PI;self.Ra=class extends self.ab{constructor(a){super(a,"audio");this.qd=this.o=null;this.ud=this.Ve=!1;this.ib=()=>this.sl();this.Ma=[];this.V=[];this.Ua=null;this.Eg="";this.Hg=-1;this.Ac=new Map;this.ef=1;this.fb=!1;this.tf=0;this.Jd=1;this.Se=0;this.Lg="HRTF";this.xg="inverse";this.Ng=600;this.Kg=1E4;this.Pg=1;this.zg=this.lf=!1;this.Fl=this.P.fi();this.Na=new Map;this.Eb=new Set;this.Ze=!1;this.ff="";this.wb=null;self.C3Audio_OnMicrophoneStream=(b,g)=>this.bk(b,g);this.pd=null;
self.C3Audio_GetOutputStream=()=>this.Sj();self.C3Audio_DOMInterface=this;C(this,[["create-audio-context",b=>this.kj(b)],["play",b=>this.Lk(b)],["stop",b=>this.ol(b)],["stop-all",()=>this.pl()],["set-paused",b=>this.hl(b)],["set-volume",b=>this.ml(b)],["fade-volume",b=>this.qj(b)],["set-master-volume",b=>this.fl(b)],["set-muted",b=>this.gl(b)],["set-silent",b=>this.jl(b)],["set-looping",b=>this.el(b)],["set-playback-rate",b=>this.il(b)],["seek",b=>this.Tk(b)],["preload",b=>this.Mk(b)],["unload",b=>
this.tl(b)],["unload-all",()=>this.ul()],["set-suspended",b=>this.kl(b)],["add-effect",b=>this.Zf(b)],["set-effect-param",b=>this.Zk(b)],["remove-effects",b=>this.Ok(b)],["tick",b=>this.Hk(b)],["load-state",b=>this.De(b)]])}async kj(a){a.isiOSCordova&&(this.lf=!0);this.tf=a.timeScaleMode;this.Lg=["equalpower","HRTF","soundfield"][a.panningModel];this.xg=["linear","inverse","exponential"][a.distanceModel];this.Ng=a.refDistance;this.Kg=a.maxDistance;this.Pg=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.o=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.o=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.$f();this.o.onstatechange=()=>{"running"!==this.o.state&&this.$f()};this.qd=this.o.createGain();this.qd.connect(this.o.destination);b=a.listenerPos;this.o.listener.setPosition(b[0],b[1],b[2]);this.o.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.Vd();try{await Promise.all(a.preloadList.map(g=>
this.ad(g.originalUrl,g.url,g.type,!1)))}catch(g){console.error("[Construct 3] Preloading sounds failed: ",g)}return{sampleRate:this.o.sampleRate}}$f(){this.ud||(this.Ve=!1,window.addEventListener("pointerup",this.ib,!0),window.addEventListener("touchend",this.ib,!0),window.addEventListener("click",this.ib,!0),window.addEventListener("keydown",this.ib,!0),this.ud=!0)}mj(){this.ud&&(this.Ve=!0,window.removeEventListener("pointerup",this.ib,!0),window.removeEventListener("touchend",this.ib,!0),window.removeEventListener("click",
this.ib,!0),window.removeEventListener("keydown",this.ib,!0),this.ud=!1)}sl(){if(!this.Ve){var a=this.o;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),g=a.createBufferSource();g.buffer=b;g.connect(a.destination);g.start(0);"running"===a.state&&this.mj()}}ua(){return this.o}Vd(){return this.o.currentTime}jb(){return this.qd}Kf(a){return(a=this.Na.get(a.toLowerCase()))?a[0].ja():this.jb()}eh(a,b){a=a.toLowerCase();let g=this.Na.get(a);g||(g=[],this.Na.set(a,g));b.bl(g.length);
b.ll(a);g.push(b);this.ng(a)}ng(a){let b=this.jb();const g=this.Na.get(a);if(g&&g.length){b=g[0].ja();for(let p=0,m=g.length;p<m;++p){const f=g[p];p+1===m?f.oa(this.jb()):f.oa(g[p+1].ja())}}for(const p of this.Za(a))p.Ai(b);this.wb&&this.ff===a&&(this.wb.disconnect(),this.wb.connect(b))}Oc(){return this.ef}Tc(){return this.fb}$k(){this.zg=!0}Eh(a,b){return b?this.P.vl(a).then(g=>{const p=this.o.createBuffer(1,g.length,48E3);p.getChannelData(0).set(g);return p}):new Promise((g,p)=>{this.o.decodeAudioData(a,
g,p)})}lb(a){this.P.lb(a)}Cb(a){this.P.Cb(a)}Rf(a){let b=0;for(let g=0,p=this.V.length;g<p;++g){const m=this.V[g];this.V[b]=m;m.fa===a?m.l():++b}this.V.length=b}Bi(){let a=0;for(let b=0,g=this.Ma.length;b<g;++b){const p=this.Ma[b];this.Ma[a]=p;p.kb()?p.l():++a}this.Ma.length=a}*Za(a){if(a)for(const b of this.V)self.Ra.Fh(b.Z,a)&&(yield b);else this.Ua&&!this.Ua.pa()&&(yield this.Ua)}async ad(a,b,g,p,m){for(const f of this.Ma)if(f.Vb()===b)return await sa(f),f;if(m)return null;p&&(this.lf||this.zg)&&
this.Bi();m="audio/webm; codecs=opus"===g&&!this.Fl;p&&m&&this.$k();a=!p||this.lf||m?new self.zh(this,a,b,g,p,m):new self.uh(this,a,b,g,p);this.Ma.push(a);await sa(a);return a}async re(a,b,g,p,m){for(const f of this.V)if(f.Vb()===b&&(f.Rd()||m))return f.Li(p),f;a=await this.ad(a,b,g,m);p="html5"===a.Ke?new self.vh(a.A,a,p):new self.Ah(a.A,a,p);this.V.push(p);return p}cj(a){let b=this.Ac.get(a);if(!b){let g=null;b={yf:0,promise:new Promise(p=>g=p),resolve:g};this.Ac.set(a,b)}b.yf++}Qk(a){const b=this.Ac.get(a);
if(!b)throw Error("expected pending tag");b.yf--;0===b.yf&&(b.resolve(),this.Ac.delete(a))}me(a){a||(a=this.Eg);return(a=this.Ac.get(a))?a.promise:Promise.resolve()}dd(){if(0<this.Eb.size)D(this);else for(const a of this.V)if(a.Mf()){D(this);break}}ka(){for(var a of this.Eb)a.ka();a=this.Vd();for(var b of this.V)b.ka(a);b=this.V.filter(g=>g.Mf()).map(g=>g.Ub());u(this,"state",{tickCount:this.Hg,audioInstances:b,analysers:[...this.Eb].map(g=>g.Nh())});0===b.length&&0===this.Eb.size&&this.vd&&(this.P.Rk(this.Sg),
this.vd=!1)}de(a,b,g){u(this,"trigger",{type:a,tag:b,aiid:g})}async Lk(a){const b=a.originalUrl,g=a.url,p=a.type,m=a.isMusic,f=a.tag,c=a.isLooping,h=a.vol,d=a.pos,e=a.panning;let n=a.off;0<n&&!a.trueClock&&(this.o.getOutputTimestamp?(a=this.o.getOutputTimestamp(),n=n-a.performanceTime/1E3+a.contextTime):n=n-performance.now()/1E3+this.o.currentTime);this.Eg=f;this.cj(f);try{this.Ua=await this.re(b,g,p,f,m),e?(this.Ua.Xc(!0),this.Ua.Ji(e.x,e.y,e.angle,e.innerAngle,e.outerAngle,e.outerGain),e.hasOwnProperty("uid")&&
this.Ua.Mi(e.uid)):this.Ua.Xc(!1),this.Ua.Play(c,h,d,n)}catch(l){console.error("[Construct 3] Audio: error starting playback: ",l);return}finally{this.Qk(f)}D(this)}ol(a){a=a.tag;for(const b of this.Za(a))b.eb()}pl(){for(const a of this.V)a.eb()}hl(a){const b=a.tag;a=a.paused;for(const g of this.Za(b))a?g.Yb():g.Wc();this.dd()}ml(a){const b=a.tag;a=a.vol;for(const g of this.Za(b))g.Zc(a)}async qj(a){const b=a.tag,g=a.vol,p=a.duration;a=a.stopOnEnd;await this.me(b);for(const m of this.Za(b))m.Gh(g,
p,a);this.dd()}fl(a){this.ef=a.vol;for(const b of this.V)b.jd()}gl(a){const b=a.tag;a=a.isMuted;for(const g of this.Za(b))g.Uf(a)}jl(a){this.fb=a.isSilent;this.P.Yc(this.fb);for(const b of this.V)b.hd()}el(a){const b=a.tag;a=a.isLooping;for(const g of this.Za(b))g.je(a)}async il(a){const b=a.tag;a=a.rate;await this.me(b);for(const g of this.Za(b))g.Wf(a)}async Tk(a){const b=a.tag;a=a.pos;await this.me(b);for(const g of this.Za(b))g.he(a)}async Mk(a){const b=a.originalUrl,g=a.url,p=a.type;a=a.isMusic;
try{await this.re(b,g,p,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async tl(a){if(a=await this.ad("",a.url,a.type,a.isMusic,!0))a.l(),a=this.Ma.indexOf(a),-1!==a&&this.Ma.splice(a,1)}ul(){for(const a of this.Ma)a.l();this.Ma.length=0}kl(a){a=a.isSuspended;!a&&this.o.resume&&this.o.resume();for(const b of this.V)b.ke(a);a&&this.o.suspend&&this.o.suspend()}Hk(a){this.Jd=a.timeScale;this.Se=a.gameTime;this.Hg=a.tickCount;if(0!==this.tf)for(var b of this.V)b.Db();(b=a.listenerPos)&&
this.o.listener.setPosition(b[0],b[1],b[2]);for(const g of a.instPans){a=g.uid;for(const p of this.V)p.Ta===a&&p.Vf(g.x,g.y,g.angle)}}async Zf(a){var b=a.type;const g=a.tag;var p=a.params;if("filter"===b)p=new self.oh(this,...p);else if("delay"===b)p=new self.mh(this,...p);else if("convolution"===b){b=null;try{b=await this.ad(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",m);return}p=new self.lh(this,b.La,...p);p.Xk(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)p=new self.ph(this,...p);else if("phaser"===b)p=new self.rh(this,...p);else if("gain"===b)p=new self.qh(this,...p);else if("tremolo"===b)p=new self.th(this,...p);else if("ringmod"===b)p=new self.sh(this,...p);else if("distortion"===b)p=new self.nh(this,...p);else if("compressor"===b)p=new self.kh(this,...p);else if("analyser"===b)p=new self.jh(this,...p);else throw Error("invalid effect type");this.eh(g,p);this.mg()}Zk(a){const b=a.index,g=a.param,p=a.value,m=a.ramp,
f=a.time;a=this.Na.get(a.tag);!a||0>b||b>=a.length||(a[b].za(g,p,m,f),this.mg())}Ok(a){a=a.tag.toLowerCase();const b=this.Na.get(a);if(b&&b.length){for(const g of b)g.l();this.Na.delete(a);this.ng(a)}}Zi(a){this.Eb.add(a);this.dd()}Nk(a){this.Eb.delete(a)}mg(){this.Ze||(this.Ze=!0,Promise.resolve().then(()=>this.oj()))}oj(){const a={};for(const [b,g]of this.Na)a[b]=g.map(p=>p.Ub());u(this,"fxstate",{fxstate:a});this.Ze=!1}async De(a){const b=a.saveLoadMode;if(3!==b)for(var g of this.V)g.kb()&&1===
b||(g.kb()||2!==b)&&g.eb();for(const p of this.Na.values())for(const m of p)m.l();this.Na.clear();this.Jd=a.timeScale;this.Se=a.gameTime;g=a.listenerPos;this.o.listener.setPosition(g[0],g[1],g[2]);this.fb=a.isSilent;this.P.Yc(this.fb);this.ef=a.masterVolume;g=[];for(const p of Object.values(a.effects))g.push(Promise.all(p.map(m=>this.Zf(m))));await Promise.all(g);await Promise.all(a.playing.map(p=>this.Dj(p,b)));this.dd()}async Dj(a,b){if(3!==b){var g=a.bufferOriginalUrl,p=a.bufferUrl,m=a.bufferType,
f=a.isMusic,c=a.tag,h=a.isLooping,d=a.volume,e=a.playbackTime;if(!f||1!==b)if(f||2!==b){b=null;try{b=await this.re(g,p,m,c,f)}catch(n){console.error("[Construct 3] Audio: error loading audio state: ",n);return}b.li(a.pan);b.Play(h,d,e,0);a.isPlaying||b.Yb();b.ve(a)}}}bk(a,b){this.wb&&this.wb.disconnect();this.ff=b.toLowerCase();this.wb=this.o.createMediaStreamSource(a);this.wb.connect(this.Kf(this.ff))}Sj(){this.pd||(this.pd=this.o.createMediaStreamDestination(),this.qd.connect(this.pd));return this.pd.stream}static Fh(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Yi(a){return a*k}static Dh(a){return Math.pow(10,a/20)}static If(a){return Math.max(Math.min(self.Ra.Dh(a),1),0)}static ki(a){return Math.log(a)/Math.log(10)*20}static ji(a){return self.Ra.ki(Math.max(Math.min(a,1),0))}static Hl(a,b){return 1-Math.exp(-b*a)}};self.ya.Ga(self.Ra)}"use strict";function sa(k){k.Ad||(k.Ad=k.ue());return k.Ad}
self.Cf=class{constructor(k,a,b,g,p){this.A=k;this.Cl=a;this.zb=b;this.na=g;this.yl=p;this.Ke="";this.Ad=null}l(){this.Ad=this.A=null}ue(){}ua(){return this.A.ua()}Xd(){return this.Cl}Vb(){return this.zb}Wd(){return this.na}kb(){return this.yl}Sa(){}};"use strict";
self.uh=class extends self.Cf{constructor(k,a,b,g,p){super(k,a,b,g,p);this.Ke="html5";this.aa=new Audio;this.aa.crossOrigin="anonymous";this.aa.autoplay=!1;this.aa.preload="auto";this.qc=this.rc=null;this.aa.addEventListener("canplaythrough",()=>!0);this.yc=this.ua().createGain();this.tc=null;this.aa.addEventListener("canplay",()=>{this.rc&&(this.rc(),this.qc=this.rc=null);!this.tc&&this.aa&&(this.tc=this.ua().createMediaElementSource(this.aa),this.tc.connect(this.yc))});this.onended=null;this.aa.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.aa.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.zb}' error: `,m);this.qc&&(this.qc(m),this.qc=this.rc=null)})}l(){this.A.Rf(this);this.yc.disconnect();this.yc=null;this.tc.disconnect();this.tc=null;this.aa&&!this.aa.paused&&this.aa.pause();this.aa=this.onended=null;super.l()}ue(){return new Promise((k,a)=>{this.rc=k;this.qc=a;this.aa.src=this.zb})}ia(){return this.aa}Sa(){return this.aa.duration}};"use strict";
async function ta(k){if(k.pb)return k.pb;var a=k.A.P;if("cordova"===a.ca&&a.gi(k.zb)&&"file:"===location.protocol)k.pb=await a.Sd(k.zb);else{a=await fetch(k.zb);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);k.pb=await a.arrayBuffer()}}async function ua(k){if(k.La)return k.La;k.La=await k.A.Eh(k.pb,k.Al);k.pb=null}
self.zh=class extends self.Cf{constructor(k,a,b,g,p,m){super(k,a,b,g,p);this.Ke="webaudio";this.La=this.pb=null;this.Al=!!m}l(){this.A.Rf(this);this.La=this.pb=null;super.l()}async ue(){try{await ta(this),await ua(this)}catch(k){console.error(`[Construct 3] Failed to load audio '${this.zb}': `,k)}}Sa(){return this.La?this.La.duration:0}};"use strict";
{let k=0;self.Df=class{constructor(a,b,g){this.A=a;this.fa=b;this.Z=g;this.kd=k++;this.ga=this.ua().createGain();this.ga.connect(this.jb());this.M=null;this.mc=!1;this.X=!0;this.ra=this.Xa=this.W=!1;this.Hc=1;this.Hb=!1;this.Ea=1;a=this.A.tf;this.$e=1===a&&!this.kb()||2===a;this.ec=this.Ta=-1;this.Rg=!1}l(){this.fa=this.A=null;this.M&&(this.M.disconnect(),this.M=null);this.ga.disconnect();this.ga=null}ua(){return this.A.ua()}jb(){return this.A.Kf(this.Z)}Oc(){return this.A.Oc()}Nc(){return this.$e?
this.A.Se:performance.now()/1E3}Xd(){return this.fa.Xd()}Vb(){return this.fa.Vb()}Wd(){return this.fa.Wd()}kb(){return this.fa.kb()}Li(a){this.Z=a}pa(){}Rd(){}IsPlaying(){return!this.X&&!this.W&&!this.pa()}Mf(){return!this.X&&!this.pa()}Ab(){}Sa(){return this.fa.Sa()}Play(){}eb(){}Yb(){}Wc(){}Zc(a){this.Hc=a;this.ga.gain.cancelScheduledValues(0);this.ec=-1;this.ga.gain.value=this.Yd()}Gh(a,b,g){if(!this.Hb){a*=this.Oc();var p=this.ga.gain;p.cancelScheduledValues(0);var m=this.A.Vd();b=m+b;p.setValueAtTime(p.value,
m);p.linearRampToValueAtTime(a,b);this.Hc=a;this.ec=b;this.Rg=g}}jd(){this.Zc(this.Hc)}ka(a){-1!==this.ec&&a>=this.ec&&(this.ec=-1,this.Rg&&this.eb(),this.A.de("fade-ended",this.Z,this.kd))}Yd(){const a=this.Hc*this.Oc();return isFinite(a)?a:0}Uf(a){a=!!a;this.Hb!==a&&(this.Hb=a,this.hd())}Tc(){return this.A.Tc()}hd(){}je(){}Wf(a){this.Ea!==a&&(this.Ea=a,this.Db())}Db(){}he(){}ke(){}Xc(a){a=!!a;this.mc!==a&&((this.mc=a)?(this.M||(this.M=this.ua().createPanner(),this.M.panningModel=this.A.Lg,this.M.distanceModel=
this.A.xg,this.M.refDistance=this.A.Ng,this.M.maxDistance=this.A.Kg,this.M.rolloffFactor=this.A.Pg),this.ga.disconnect(),this.ga.connect(this.M),this.M.connect(this.jb())):(this.M.disconnect(),this.ga.disconnect(),this.ga.connect(this.jb())))}Ji(a,b,g,p,m,f){this.mc&&(this.Vf(a,b,g),a=self.Ra.Yi,this.M.coneInnerAngle=a(p),this.M.coneOuterAngle=a(m),this.M.coneOuterGain=f)}Vf(a,b,g){this.mc&&(this.M.setPosition(a,b,0),this.M.setOrientation(Math.cos(g),Math.sin(g),0))}Mi(a){this.Ta=a}Zd(){}Ai(a){const b=
this.M||this.ga;b.disconnect();b.connect(a)}Ub(){return{aiid:this.kd,tag:this.Z,duration:this.Sa(),volume:this.Hc,isPlaying:this.IsPlaying(),playbackTime:this.Ab(),playbackRate:this.Ea,uid:this.Ta,bufferOriginalUrl:this.Xd(),bufferUrl:"",bufferType:this.Wd(),isMusic:this.kb(),isLooping:this.ra,isMuted:this.Hb,resumePosition:this.Zd(),pan:this.Vh()}}ve(a){this.Wf(a.playbackRate);this.Uf(a.isMuted)}Vh(){if(!this.M)return null;const a=this.M;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.Ta}}li(a){a?(this.Xc(!0),a=this.M,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.Ta=a.uid):this.Xc(!1)}}}"use strict";
self.vh=class extends self.Df{constructor(k,a,b){super(k,a,b);this.fa.yc.connect(this.ga);this.fa.onended=()=>this.ze()}l(){this.eb();this.fa.yc.disconnect();super.l()}ia(){return this.fa.ia()}ze(){this.X=!0;this.Ta=-1;this.A.de("ended",this.Z,this.kd)}pa(){return this.ia().ended}Rd(){return this.X?!0:this.pa()}Ab(k){let a=this.ia().currentTime;k&&(a*=this.Ea);this.ra||(a=Math.min(a,this.Sa()));return a}Play(k,a,b){const g=this.ia();1!==g.playbackRate&&(g.playbackRate=1);g.loop!==k&&(g.loop=k);this.Zc(a);
g.muted&&(g.muted=!1);if(g.currentTime!==b)try{g.currentTime=b}catch(p){console.warn(`[Construct 3] Exception seeking audio '${this.fa.Vb()}' to position '${b}': `,p)}this.A.lb(g);this.W=this.X=!1;this.ra=k;this.Ea=1}eb(){const k=this.ia();k.paused||k.pause();this.A.Cb(k);this.X=!0;this.W=!1;this.Ta=-1}Yb(){if(!(this.W||this.X||this.pa())){var k=this.ia();k.paused||k.pause();this.A.Cb(k);this.W=!0}}Wc(){!this.W||this.X||this.pa()||(this.A.lb(this.ia()),this.W=!1)}hd(){this.ia().muted=this.Hb||this.Tc()}je(k){k=
!!k;this.ra!==k&&(this.ra=k,this.ia().loop=k)}Db(){let k=this.Ea;this.$e&&(k*=this.A.Jd);try{this.ia().playbackRate=k}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${k}':`,a)}}he(k){if(!this.X&&!this.pa())try{this.ia().currentTime=k}catch(a){console.warn(`[Construct 3] Error seeking audio to '${k}': `,a)}}Zd(){return this.Ab()}ke(k){k?this.IsPlaying()?(this.ia().pause(),this.Xa=!0):this.Xa=!1:this.Xa&&(this.A.lb(this.ia()),this.Xa=!1)}};"use strict";
function Z(k){k.B&&k.B.disconnect();k.B=null;k.ac=null}
self.Ah=class extends self.Df{constructor(k,a,b){super(k,a,b);this.B=null;this.Dd=g=>this.ze(g);this.Ue=!0;this.ac=null;this.ha=this.Id=0;this.gf=1}l(){this.eb();Z(this);this.Dd=null;super.l()}ze(k){this.W||this.Xa||k.target!==this.ac||(this.X=this.Ue=!0,this.Ta=-1,Z(this),this.A.de("ended",this.Z,this.kd))}pa(){return!this.X&&this.B&&this.B.loop||this.W?!1:this.Ue}Rd(){return!this.B||this.X?!0:this.pa()}Ab(k){let a;a=this.W?this.ha:this.Nc()-this.Id;k&&(a*=this.Ea);this.ra||(a=Math.min(a,this.Sa()));
return a}Play(k,a,b,g){this.gf=1;this.Zc(a);Z(this);this.B=this.ua().createBufferSource();this.B.buffer=this.fa.La;this.B.connect(this.ga);this.ac=this.B;this.B.onended=this.Dd;this.B.loop=k;this.B.start(g,b);this.W=this.X=this.Ue=!1;this.ra=k;this.Ea=1;this.Id=this.Nc()-b}eb(){if(this.B)try{this.B.stop(0)}catch(k){}this.X=!0;this.W=!1;this.Ta=-1}Yb(){this.W||this.X||this.pa()||(this.ha=this.Ab(!0),this.ra&&(this.ha%=this.Sa()),this.W=!0,this.B.stop(0))}Wc(){!this.W||this.X||this.pa()||(Z(this),this.B=
this.ua().createBufferSource(),this.B.buffer=this.fa.La,this.B.connect(this.ga),this.ac=this.B,this.B.onended=this.Dd,this.B.loop=this.ra,this.jd(),this.Db(),this.Id=this.Nc()-this.ha/(this.Ea||.001),this.B.start(0,this.ha),this.W=!1)}Yd(){return super.Yd()*this.gf}hd(){this.gf=this.Hb||this.Tc()?0:1;this.jd()}je(k){k=!!k;this.ra!==k&&(this.ra=k,this.B&&(this.B.loop=k))}Db(){let k=this.Ea;this.$e&&(k*=this.A.Jd);this.B&&(this.B.playbackRate.value=k)}he(k){this.X||this.pa()||(this.W?this.ha=k:(this.Yb(),
this.ha=k,this.Wc()))}Zd(){return this.ha}ke(k){k?this.IsPlaying()?(this.Xa=!0,this.ha=this.Ab(!0),this.ra&&(this.ha%=this.Sa()),this.B.stop(0)):this.Xa=!1:this.Xa&&(Z(this),this.B=this.ua().createBufferSource(),this.B.buffer=this.fa.La,this.B.connect(this.ga),this.ac=this.B,this.B.onended=this.Dd,this.B.loop=this.ra,this.jd(),this.Db(),this.Id=this.Nc()-this.ha/(this.Ea||.001),this.B.start(0,this.ha),this.Xa=!1)}ve(k){super.ve(k);this.ha=k.resumePosition}};"use strict";
{class k{constructor(a){this.A=a;this.o=a.ua();this.jc=-1;this.na=this.Z="";this.s=null}l(){this.o=null}bl(a){this.jc=a}ll(a){this.Z=a}G(){return this.o.createGain()}ja(){}oa(){}F(a,b,g,p){a.cancelScheduledValues(0);if(0===p)a.value=b;else{var m=this.o.currentTime;p+=m;switch(g){case 0:a.setValueAtTime(b,p);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,p);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,p)}}}Ub(){return{type:this.na,tag:this.Z,params:this.s}}}
self.oh=class extends k{constructor(a,b,g,p,m,f,c){super(a);this.na="filter";this.s=[b,g,p,m,f,c];this.D=this.G();this.h=this.G();this.h.gain.value=c;this.g=this.G();this.g.gain.value=1-c;this.K=this.o.createBiquadFilter();this.K.type=b;this.K.frequency.value=g;this.K.detune.value=p;this.K.Q.value=m;this.K.gain.vlaue=f;this.D.connect(this.K);this.D.connect(this.g);this.K.connect(this.h)}l(){this.D.disconnect();this.K.disconnect();this.h.disconnect();this.g.disconnect();super.l()}oa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}ja(){return this.D}za(a,b,g,p){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[5]=b;this.F(this.h.gain,b,g,p);this.F(this.g.gain,1-b,g,p);break;case 1:this.s[1]=b;this.F(this.K.frequency,b,g,p);break;case 2:this.s[2]=b;this.F(this.K.detune,b,g,p);break;case 3:this.s[3]=b;this.F(this.K.Q,b,g,p);break;case 4:this.s[4]=b,this.F(this.K.gain,b,g,p)}}};self.mh=class extends k{constructor(a,b,g,p){super(a);this.na="delay";this.s=[b,g,p];this.D=
this.G();this.h=this.G();this.h.gain.value=p;this.g=this.G();this.g.gain.value=1-p;this.sc=this.G();this.qa=this.o.createDelay(b);this.qa.delayTime.value=b;this.dc=this.G();this.dc.gain.value=g;this.D.connect(this.sc);this.D.connect(this.g);this.sc.connect(this.h);this.sc.connect(this.qa);this.qa.connect(this.dc);this.dc.connect(this.sc)}l(){this.D.disconnect();this.h.disconnect();this.g.disconnect();this.sc.disconnect();this.qa.disconnect();this.dc.disconnect();super.l()}oa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}ja(){return this.D}za(a,b,g,p){const m=self.Ra.If;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[2]=b;this.F(this.h.gain,b,g,p);this.F(this.g.gain,1-b,g,p);break;case 4:this.s[1]=m(b);this.F(this.dc.gain,m(b),g,p);break;case 5:this.s[0]=b,this.F(this.qa.delayTime,b,g,p)}}};self.lh=class extends k{constructor(a,b,g,p){super(a);this.na="convolution";this.s=[g,p];this.tg=this.sg="";this.D=this.G();this.h=this.G();this.h.gain.value=p;this.g=
this.G();this.g.gain.value=1-p;this.cc=this.o.createConvolver();this.cc.normalize=g;this.cc.buffer=b;this.D.connect(this.cc);this.D.connect(this.g);this.cc.connect(this.h)}l(){this.D.disconnect();this.cc.disconnect();this.h.disconnect();this.g.disconnect();super.l()}oa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ja(){return this.D}za(a,b,g,p){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.s[1]=b,this.F(this.h.gain,b,g,p),this.F(this.g.gain,1-b,g,p)}}Xk(a,
b){this.sg=a;this.tg=b}Ub(){const a=super.Ub();a.bufferOriginalUrl=this.sg;a.bufferUrl="";a.bufferType=this.tg;return a}};self.ph=class extends k{constructor(a,b,g,p,m,f){super(a);this.na="flanger";this.s=[b,g,p,m,f];this.D=this.G();this.g=this.G();this.g.gain.value=1-f/2;this.h=this.G();this.h.gain.value=f/2;this.fc=this.G();this.fc.gain.value=m;this.qa=this.o.createDelay(b+g);this.qa.delayTime.value=b;this.I=this.o.createOscillator();this.I.frequency.value=p;this.Y=this.G();this.Y.gain.value=g;
this.D.connect(this.qa);this.D.connect(this.g);this.qa.connect(this.h);this.qa.connect(this.fc);this.fc.connect(this.qa);this.I.connect(this.Y);this.Y.connect(this.qa.delayTime);this.I.start(0)}l(){this.I.stop(0);this.D.disconnect();this.qa.disconnect();this.I.disconnect();this.Y.disconnect();this.g.disconnect();this.h.disconnect();this.fc.disconnect();super.l()}oa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ja(){return this.D}za(a,b,g,p){switch(a){case 0:b=Math.max(Math.min(b/
100,1),0);this.s[4]=b;this.F(this.h.gain,b/2,g,p);this.F(this.g.gain,1-b/2,g,p);break;case 6:this.s[1]=b/1E3;this.F(this.Y.gain,b/1E3,g,p);break;case 7:this.s[2]=b;this.F(this.I.frequency,b,g,p);break;case 8:this.s[3]=b/100,this.F(this.fc.gain,b/100,g,p)}}};self.rh=class extends k{constructor(a,b,g,p,m,f,c){super(a);this.na="phaser";this.s=[b,g,p,m,f,c];this.D=this.G();this.g=this.G();this.g.gain.value=1-c/2;this.h=this.G();this.h.gain.value=c/2;this.K=this.o.createBiquadFilter();this.K.type="allpass";
this.K.frequency.value=b;this.K.detune.value=g;this.K.Q.value=p;this.I=this.o.createOscillator();this.I.frequency.value=f;this.Y=this.G();this.Y.gain.value=m;this.D.connect(this.K);this.D.connect(this.g);this.K.connect(this.h);this.I.connect(this.Y);this.Y.connect(this.K.frequency);this.I.start(0)}l(){this.I.stop(0);this.D.disconnect();this.K.disconnect();this.I.disconnect();this.Y.disconnect();this.g.disconnect();this.h.disconnect();super.l()}oa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();
this.g.connect(a)}ja(){return this.D}za(a,b,g,p){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[5]=b;this.F(this.h.gain,b/2,g,p);this.F(this.g.gain,1-b/2,g,p);break;case 1:this.s[0]=b;this.F(this.K.frequency,b,g,p);break;case 2:this.s[1]=b;this.F(this.K.detune,b,g,p);break;case 3:this.s[2]=b;this.F(this.K.Q,b,g,p);break;case 6:this.s[3]=b;this.F(this.Y.gain,b,g,p);break;case 7:this.s[4]=b,this.F(this.I.frequency,b,g,p)}}};self.qh=class extends k{constructor(a,b){super(a);this.na="gain";this.s=
[b];this.v=this.G();this.v.gain.value=b}l(){this.v.disconnect();super.l()}oa(a){this.v.disconnect();this.v.connect(a)}ja(){return this.v}za(a,b,g,p){const m=self.Ra.If;switch(a){case 4:this.s[0]=m(b),this.F(this.v.gain,m(b),g,p)}}};self.th=class extends k{constructor(a,b,g){super(a);this.na="tremolo";this.s=[b,g];this.v=this.G();this.v.gain.value=1-g/2;this.I=this.o.createOscillator();this.I.frequency.value=b;this.Y=this.G();this.Y.gain.value=g/2;this.I.connect(this.Y);this.Y.connect(this.v.gain);
this.I.start(0)}l(){this.I.stop(0);this.I.disconnect();this.Y.disconnect();this.v.disconnect();super.l()}oa(a){this.v.disconnect();this.v.connect(a)}ja(){return this.v}za(a,b,g,p){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[1]=b;this.F(this.v.gain.value,1-b/2,g,p);this.F(this.Y.gain.value,b/2,g,p);break;case 7:this.s[0]=b,this.F(this.I.frequency,b,g,p)}}};self.sh=class extends k{constructor(a,b,g){super(a);this.na="ringmod";this.s=[b,g];this.D=this.G();this.h=this.G();this.h.gain.value=
g;this.g=this.G();this.g.gain.value=1-g;this.Ec=this.G();this.Ec.gain.value=0;this.I=this.o.createOscillator();this.I.frequency.value=b;this.I.connect(this.Ec.gain);this.I.start(0);this.D.connect(this.Ec);this.D.connect(this.g);this.Ec.connect(this.h)}l(){this.I.stop(0);this.I.disconnect();this.Ec.disconnect();this.D.disconnect();this.h.disconnect();this.g.disconnect();super.l()}oa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ja(){return this.D}za(a,b,g,p){switch(a){case 0:b=
Math.max(Math.min(b/100,1),0);this.s[1]=b;this.F(this.h.gain,b,g,p);this.F(this.g.gain,1-b,g,p);break;case 7:this.s[0]=b,this.F(this.I.frequency,b,g,p)}}};self.nh=class extends k{constructor(a,b,g,p,m,f){super(a);this.na="distortion";this.s=[b,g,p,m,f];this.D=this.G();this.Fd=this.G();this.Ed=this.G();this.Yk(p,m);this.h=this.G();this.h.gain.value=f;this.g=this.G();this.g.gain.value=1-f;this.Nd=this.o.createWaveShaper();this.Ne=new Float32Array(65536);this.sj(b,g);this.Nd.curve=this.Ne;this.D.connect(this.Fd);
this.D.connect(this.g);this.Fd.connect(this.Nd);this.Nd.connect(this.Ed);this.Ed.connect(this.h)}l(){this.D.disconnect();this.Fd.disconnect();this.Nd.disconnect();this.Ed.disconnect();this.h.disconnect();this.g.disconnect();super.l()}Yk(a,b){.01>a&&(a=.01);this.Fd.gain.value=a;this.Ed.gain.value=Math.pow(1/a,.6)*b}sj(a,b){for(let g=0;32768>g;++g){let p=g/32768;p=this.nl(p,a,b);this.Ne[32768+g]=p;this.Ne[32768-g-1]=-p}}nl(a,b,g){g=1.05*g*b-b;const p=0>a?-a:a;return(p<b?p:b+g*self.Ra.Hl(p-b,1/g))*(0>
a?-1:1)}oa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ja(){return this.D}za(a,b,g,p){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.s[4]=b,this.F(this.h.gain,b,g,p),this.F(this.g.gain,1-b,g,p)}}};self.kh=class extends k{constructor(a,b,g,p,m,f){super(a);this.na="compressor";this.s=[b,g,p,m,f];this.v=this.o.createDynamicsCompressor();this.v.threshold.value=b;this.v.knee.value=g;this.v.ratio.value=p;this.v.attack.value=m;this.v.release.value=f}l(){this.v.disconnect();
super.l()}oa(a){this.v.disconnect();this.v.connect(a)}ja(){return this.v}za(){}};self.jh=class extends k{constructor(a,b,g){super(a);this.na="analyser";this.s=[b,g];this.v=this.o.createAnalyser();this.v.fftSize=b;this.v.smoothingTimeConstant=g;this.yg=new Float32Array(this.v.frequencyBinCount);this.Qg=new Uint8Array(b);this.Og=this.Lb=0;this.A.Zi(this)}l(){this.A.Nk(this);this.v.disconnect();super.l()}ka(){this.v.getFloatFrequencyData(this.yg);this.v.getByteTimeDomainData(this.Qg);const a=this.v.fftSize;
let b=this.Lb=0;for(var g=0;g<a;++g){let p=(this.Qg[g]-128)/128;0>p&&(p=-p);this.Lb<p&&(this.Lb=p);b+=p*p}g=self.Ra.ji;this.Lb=g(this.Lb);this.Og=g(Math.sqrt(b/a))}oa(a){this.v.disconnect();this.v.connect(a)}ja(){return this.v}za(){}Nh(){return{tag:this.Z,index:this.jc,peak:this.Lb,rms:this.Og,binCount:this.v.frequencyBinCount,freqBins:this.yg}}}}"use strict";self.ya.Ga(class extends self.ab{constructor(k){super(k,"mouse");B(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
function va(k){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>u(k,"sw-message",a.data))}
function wa(k){k=k.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(k).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(k):screen.webkitLockOrientation?a=screen.webkitLockOrientation(k):screen.mozLockOrientation?a=screen.mozLockOrientation(k):screen.msLockOrientation&&(a=screen.msLockOrientation(k));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.ya.Ga(class extends self.ab{constructor(k){super(k,"browser");this.ca="";C(this,[["get-initial-state",a=>this.Ce(a)],["ready-for-sw-messages",()=>va(this)],["alert",a=>this.xe(a)],["close",()=>this.ye()],["set-focus",a=>this.Ge(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>wa(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var g=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a?window.open(b,"_blank"):this.Tl||(2===g?window.top.location=b:1===g?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,g=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,g))}],["request-fullscreen",
a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():
document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{u(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{u(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{u(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",
()=>{u(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;u(this,"backbutton")})}Ce(k){this.ca=k.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==
typeof window.is_scirra_arcade}}xe(k){alert(k.message)}ye(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}Ge(k){k=k.isFocus;if("nwjs"===this.ca){const a="nwjs"===this.ca?nw.Window.get():null;k?a.focus():a.blur()}else k?window.focus():window.blur()}});"use strict";
{const k=window.speechSynthesis||window.webkitSpeechSynthesis||window.mozSpeechSynthesis||window.msSpeechSynthesis,a=window.SpeechSynthesisUtterance||window.webkitSpeechSynthesisUtterance||window.mozSpeechSynthesisUtterance||window.msSpeechSynthesisUtterance;self.ya.Ga(class extends self.ab{constructor(b){super(b,"speech-synthesis");this.vf=[];B(this,"get-voices",()=>this.Vj());B(this,"speak-text",g=>this.Fk(g));B(this,"stop-speaking",()=>this.Gk());B(this,"pause-speaking",()=>this.ek());B(this,"resume-speaking",
()=>this.nk())}Vj(){k&&(this.vf=k.getVoices());return{isSupported:!!k,voices:this.vf.map(b=>({name:b.name,lang:b.lang,voiceURI:b.voiceURI}))}}xj(b){for(const g of this.vf)if(g.voiceURI===b)return g;return null}Fk(b){const g=new a(b.text);b.lang&&(g.lang=b.lang);b.voiceURI&&(g.voice=this.xj(b.voiceURI),g.voiceURI=b.voiceURI);g.volume=b.volume;g.rate=b.rate;g.pitch=b.pitch;g.onend=()=>u(this,"speech-ended");g.onerror=()=>u(this,"speech-error");k.speak(g)}Gk(){k.cancel()}ek(){k.pause()}nk(){k.resume()}})};