'use strict';function A(h,a,b,d){h.M.ge(h.fc,a,b,d,void 0)}function B(h,a,b){return h.M.Wf(h.fc,a,b,void 0,void 0)}function D(h,a,b,d){h.M.lb?A(h,a,b,d):h.M.yj()._OnMessageFromDOM({type:"event",component:h.fc,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function E(h,a,b){h.M.R(h.fc,a,b)}function F(h,a){for(const [b,d]of a)E(h,b,d)}function G(h){h.yd||(h.M.hj(h.Zg),h.yd=!0)}window.ab=class{constructor(h,a){this.M=h;this.fc=a;this.yd=!1;this.Zg=()=>this.la()}Gf(){}la(){}};
function H(h){-1!==h.Ub&&(self.clearTimeout(h.Ub),h.Ub=-1)}window.Di=class{constructor(h,a){this.Te=h;this.Gl=a;this.Ub=-1;this.Ad=-Infinity;this.$g=()=>{this.Ub=-1;this.Ad=Date.now();this.mc=!0;this.Te();this.mc=!1};this.Bg=this.mc=!1}l(){H(this);this.$g=this.Te=null}};"use strict";
function I(h,a){const b=a.elementId,d=h.Xb(b,a);h.Da.set(b,d);a.isVisible||(d.style.display="none");a=h.xe(d);a.addEventListener("focus",()=>{J(h,"elem-focused",b)});a.addEventListener("blur",()=>{J(h,"elem-blurred",b)});h.od&&document.body.appendChild(d)}function K(h,a,b){E(h,a,d=>{const k=h.Da.get(d.elementId);return b(k,d)})}function J(h,a,b,d){d||(d={});d.elementId=b;A(h,a,d)}function M(h,a,b,d){d||(d={});d.elementId=b;D(h,a,d)}
window.Qc=class extends self.ab{constructor(h,a){super(h,a);this.Da=new Map;this.od=!0;F(this,[["create",b=>I(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Da.get(b);this.Of(d);this.od&&d.parentElement.removeChild(d);this.Da.delete(b)}}],["set-visible",b=>{this.od&&(this.Da.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.od){var d=this.Da.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+
"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Da.get(b.elementId);this.fb(d,b)}}],["focus",b=>this.Ne(b)],["set-css-style",b=>{this.Da.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Da.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Da.get(b.elementId).removeAttribute(b.name)}]]);K(this,"get-element",b=>b)}Xb(){throw Error("required override");}Of(){}fb(){throw Error("required override");}xe(h){return h}Ne(h){const a=
this.xe(this.Da.get(h.elementId));h.focus?a.focus():a.blur()}};"use strict";
{const h=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function a(z){if(z.Sl){const q=document.createElement("script");q.async=!1;q.textContent=z.Vl;document.head.appendChild(q)}else return new Promise((q,r)=>{const g=document.createElement("script");g.onload=q;g.onerror=r;g.async=!1;g.src=z;document.head.appendChild(g)})}let b=new Audio;const d={"audio/webm; codecs=opus":!!b.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!b.canPlayType("audio/ogg; codecs=opus"),
"audio/webm; codecs=vorbis":!!b.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!b.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!b.canPlayType("audio/mp4"),"audio/mpeg":!!b.canPlayType("audio/mpeg")};b=null;async function k(z){z=await w(z);return(new TextDecoder("utf-8")).decode(z)}function w(z){return new Promise((q,r)=>{const g=new FileReader;g.onload=m=>q(m.target.result);g.onerror=m=>r(m);g.readAsArrayBuffer(z)})}const l=[];let f=0;window.RealFile=window.File;const n=
[],c=new Map,e=new Map;let p=0;const v=[];self.gm=function(z){if("function"!==typeof z)throw Error("runOnStartup called without a function");v.push(z)};const x=new Set(["cordova","playable-ad","instant-games"]);window.wa=class z{constructor(q){this.lb=q.Xl;this.ib=null;this.fa="";this.Ld=q.Ul;this.Oc={};this.hb=this.Mb=this.Nc=null;this.ud=[];this.tc=this.ca=this.Sb=null;this.Rb=-1;this.Ml=()=>this.qk();this.Qb=[];this.T=q.ah;!this.lb||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation||
(this.lb=!1);x.has(this.T)&&this.lb&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.lb=!1);this.Fd=this.Va=null;"html5"!==this.T&&"playable-ad"!==this.T||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.R("runtime","cordova-fetch-local-file",r=>
this.Rj(r));this.R("runtime","create-job-worker",()=>this.Sj());"cordova"===this.T?document.addEventListener("deviceready",()=>this.lg(q)):this.lg(q)}l(){this.te();this.ib&&(this.ib=this.ib.onmessage=null);this.Nc&&(this.Nc.terminate(),this.Nc=null);this.Mb&&(this.Mb.l(),this.Mb=null);this.ca&&(this.ca.parentElement.removeChild(this.ca),this.ca=null)}Uf(){return h&&"cordova"===this.T}Yc(){return h&&x.has(this.T)||navigator.standalone}async lg(q){"preview"===this.T&&(this.hb=document.createElement("div"),
this.hb.className="previewLoadingMessage",this.hb.textContent=q.em,document.body.appendChild(this.hb));if("playable-ad"===this.T){this.Va=self.c3_base64files;this.Fd={};await this.mj();for(let g=0,m=q.Wb.length;g<m;++g){var r=q.Wb[g].toLowerCase();this.Fd.hasOwnProperty(r)?q.Wb[g]={Sl:!0,Vl:this.Fd[r]}:this.Va.hasOwnProperty(r)&&(q.Wb[g]=URL.createObjectURL(this.Va[r]))}}q.Pl?this.fa=q.Pl:(r=location.origin,this.fa=("null"===r?"file:///":r)+location.pathname,r=this.fa.lastIndexOf("/"),-1!==r&&(this.fa=
this.fa.substr(0,r+1)));if(q.Zl)for(const [g,m]of Object.entries(q.Zl))this.Oc[g]=URL.createObjectURL(m);r=new MessageChannel;this.ib=r.port1;this.ib.onmessage=g=>this._OnMessageFromRuntime(g.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(g=>this.gk(g));this.tc=new self.mi(this);await N(this.tc);this.Vf();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.lb?await this.Fj(q,r.port2):
await this.Ej(q,r.port2)}ze(q){return this.Oc.hasOwnProperty(q)?this.Oc[q]:q.endsWith("/workermain.js")&&this.Oc.hasOwnProperty("workermain.js")?this.Oc["workermain.js"]:"playable-ad"===this.T&&this.Va.hasOwnProperty(q.toLowerCase())?URL.createObjectURL(this.Va[q.toLowerCase()]):q}async Yd(q,r,g){if(q.startsWith("blob:"))return new Worker(q,g);if(this.Uf()&&"file:"===location.protocol)return q=await this.Xd(this.Ld+q),new Worker(URL.createObjectURL(new Blob([q],{type:"application/javascript"})),g);
q=new URL(q,r);if(location.origin!==q.origin){q=await fetch(q);if(!q.ok)throw Error("failed to fetch worker script");q=await q.blob();return new Worker(URL.createObjectURL(q),g)}return new Worker(q,g)}qb(){return Math.max(window.innerWidth,1)}pb(){return Math.max(window.innerHeight,1)}Vf(){if(this.Yc()){const q=document.documentElement.style,r=document.body.style,g=window.innerWidth<window.innerHeight,m=g?window.screen.width:window.screen.height;r.height=q.height=(g?window.screen.height:window.screen.width)+
"px";r.width=q.width=m+"px"}}jg(q){var r=this.tc;return{baseUrl:this.fa,windowInnerWidth:this.qb(),windowInnerHeight:this.pb(),devicePixelRatio:window.devicePixelRatio,isFullscreen:z.de(),projectData:q.fm,previewImageBlobs:window.cr_previewImageBlobs||this.Va,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:q.ah,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.dm,jobScheduler:{inputPort:r.ef,outputPort:r.sf,maxNumWorkers:r.Il},supportedAudioFormats:d,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||
this.Ld+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Ld+"opus.wasm.wasm",isiOSCordova:this.Uf(),isiOSWebView:this.Yc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Fj(q,r){var g=this.ze(q.Yl);this.Nc=await this.Yd(g,this.fa,{name:"Runtime"});this.ca=document.createElement("canvas");this.ca.style.display="none";g=this.ca.transferControlToOffscreen();document.body.appendChild(this.ca);window.c3canvas=this.ca;this.Nc.postMessage(Object.assign(this.jg(q),{type:"init-runtime",
isInWorker:!0,messagePort:r,canvas:g,workerDependencyScripts:q.Ef||[],engineScripts:q.Wb,projectScripts:window.cm,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[r,g,...O(this.tc)]);this.ud=n.map(m=>new m(this));this.ig();self.c3_callFunction=(m,u)=>this.Sb.Gj(m,u);"preview"===this.T&&(self.goToLastErrorScript=()=>this.ge("runtime","go-to-last-error-script"))}async Ej(q,r){this.ca=document.createElement("canvas");this.ca.style.display="none";document.body.appendChild(this.ca);window.c3canvas=
this.ca;this.ud=n.map(m=>new m(this));this.ig();const g=q.Wb.map(m=>"string"===typeof m?(new URL(m,this.fa)).toString():m);Array.isArray(q.Ef)&&g.unshift(...q.Ef);await Promise.all(g.map(m=>a(m)));if(q.ih&&0<q.ih.length){const m=self.C3_ProjectScriptsStatus;try{if(await Promise.all(q.ih.map(u=>a(u[1]))),Object.values(m).some(u=>!u)){self.setTimeout(()=>this.vg(m),100);return}}catch(u){console.error("[Preview] Error loading project scripts: ",u);self.setTimeout(()=>this.vg(m),100);return}}"preview"===
this.T&&"object"!==typeof self.$l.am?(this.kd(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(q=Object.assign(this.jg(q),{isInWorker:!1,messagePort:r,canvas:this.ca,runOnStartupFunctions:v}),this.ng(),this.Mb=self.C3_CreateRuntime(q),await self.C3_InitRuntime(this.Mb,q))}vg(q){this.kd();q=`Failed to load project script '${Object.entries(q).filter(r=>
!r[1]).map(r=>r[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+q);alert(q)}ng(){this.kd()}kd(){this.hb&&(this.hb.parentElement.removeChild(this.hb),this.hb=null)}async Sj(){const q=await P(this.tc);return{outputPort:q,transferables:[q]}}yj(){if(this.lb)throw Error("not available in worker mode");return this.Mb}ge(q,r,g,m,u){this.ib.postMessage({type:"event",component:q,handler:r,dispatchOpts:m||null,data:g,responseId:null},u)}Wf(q,r,g,m,u){const t=p++,y=new Promise((C,
L)=>{e.set(t,{resolve:C,reject:L})});this.ib.postMessage({type:"event",component:q,handler:r,dispatchOpts:m||null,data:g,responseId:t},u);return y}["_OnMessageFromRuntime"](q){const r=q.type;if("event"===r)return this.Xj(q);if("result"===r)this.uk(q);else if("runtime-ready"===r)this.wk();else if("alert-error"===r)this.kd(),alert(q.message);else if("creating-runtime"===r)this.ng();else throw Error(`unknown message '${r}'`);}Xj(q){const r=q.component,g=q.handler,m=q.data,u=q.responseId;if(q=c.get(r))if(q=
q.get(g)){var t=null;try{t=q(m)}catch(y){console.error(`Exception in '${r}' handler '${g}':`,y);null!==u&&this.hd(u,!1,""+y);return}if(null===u)return t;t&&t.then?t.then(y=>this.hd(u,!0,y)).catch(y=>{console.error(`Rejection from '${r}' handler '${g}':`,y);this.hd(u,!1,""+y)}):this.hd(u,!0,t)}else console.warn(`[DOM] No handler '${g}' for component '${r}'`);else console.warn(`[DOM] No event handlers for component '${r}'`)}hd(q,r,g){let m;g&&g.transferables&&(m=g.transferables);this.ib.postMessage({type:"result",
responseId:q,isOk:r,result:g},m)}uk(q){const r=q.responseId,g=q.isOk;q=q.result;const m=e.get(r);g?m.resolve(q):m.reject(q);e.delete(r)}R(q,r,g){let m=c.get(q);m||(m=new Map,c.set(q,m));if(m.has(r))throw Error(`[DOM] Component '${q}' already has handler '${r}'`);m.set(r,g)}static za(q){if(n.includes(q))throw Error("DOM handler already added");n.push(q)}ig(){for(const q of this.ud)if("runtime"===q.fc){this.Sb=q;return}throw Error("cannot find runtime DOM handler");}gk(q){this.ge("debugger","message",
q)}wk(){for(const q of this.ud)q.Gf()}static de(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}hj(q){this.Qb.push(q);this.Qe()}al(q){q=this.Qb.indexOf(q);if(-1===q)throw Error("invalid callback");this.Qb.splice(q,1);this.Qb.length||this.te()}Qe(){-1===this.Rb&&this.Qb.length&&(this.Rb=requestAnimationFrame(this.Ml))}te(){-1!==this.Rb&&(cancelAnimationFrame(this.Rb),this.Rb=-1)}qk(){this.Rb=-1;for(const q of this.Qb)q();this.Qe()}ob(q){this.Sb.ob(q)}Gb(q){this.Sb.Gb(q)}Pe(){this.Sb.Pe()}bd(q){this.Sb.bd(q)}ji(){return!!d["audio/webm; codecs=opus"]}async El(q){q=
await this.Wf("runtime","opus-decode",{arrayBuffer:q},null,[q]);return new Float32Array(q)}ii(q){return/^(?:[a-z]+:)?\/\//.test(q)||"data:"===q.substr(0,5)||"blob:"===q.substr(0,5)}ki(q){return!this.ii(q)}async Rj(q){const r=q.filename;switch(q.as){case "text":return await this.Jh(r);case "buffer":return await this.Xd(r);default:throw Error("unsupported type");}}Mf(q){const r=window.cordova.file.applicationDirectory+"www/"+q.toLowerCase();return new Promise((g,m)=>{window.resolveLocalFileSystemURL(r,
u=>{u.file(g,m)},m)})}async Jh(q){q=await this.Mf(q);return await k(q)}ue(){if(l.length&&!(8<=f)){f++;var q=l.shift();this.nj(q.filename,q.Wl,q.Rl)}}Xd(q){return new Promise((r,g)=>{l.push({filename:q,Wl:m=>{f--;this.ue();r(m)},Rl:m=>{f--;this.ue();g(m)}});this.ue()})}async nj(q,r,g){try{const m=await this.Mf(q),u=await w(m);r(u)}catch(m){g(m)}}async mj(){const q=[];for(const [r,g]of Object.entries(this.Va))q.push(this.lj(r,g));await Promise.all(q)}async lj(q,r){if("object"===typeof r)this.Va[q]=
new Blob([r.str],{type:r.type}),this.Fd[q]=r.str;else{let g=await this.vj(r);g||(g=this.pj(r));this.Va[q]=g}}async vj(q){try{return await (await fetch(q)).blob()}catch(r){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",r),null}}pj(q){q=this.Uk(q);return this.kj(q.data,q.Tl)}Uk(q){var r=q.indexOf(",");if(0>r)throw new URIError("expected comma in data: uri");
var g=q.substring(r+1);r=q.substring(5,r).split(";");q=r[0]||"";const m=r[2];g="base64"===r[1]||"base64"===m?atob(g):decodeURIComponent(g);return{Tl:q,data:g}}kj(q,r){var g=q.length;let m=g>>2,u=new Uint8Array(g),t=new Uint32Array(u.buffer,0,m),y,C;for(C=y=0;y<m;++y)t[y]=q.charCodeAt(C++)|q.charCodeAt(C++)<<8|q.charCodeAt(C++)<<16|q.charCodeAt(C++)<<24;for(g&=3;g--;)u[C]=q.charCodeAt(C),++C;return new Blob([u],{type:r})}}}"use strict";
{const h=self.wa;function a(g){return g.sourceCapabilities&&g.sourceCapabilities.firesTouchEvents||g.originalEvent&&g.originalEvent.sourceCapabilities&&g.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},k={dispatchUserScriptEvent:!0},w={dispatchRuntimeEvent:!0};function l(g){return new Promise((m,u)=>{const t=document.createElement("link");t.onload=()=>m(t);t.onerror=y=>u(y);t.rel=
"stylesheet";t.href=g;document.head.appendChild(t)})}function f(g){return new Promise((m,u)=>{const t=new Image;t.onload=()=>m(t);t.onerror=y=>u(y);t.src=g})}async function n(g){g=URL.createObjectURL(g);try{return await f(g)}finally{URL.revokeObjectURL(g)}}function c(g){return new Promise((m,u)=>{let t=new FileReader;t.onload=y=>m(y.target.result);t.onerror=y=>u(y);t.readAsText(g)})}async function e(g,m,u){if(!/firefox/i.test(navigator.userAgent))return await n(g);var t=await c(g);t=(new DOMParser).parseFromString(t,
"image/svg+xml");const y=t.documentElement;if(y.hasAttribute("width")&&y.hasAttribute("height")){const C=y.getAttribute("width"),L=y.getAttribute("height");if(!C.includes("%")&&!L.includes("%"))return await n(g)}y.setAttribute("width",m+"px");y.setAttribute("height",u+"px");t=(new XMLSerializer).serializeToString(t);g=new Blob([t],{type:"image/svg+xml"});return await n(g)}function p(g){do{if(g.parentNode&&g.hasAttribute("contenteditable"))return!0;g=g.parentNode}while(g);return!1}const v=new Set(["canvas",
"body","html"]);function x(g){v.has(g.target.tagName.toLowerCase())&&g.preventDefault()}function z(g){(g.metaKey||g.ctrlKey)&&g.preventDefault()}self.C3_GetSvgImageSize=async function(g){g=await n(g);if(0<g.width&&0<g.height)return[g.width,g.height];{g.style.position="absolute";g.style.left="0px";g.style.top="0px";g.style.visibility="hidden";document.body.appendChild(g);const m=g.getBoundingClientRect();document.body.removeChild(g);return[m.width,m.height]}};self.C3_RasterSvgImageBlob=async function(g,
m,u,t,y){g=await e(g,m,u);const C=document.createElement("canvas");C.width=t;C.height=y;C.getContext("2d").drawImage(g,0,0,m,u);return C};let q=!1;document.addEventListener("pause",()=>q=!0);document.addEventListener("resume",()=>q=!1);function r(){try{return window.parent&&window.parent.document.hasFocus()}catch(g){return!1}}h.za(class extends self.ab{constructor(g){super(g,"runtime");this.Ig=!0;this.Tb=-1;this.yf="any";this.wg=this.xg=!1;this.jf=this.Fc=this.xb=null;g.R("canvas","update-size",t=>
this.Sk(t));g.R("runtime","invoke-download",t=>this.ek(t));g.R("runtime","raster-svg-image",t=>this.rk(t));g.R("runtime","get-svg-image-size",t=>this.$j(t));g.R("runtime","set-target-orientation",t=>this.Ak(t));g.R("runtime","register-sw",()=>this.sk());g.R("runtime","post-to-debugger",t=>this.rg(t));g.R("runtime","go-to-script",t=>this.rg(t));g.R("runtime","before-start-ticking",()=>this.Nj());g.R("runtime","debug-highlight",t=>this.Tj(t));g.R("runtime","enable-device-orientation",()=>this.jj());
g.R("runtime","enable-device-motion",()=>this.ij());g.R("runtime","add-stylesheet",t=>this.Lj(t));g.R("runtime","alert",t=>this.Ee(t));g.R("runtime","hide-cordova-splash",()=>this.bk());const m=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",t=>{const y=t.target;m.has(y.tagName.toLowerCase())||p(y)||t.preventDefault()});const u=g.ca;window.addEventListener("selectstart",x);window.addEventListener("gesturehold",x);u.addEventListener("selectstart",x);u.addEventListener("gesturehold",
x);window.addEventListener("touchstart",x,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",x,{passive:!1}),u.addEventListener("pointerdown",x)):u.addEventListener("touchstart",x);this.yc=0;window.addEventListener("mousedown",t=>{1===t.button&&t.preventDefault()});window.addEventListener("mousewheel",z,{passive:!1});window.addEventListener("wheel",z,{passive:!1});window.addEventListener("resize",()=>this.Tk());g.Yc()&&window.addEventListener("focusout",()=>{{const C=
document.activeElement;if(C){var t=C.tagName.toLowerCase();var y=new Set("email number password search tel text url".split(" "));t="textarea"===t?!0:"input"===t?y.has(C.type.toLowerCase()||"text"):p(C)}else t=!1}t||(document.scrollingElement.scrollTop=0)});this.Nb=new Set;this.Gd=new WeakSet;this.gb=!1}Nj(){"cordova"===this.M.T?(document.addEventListener("pause",()=>this.Oe(!0)),document.addEventListener("resume",()=>this.Oe(!1))):document.addEventListener("visibilitychange",()=>this.Oe(document.hidden));
return{isSuspended:!(!document.hidden&&!q)}}Gf(){window.addEventListener("focus",()=>this.jd("window-focus"));window.addEventListener("blur",()=>{this.jd("window-blur",{parentHasFocus:r()});this.yc=0});window.addEventListener("fullscreenchange",()=>this.He());window.addEventListener("webkitfullscreenchange",()=>this.He());window.addEventListener("mozfullscreenchange",()=>this.He());window.addEventListener("fullscreenerror",m=>this.Ie(m));window.addEventListener("webkitfullscreenerror",m=>this.Ie(m));
window.addEventListener("mozfullscreenerror",m=>this.Ie(m));window.addEventListener("keydown",m=>this.og("keydown",m));window.addEventListener("keyup",m=>this.og("keyup",m));window.addEventListener("dblclick",m=>this.Le("dblclick",m,d));window.addEventListener("wheel",m=>this.ik(m));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",m=>{this.Ae(m);this.dc("pointerdown",m)}),this.M.lb&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Fc=new self.Di(()=>this.tj(),
5),this.Fc.Bg=!0,window.addEventListener("pointerrawupdate",m=>this.nk(m))):window.addEventListener("pointermove",m=>this.dc("pointermove",m)),window.addEventListener("pointerup",m=>this.dc("pointerup",m)),window.addEventListener("pointercancel",m=>this.dc("pointercancel",m))):(window.addEventListener("mousedown",m=>{this.Ae(m);this.Me("pointerdown",m)}),window.addEventListener("mousemove",m=>this.Me("pointermove",m)),window.addEventListener("mouseup",m=>this.Me("pointerup",m)),window.addEventListener("touchstart",
m=>{this.Ae(m);this.gd("pointerdown",m)}),window.addEventListener("touchmove",m=>this.gd("pointermove",m)),window.addEventListener("touchend",m=>this.gd("pointerup",m)),window.addEventListener("touchcancel",m=>this.gd("pointercancel",m)));const g=()=>this.Pe();window.addEventListener("pointerup",g,!0);window.addEventListener("touchend",g,!0);window.addEventListener("click",g,!0);window.addEventListener("keydown",g,!0);window.addEventListener("gamepadconnected",g,!0)}jd(g,m){A(this,g,m||null,w)}qb(){return this.M.qb()}pb(){return this.M.pb()}Tk(){const g=
this.qb(),m=this.pb();this.jd("window-resize",{innerWidth:g,innerHeight:m,devicePixelRatio:window.devicePixelRatio});this.M.Yc()&&(-1!==this.Tb&&clearTimeout(this.Tb),this.sg(g,m,0))}bl(g,m,u){-1!==this.Tb&&clearTimeout(this.Tb);this.Tb=setTimeout(()=>this.sg(g,m,u),48)}sg(g,m,u){const t=this.qb(),y=this.pb();this.Tb=-1;t!=g||y!=m?this.jd("window-resize",{innerWidth:t,innerHeight:y,devicePixelRatio:window.devicePixelRatio}):10>u&&this.bl(t,y,u+1)}Ak(g){this.yf=g.targetOrientation}Al(){const g=this.yf;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(g).catch(m=>console.warn("[Construct 3] Failed to lock orientation: ",m));else try{let m=!1;screen.lockOrientation?m=screen.lockOrientation(g):screen.webkitLockOrientation?m=screen.webkitLockOrientation(g):screen.mozLockOrientation?m=screen.mozLockOrientation(g):screen.msLockOrientation&&(m=screen.msLockOrientation(g));m||console.warn("[Construct 3] Failed to lock orientation")}catch(m){console.warn("[Construct 3] Failed to lock orientation: ",
m)}}He(){const g=h.de();g&&"any"!==this.yf&&this.Al();A(this,"fullscreenchange",{isFullscreen:g,innerWidth:this.qb(),innerHeight:this.pb()})}Ie(g){console.warn("[Construct 3] Fullscreen request failed: ",g);A(this,"fullscreenerror",{isFullscreen:h.de(),innerWidth:this.qb(),innerHeight:this.pb()})}Oe(g){g?this.M.te():this.M.Qe();A(this,"visibilitychange",{hidden:g})}og(g,m){"Backspace"===m.key&&x(m);const u=b.get(m.code)||m.code;D(this,g,{code:u,key:m.key,which:m.which,repeat:m.repeat,altKey:m.altKey,
ctrlKey:m.ctrlKey,metaKey:m.metaKey,shiftKey:m.shiftKey,timeStamp:m.timeStamp},d)}ik(g){A(this,"wheel",{clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,deltaX:g.deltaX,deltaY:g.deltaY,deltaZ:g.deltaZ,deltaMode:g.deltaMode,timeStamp:g.timeStamp},d)}Le(g,m,u){a(m)||D(this,g,{button:m.button,buttons:m.buttons,clientX:m.clientX,clientY:m.clientY,pageX:m.pageX,pageY:m.pageY,timeStamp:m.timeStamp},u)}Me(g,m){if(!a(m)){var u=this.yc;"pointerdown"===g&&0!==u?g="pointermove":"pointerup"===
g&&0!==m.buttons&&(g="pointermove");D(this,g,{pointerId:1,pointerType:"mouse",button:m.button,buttons:m.buttons,lastButtons:u,clientX:m.clientX,clientY:m.clientY,pageX:m.pageX,pageY:m.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:m.timeStamp},d);this.yc=m.buttons;this.Le(m.type,m,k)}}dc(g,m){if(this.Fc&&"pointermove"!==g){var u=this.Fc;u.mc||(H(u),u.Ad=Date.now())}u=0;"mouse"===m.pointerType&&(u=this.yc);D(this,g,{pointerId:m.pointerId,pointerType:m.pointerType,
button:m.button,buttons:m.buttons,lastButtons:u,clientX:m.clientX,clientY:m.clientY,pageX:m.pageX,pageY:m.pageY,width:m.width||0,height:m.height||0,pressure:m.pressure||0,tangentialPressure:m.tangentialPressure||0,tiltX:m.tiltX||0,tiltY:m.tiltY||0,twist:m.twist||0,timeStamp:m.timeStamp},d);"mouse"===m.pointerType&&(u="mousemove","pointerdown"===g?u="mousedown":"pointerup"===g&&(u="pointerup"),this.Le(u,m,k),this.yc=m.buttons)}nk(g){this.jf=g;g=this.Fc;if(-1===g.Ub){var m=Date.now(),u=m-g.Ad,t=g.Gl;
u>=t&&g.Bg?(g.Ad=m,g.mc=!0,g.Te(),g.mc=!1):g.Ub=self.setTimeout(g.$g,Math.max(t-u,4))}}tj(){this.dc("pointermove",this.jf);this.jf=null}gd(g,m){for(let u=0,t=m.changedTouches.length;u<t;++u){const y=m.changedTouches[u];D(this,g,{pointerId:y.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:y.clientX,clientY:y.clientY,pageX:y.pageX,pageY:y.pageY,width:2*(y.radiusX||y.webkitRadiusX||0),height:2*(y.radiusY||y.webkitRadiusY||0),pressure:y.force||y.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:y.rotationAngle||0,timeStamp:m.timeStamp},d)}}Ae(g){window!==window.top&&window.focus();this.mg(g.target)&&document.activeElement&&!this.mg(document.activeElement)&&document.activeElement.blur()}mg(g){return!g||g===document||g===window||g===document.body||"canvas"===g.tagName.toLowerCase()}jj(){this.xg||(this.xg=!0,window.addEventListener("deviceorientation",g=>this.Vj(g)),window.addEventListener("deviceorientationabsolute",g=>this.Wj(g)))}ij(){this.wg||(this.wg=!0,window.addEventListener("devicemotion",
g=>this.Uj(g)))}Vj(g){A(this,"deviceorientation",{absolute:!!g.absolute,alpha:g.alpha||0,beta:g.beta||0,gamma:g.gamma||0,timeStamp:g.timeStamp,webkitCompassHeading:g.webkitCompassHeading,webkitCompassAccuracy:g.webkitCompassAccuracy},d)}Wj(g){A(this,"deviceorientationabsolute",{absolute:!!g.absolute,alpha:g.alpha||0,beta:g.beta||0,gamma:g.gamma||0,timeStamp:g.timeStamp},d)}Uj(g){let m=null;var u=g.acceleration;u&&(m={x:u.x||0,y:u.y||0,z:u.z||0});u=null;var t=g.accelerationIncludingGravity;t&&(u={x:t.x||
0,y:t.y||0,z:t.z||0});t=null;const y=g.rotationRate;y&&(t={alpha:y.alpha||0,beta:y.beta||0,gamma:y.gamma||0});A(this,"devicemotion",{acceleration:m,accelerationIncludingGravity:u,rotationRate:t,interval:g.interval,timeStamp:g.timeStamp},d)}Sk(g){const m=this.M,u=m.ca;u.style.width=g.styleWidth+"px";u.style.height=g.styleHeight+"px";u.style.marginLeft=g.marginLeft+"px";u.style.marginTop=g.marginTop+"px";m.Vf();this.Ig&&(u.style.display="",this.Ig=!1)}ek(g){const m=g.url;g=g.filename;const u=document.createElement("a"),
t=document.body;u.textContent=g;u.href=m;u.download=g;t.appendChild(u);u.click();t.removeChild(u)}async rk(g){var m=g.imageBitmapOpts;g=await self.C3_RasterSvgImageBlob(g.blob,g.imageWidth,g.imageHeight,g.surfaceWidth,g.surfaceHeight);m=m?await createImageBitmap(g,m):await createImageBitmap(g);return{imageBitmap:m,transferables:[m]}}async $j(g){return await self.C3_GetSvgImageSize(g.blob)}async Lj(g){await l(g.url)}Pe(){var g=[...this.Nb];this.Nb.clear();if(!this.gb)for(const m of g)(g=m.play())&&
g.catch(()=>{this.Gd.has(m)||this.Nb.add(m)})}ob(g){if("function"!==typeof g.play)throw Error("missing play function");this.Gd.delete(g);let m;try{m=g.play()}catch(u){this.Nb.add(g);return}m&&m.catch(()=>{this.Gd.has(g)||this.Nb.add(g)})}Gb(g){this.Nb.delete(g);this.Gd.add(g)}bd(g){this.gb=!!g}bk(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Tj(g){if(g.show){this.xb||(this.xb=document.createElement("div"),this.xb.id="inspectOutline",document.body.appendChild(this.xb));
var m=this.xb;m.style.display="";m.style.left=g.left-1+"px";m.style.top=g.top-1+"px";m.style.width=g.width+2+"px";m.style.height=g.height+2+"px";m.textContent=g.name}else this.xb&&(this.xb.style.display="none")}sk(){window.C3_RegisterSW&&window.C3_RegisterSW()}rg(g){window.c3_postToMessagePort&&(g.from="runtime",window.c3_postToMessagePort(g))}Gj(g,m){return B(this,"js-invoke-function",{name:g,params:m})}Ee(g){alert(g.message)}})}"use strict";
async function N(h){if(h.Fl)throw Error("already initialised");h.Fl=!0;var a=h.Kd.ze("dispatchworker.js");h.We=await h.Kd.Yd(a,h.fa,{name:"DispatchWorker"});a=new MessageChannel;h.ef=a.port1;h.We.postMessage({type:"_init","in-port":a.port2},[a.port2]);h.sf=await P(h)}function O(h){return[h.ef,h.sf]}
async function P(h){const a=h.Jg.length;var b=h.Kd.ze("jobworker.js");b=await h.Kd.Yd(b,h.fa,{name:"JobWorker"+a});const d=new MessageChannel,k=new MessageChannel;h.We.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":k.port2},[d.port2,k.port2]);h.Jg.push(b);return k.port1}
self.mi=class{constructor(h){this.Kd=h;this.fa=h.fa;this.fa="preview"===h.T?this.fa+"c3/workers/":this.fa+h.Ld;this.Il=Math.min(navigator.hardwareConcurrency||2,16);this.We=null;this.Jg=[];this.sf=this.ef=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.wa({Xl:!1,Yl:"workermain.js",Wb:["scripts/c3runtime.js"],Ul:"scripts/",Ef:[],ah:"html5"}));"use strict";
{function h(a){a.stopPropagation()}self.wa.za(class extends self.Qc{constructor(a){super(a,"list");K(this,"set-selected-index",(b,d)=>this.zk(b,d.selectedIndex));K(this,"add-item",(b,d)=>this.Kj(b,d));K(this,"remove-item",(b,d)=>this.tk(b,d));K(this,"set-item",(b,d)=>this.yk(b,d));K(this,"clear",b=>this.Pj(b));K(this,"load-state",(b,d)=>this.Ke(b,d))}Xb(a,b){const d=b.isDropdown,k=b.isMultiSelect,w=b.items,l=document.createElement("select");l.style.position="absolute";l.style.userSelect="none";l.style.webkitUserSelect=
"none";l.multiple=k;d||(l.size=2);for(const f of w)l.add(this.ve(f));l.addEventListener("touchstart",h);l.addEventListener("touchmove",h);l.addEventListener("touchend",h);l.addEventListener("mousedown",h);l.addEventListener("mouseup",h);l.addEventListener("click",f=>{f.stopPropagation();M(this,"click",a,this.ye(l))});l.addEventListener("dblclick",f=>{f.stopPropagation();M(this,"dblclick",a,this.ye(l))});l.addEventListener("change",()=>J(this,"change",a,this.ye(l)));b.id&&(l.id=b.id);this.fb(l,b);
return l}ve(a){const b=document.createElement("option");b.text=a;return b}ye(a){const b=a.selectedIndex,d=[];for(let k=0,w=a.length;k<w;++k)a.options[k].selected&&d.push(k);return{selectedIndex:b,selectedIndices:d}}fb(a,b){a.title=b.title;a.disabled=!b.isEnabled;a.multiple=!!b.isMultiSelect}zk(a,b){a.selectedIndex=b}Kj(a,b){const d=b.index;b=this.ve(b.text);0>d?a.add(b):a.add(b,d)}tk(a,b){a.remove(b.index)}yk(a,b){a.options[b.index].text=b.text}Pj(a){a.innerHTML=""}Ke(a,b){a.innerHTML="";for(const d of b.items)a.add(this.ve(d));
a.selectedIndex=b.selectedIndex;for(const d of b.selectedIndices)if(b=a.options[d])b.selected=!0}})}"use strict";
{function h(a){a.stopPropagation()}self.wa.za(class extends self.Qc{constructor(a){super(a,"button")}Xb(a,b){const d=document.createElement("input");var k=d;b.isCheckbox?(d.type="checkbox",k=document.createElement("label"),k.appendChild(d),k.appendChild(document.createTextNode("")),k.style.fontFamily="sans-serif",k.style.userSelect="none",k.style.webkitUserSelect="none",k.style.display="inline-block",k.style.color="black"):d.type="button";k.style.position="absolute";k.addEventListener("touchstart",
h);k.addEventListener("touchmove",h);k.addEventListener("touchend",h);k.addEventListener("mousedown",h);k.addEventListener("mouseup",h);k.addEventListener("keydown",h);k.addEventListener("keyup",h);d.addEventListener("click",()=>M(this,"click",a,{isChecked:d.checked}));b.id&&(d.id=b.id);this.fb(k,b);return k}kg(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}xe(a){return this.kg(a)}fb(a,b){const d=this.kg(a);d.checked=b.isChecked;d.disabled=!b.isEnabled;a.title=b.title;a===d?d.value=b.text:
a.lastChild.textContent=b.text}})}"use strict";
{function h(b){b.stopPropagation()}function a(b){13!==b.which&&27!==b.which&&b.stopPropagation()}self.wa.za(class extends self.Qc{constructor(b){super(b,"text-input");K(this,"scroll-to-bottom",d=>this.xk(d))}Xb(b,d){let k;const w=d.type;"textarea"===w?(k=document.createElement("textarea"),k.style.resize="none"):(k=document.createElement("input"),k.type=w);k.style.position="absolute";k.autocomplete="off";k.addEventListener("touchstart",h);k.addEventListener("touchmove",h);k.addEventListener("touchend",
h);k.addEventListener("mousedown",h);k.addEventListener("mouseup",h);k.addEventListener("keydown",a);k.addEventListener("keyup",a);k.addEventListener("click",l=>{l.stopPropagation();M(this,"click",b)});k.addEventListener("dblclick",l=>{l.stopPropagation();M(this,"dblclick",b)});k.addEventListener("input",()=>J(this,"change",b,{text:k.value}));d.id&&(k.id=d.id);this.fb(k,d);return k}fb(b,d){b.value=d.text;b.placeholder=d.placeholder;b.title=d.title;b.disabled=!d.isEnabled;b.readOnly=d.isReadOnly;b.spellcheck=
d.spellCheck;d=d.maxLength;0>d?b.removeAttribute("maxlength"):b.setAttribute("maxlength",d)}xk(b){b.scrollTop=b.scrollHeight}})}"use strict";function Q(h,a,b){R(h,a,URL.createObjectURL(new Blob([b.html],{type:"text/html"})));h.zd=!0}function R(h,a,b){a.src.startsWith("blob:")&&h.zd&&URL.revokeObjectURL(a.src);a.src=b}
self.wa.za(class extends self.Qc{constructor(h){super(h,"iframe");this.zd=!1;K(this,"navigate-url",(a,b)=>{R(this,a,b.url);this.zd=!1});K(this,"display-html",(a,b)=>Q(this,a,b))}Xb(h,a){h=document.createElement("iframe");h.style.position="absolute";h.style.border="none";var b=navigator.userAgent;/iphone|ipad|ipod/i.test(b)&&(b=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(b),b=parseInt(b[b.length-1]),12>=b||isNaN(b))&&(h.setAttribute("noresize","noresize"),h.setAttribute("scrolling","no"));a.isVisible||
(h.style.display="none");a.id&&(h.id=a.id);a.allow&&(h.setAttribute("allow",a.allow),a.allow.includes("fullscreen")&&h.setAttribute("allowfullscreen",""));a.enableSandbox&&h.setAttribute("sandbox",a.sandbox);a.url?h.src=a.url:a.html&&Q(this,h,a);return h}fb(){}Of(h){R(this,h,"");this.zd=!1}});"use strict";
{const h=[],a=2*Math.PI;function b(f){f%=a;0>f&&(f+=a);return f}class d{constructor(f,n,c,e,p,v){this.nc=f;this.oc=n;this.jb=c;this.$=e;this.Rd=p;this.Cg=v}Fb(){return{tag:this.$,interp:this.oc,userData:this.Rd,cvt:this.Cg}}bb(){return this.oc}gi(){return"undefined"!==typeof this.Rd}Kf(f){switch(this.jb){case 0:return f;case 1:return Math.fround(f);case 2:return 2===this.oc&&(f=b(f),f/=Math.PI,f=32767*(f-1)),f|=0,-32768>f?-32768:32767<f?32767:f;case 3:return 2===this.oc&&(f=b(f),f/=a,f*=255),f|=0,
0>f?0:255<f?255:f;default:return f}}dg(f,n,c){switch(this.jb){case 0:f.setFloat64(n,c);n+=8;break;case 1:f.setFloat32(n,c);n+=4;break;case 2:f.setInt16(n,c);n+=2;break;case 3:f.setUint8(n,c);n+=1;break;default:f.setFloat32(n,c),n+=4}return n}Zc(f){if(2!==this.oc)return f;2===this.jb?f=(f/32767+1)*Math.PI:3===this.jb&&(f=f/255*a);return f}static Vc(f,n,c,e,p){switch(f){case 0:return p?c:n;case 1:return n+e*(c-n);case 2:return n===c?f=0:(f=Math.sin(n)*Math.sin(c)+Math.cos(n)*Math.cos(c),f=1<=f?0:-1>=
f?Math.PI:Math.acos(f)),n=0>=Math.cos(c)*Math.sin(n)-Math.sin(c)*Math.cos(n)?b(n+f*e):b(n-f*e);default:return p?c:n}}}class k{constructor(f,n){this.timestamp=f;this.data=n}}class w{constructor(f,n,c){this.ua=f;this.b=f.b;this.H=n;this.U=c;this._data=[];this._data.length=this.ua.ya.length;this.lf=this.Bd=0;this.Hg=this.Pd=!1;this.aa=[];this.L=this.C=this.Ga=null}Fb(){var f=[];for(let c=0,e=this.ua.ya.length;c<e;++c)f.push(this.bb(this.ua.Md,c));f={id:this.H,nid:this.U,isTimedOut:this.li(),interpValues:f,
latestUpdate:null};const n=this.Xh();n&&(f.latestUpdate={timestamp:n.timestamp,data:n.data});return f}Yf(f){this.Hg=!!f}re(f,n){f=f.netValues;var c=this.ua.ya;const e=c.length;this.Pd=!1;for(let p=0;p<e;++p){const v=c[p].Kf(f[p]);this._data[p]!==v&&(this._data[p]=v,this.Bd=n,this.ua.Ki(n))}f=n-this.Bd;n-=this.lf;c=this.ua.yg;(this.Pd=100>f&&0===c?!0:1E3>f&&1>=c?95<=n:495<=n)&&this.ua.hi()}se(f,n,c){const e=this.ua.ya;this.lf=c;f.setUint16(n,this.U);n+=2;for(let p=0,v=this._data.length;p<v;++p)n=e[p].dg(f,
n,this._data[p]);return n}Vd(f,n){for(let c=0,e=this.aa.length;c<e;++c){const p=this.aa[c];if(p.timestamp===f)return;if(p.timestamp>f){this.aa.splice(c,0,new k(f,n));return}}this.aa.push(new k(f,n))}li(){return 0===this.aa.length?!1:this.aa[this.aa.length-1].timestamp<this.ua.Md-3E3}la(){for(;2<this.aa.length&&this.aa[0]!==this.Ga&&this.aa[0]!==this.C&&this.aa[0]!==this.L;)this.aa.shift();const f=this.ua.Md;if(!(this.L&&this.L.timestamp>f&&this.C&&this.C.timestamp<f)){this.L=null;for(let n=0,c=this.aa.length;n<
c;++n){const e=this.aa[n];if(e.timestamp<=f){if(!this.C||e.timestamp>this.C.timestamp)this.Ga=this.C,this.C=e}else{this.L=e;break}}}}Xh(){return 0===this.aa.length?null:this.aa[this.aa.length-1]}bb(f,n){if(!this.L&&!this.C)return 0;if(this.L&&!this.C)return this.L.data[n];const c=this.ua.ya;let e,p,v;if(!this.L&&this.C){if(this.Ga){var x=this.Ga.timestamp;e=this.Ga.data[n];p=this.C.timestamp;v=this.C.data[n];f>this.C.timestamp+this.ua.wd&&(f=this.C.timestamp+this.ua.wd);x=x===p?0:(f-x)/(p-x);return d.Vc(c[n].bb(),
e,v,x,!0)}return this.C.data[n]}x=this.C.timestamp;e=this.C.data[n];p=this.L.timestamp;v=this.L.data[n];x=x===p?0:(f-x)/(p-x);return d.Vc(c[n].bb(),e,v,x,!1)}}class l{constructor(f,n,c,e){this.b=f;this.Jc=n;this.Kc=c;this.U=this.b.ai();this.yg=e;this.Rd={};this.Oa=0;this.wd=250;switch(this.yg){case 1:this.wd=500;break;case 2:this.wd=2500}this.ya=[];this.Ea=[];this.yb=new Map;this.Vb=new Set;this.Bc=this.lf=this.Bd=this.zc=0;this.Kb=!1;this.rd=[];this.Ac=new Map;this.Md=0;this.b.nh(this)}sb(f){this.U=
f}Ki(f){this.Bd=f}hi(){this.Bc++}kl(){this.Kb=!0}$a(f,n,c,e,p){f=new d(this.ya.length,f,n,c,e,p);switch(n){case 0:this.Oa+=8;break;case 1:this.Oa+=4;break;case 2:this.Oa+=2;break;case 3:this.Oa+=1}this.ya.push(f)}Vd(f,n,c){this.Zh(n).Vd(f,c)}la(){this.Md=this.b.Uc();for(const f of this.Ea)f.la()}$h(){const f=[];for(const n of this.ya){const c={tag:n.$,precision:n.jb,interp:n.bb(),clientvaluetag:n.Cg};n.gi()&&(c.userdata=n.Rd);f.push(c)}return f}Mi(f){this.Oa=this.ya.length=0;for(const n of f)this.$a(n.interp,
n.precision,n.tag,n.userdata,n.clientvaluetag)}Zh(f){let n=this.Ac.get(f);if(n)return n;n=new w(this,-1,f);this.Ac.set(f,n);this.Ea.push(n);return n}Yh(f){let n=this.yb.get(f);if(n)return n;n=new w(this,f,this.ph());this.yb.set(f,n);this.Ea.push(n);return n}ph(){do this.zc++,65535<this.zc&&(this.zc=0);while(this.Vb.has(this.zc));const f=this.zc;this.Vb.add(f);return f}ie(f){const n=f.H,c=f.U;this.b.j()&&!this.Kb&&this.rd.push(c);this.yb.delete(n);this.Ac.delete(c);this.Vb.delete(c);f=this.Ea.indexOf(f);
-1<f&&this.Ea.splice(f,1)}Ih(){this.rd.length=0;this.yb.clear();this.Ac.clear();this.Vb.clear();this.Ea.length=0}re(f,n){this.Bc=0;for(var c of this.Ea)c.Yf(!1);for(let e=0,p=f.length;e<p;++e){c=f[e];const v=this.Yh(c.uid);v.Yf(!0);v.re(c,n)}for(const e of this.Ea)e.Hg||h.push(e);for(const e of h)this.ie(e);h.length=0}se(f,n,c){f.setUint16(n,this.U);n+=2;let e=0;this.Kb&&(e=1);f.setUint8(n,e);n+=1;f.setUint16(n,this.Bc);n+=2;f.setUint16(n,this.Oa);n+=2;for(const p of this.Ea)p.Pd&&(n=p.se(f,n,c));
return n}Ci(f,n){if(this.yb.has(f))console.warn("OverrideNid passed id "+f+" which is already in use and cannot be overridden");else if(this.Vb.has(n))console.warn("OverrideNid passed nid "+n+" which is already in use and cannot be overridden");else{var c=new w(this,f,n);this.yb.set(f,c);this.Vb.add(n);this.Ea.push(c);this.Kb=!0}}je(f){(f=this.yb.get(f))&&this.ie(f)}ke(f){(f=this.Ac.get(f))&&this.ie(f)}Fb(){return{hasOverriddenNids:this.Kb,netValues:this.ya.map(f=>f.Fb()),netInstances:this.Ea.map(f=>
f.Fb())}}di(){return{roId:this.Jc,sid:this.Kc,netValues:this.ya.map(f=>f.Fb())}}}self.Jf=d;self.Dh=k;self.Fh=l}"use strict";
{const h=self.Dh,a=self.Jf,b=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection;function d(l){if(l)try{l.close()}catch(f){}}const k=[];class w{constructor(l,f,n){this.b=l;this.H=f;this.U=0;this.ea=n;this.ub=this.J=null;this.pc=!1;this.vb=null;this.rc=!1;this.wb=null;this.$e=this.Mc=this.lc=this.Jb=this.sc=!1;this.vd=this.Dg=this.hf=0;this.Qg=[];this.Ng=this.Mg=0;this.xa=[];this.L=this.C=this.Ga=null;this.Kg=0;this.Se=!1;this.kf=1;this.Cd=
[];this.Tg=this.Dd=0;this.b.fj(this)}sb(l){this.U=l}j(){return this===this.b.P}Wc(){return this===this.b.O}ml(){this.Mg=performance.now()}nl(l){this.Ng=l}dd(l,f){l.binaryType="arraybuffer";l.onopen=()=>{"o"===f?this.pc=!0:"r"===f?this.rc=!0:"u"===f&&(this.sc=!0);this.Jj()};l.onmessage=n=>{this.fk(f,n)};l.onerror=n=>{console.error("Peer '"+this.H+"' datachannel '"+f+"' error: ",n);this.b.Ia(this,n);this.b.j()&&!this.j()&&this.S("network error")};l.onclose=()=>{this.S("disconnect")}}Lf(){if(!this.Wc()){var l=
this.b.j();this.lc=this.Jb=this.sc=this.rc=this.pc=!1;this.Dg=performance.now();this.J=new b({iceServers:this.b.df});this.J.onicecandidate=n=>{n.candidate&&this.b.Ha({message:"icecandidate",toclientid:this.H,icecandidate:n.candidate})};this.J.onsignalingstatechange=()=>{this.J&&"closed"===this.J.signalingState&&this.S("disconnect")};this.J.oniceconnectionstatechange=()=>{this.J&&("failed"!==this.J.iceConnectionState&&"closed"!==this.J.iceConnectionState||this.S("disconnect"))};this.J.onconnectionstatechange=
()=>{if(this.J){var n=this.J.connectionState;"failed"!==n&&"closed"!==n||this.S("disconnect")}};var f=`c2mp_${this.b.Rh()}_${this.b.Sh()}_${this.b.Th()}`;l?(this.U=this.b.Ff(),this.ub=this.J.createDataChannel("o",{ordered:!0,protocol:f}),this.dd(this.ub,"o"),this.vb=this.J.createDataChannel("r",{ordered:!1,protocol:f}),this.dd(this.vb,"r"),this.wb=this.J.createDataChannel("u",{ordered:!1,maxRetransmits:0,protocol:f}),this.dd(this.wb,"u"),this.J.createOffer().then(n=>{this.J.setLocalDescription(n);
this.b.Ha({message:"offer",toclientid:this.H,offer:n})}).catch(n=>{console.error("Host error creating offer for peer '"+this.H+"': ",n);this.b.Ia(this,"could not create offer for peer")})):this.J.ondatachannel=n=>{if(n.channel.protocol!==f)console.error("Unexpected datachannel protocol '"+n.channel.protocol+"', should be '"+f+"'"),this.b.Ia(this,"unexpected datachannel protocol '"+n.channel.protocol+"', should be '"+f+"'");else{var c=n.channel.label;"o"===c?this.ub=n.channel:"r"===c?this.vb=n.channel:
"u"===c?this.wb=n.channel:(console.error("Unknown datachannel label: "+n.channel.label),this.b.Ia(this,"unknown datachannel label '"+n.channel.label+"'"));this.dd(n.channel,c)}}}}async ej(l){if(this.J)try{await this.J.addIceCandidate(l)}catch(f){console.warn("[Multiplayer] Error adding ICE candidate: ",f)}}fi(){return!!this.J}Jj(){!this.Jb&&this.rc&&this.sc&&this.pc&&(this.jk(),this.Jb=!0,this.lc=!1)}jk(){this.hf=performance.now();if(this.b.j()){this.b.$b("o",JSON.stringify({c:"j",i:this.H,n:this.U,
a:this.ea}),this);this.cb("o",JSON.stringify({c:"hi",hn:this.b.P.U,n:this.U,d:this.b.Ca,u:this.b.Dc,objs:this.b.ci(),cvs:this.b.Qh()}));for(const l of this.b.Ka)!l.j()&&l!==this&&l.fe()&&this.cb("o",JSON.stringify({c:"j",i:l.H,n:l.U,a:l.ea}))}else this.$e=!0,this.j()&&this.me(performance.now(),!0);this.b.qg(this)}Ij(l){!this.lc&&this.Jb&&(this.Fe(l),this.lc=!0,this.Jb=!1)}Fe(l){this.b.j()&&!this.Wc()&&this.b.$b("o",JSON.stringify({c:"l",i:this.H,a:this.ea,r:l}),this);this.Wc()||this.b.pg(this,l)}fe(){return this.Jb&&
!this.lc}cb(l,f){this.b.aj();var n=0;f.length?n=f.length:f.byteLength&&(n=f.byteLength);this.b.Zi(n);n=this.b.wf;const c=this.b.vf,e=this.b.xf;if(!(0<n&&"u"===l&&Math.random()<n))if(0===c&&0===e)this.hg(l,f);else{let p=1;"u"!==l&&Math.random()<n&&(p=3);setTimeout(()=>this.hg(l,f),c*p+Math.random()*e*p)}}hg(l,f){try{"o"===l?this.pc&&this.ub&&this.ub.send(f):"r"===l?this.rc&&this.vb&&this.vb.send(f):"u"===l&&this.sc&&this.wb&&this.wb.send(f)}catch(n){this.Mc||(this.b.j()?"o"===l||"r"===l?("string"===
typeof f?(console.error("Error sending "+f.length+"-char string on '"+l+"' to '"+this.ea+"', host kicking: ",n),console.log("String that failed to send from previous error was: "+f)):console.error("Error sending "+(f.length||f.byteLength)+"-byte binary on '"+l+"' to '"+this.ea+"', host kicking: ",n),this.S("network error")):(this.vd++,10<=this.vd&&("string"===typeof f?(console.error("Too many errors ("+this.vd+") sending data on '"+l+"' to '"+this.ea+"', kicking; last error was for sending "+f.length+
"-char string: ",n),console.log("String that failed to send from previous error was: "+f)):console.error("Too many errors ("+this.vd+") sending data on '"+l+"' to '"+this.ea+"', kicking; last error was for sending "+(f.length||f.byteLength)+"-byte binary: ",n),this.S("network error"))):console.error("Error sending data on '"+l+"': ",n))}}me(l,f){this.Mc||(!f&&!this.fe()&&this.J&&25E3<l-this.Dg?(console.warn("Timed out '"+this.ea+"', could not establish connection after 25sec"),this.S("timeout")):
!f&&this.fe()&&2E4<l-this.hf?(console.warn("Timed out '"+this.ea+"', not heard from for 20sec"),this.S("timeout")):(this.Kg=l,this.Se=!0,this.kf++,this.cb("u","ping:"+this.kf)))}Gi(l){l="pong:"+l.substr(5);this.b.j()&&(l=l+"/"+Math.round(performance.now()).toString());this.cb("u",l)}pk(l){if(this.Se){var f=l.indexOf(":");if(-1<f){if(parseFloat(l.substr(f+1))===this.kf){f=performance.now();this.Se=!1;var n=(f-this.Kg)/2;this.Cd.push(n);10<this.Cd.length&&this.Cd.shift();k.push(...this.Cd);k.sort((v,
x)=>v-x);this.Tg=k[k.length-1]-k[0];var c=0,e=k.length;4<=k.length&&6>=k.length?(++c,--e):6<k.length&&(c+=2,e-=2);var p=0;for(let v=c;v<e;++v)p+=k[v];this.Dd=p/(e-c);k.length=0;this.b.j()||(c=l.indexOf("/"),-1<c?(l=parseFloat(l.substr(c+1)),isFinite(l)?this.b.mh(l,f,n,this.Dd):console.warn("Invalid host time from pong response")):console.warn("Cannot parse off host time from pong response"))}}else console.warn("Cannot parse off ping ID from pong")}}fk(l,f){const n=this.b.wf,c=this.b.vf,e=this.b.xf;
if(!(0<n&&"u"===l&&Math.random()<n))if(0===c&&0===e)this.gg(l,f);else{let p=1;"u"!==l&&Math.random()<n&&(p=3);setTimeout(()=>this.gg(l,f),c*p+Math.random()*e*p)}}gg(l,f){if(!this.Mc){this.hf=performance.now();this.b.$i();var n=0;f.data.length?n=f.data.length:f.data.byteLength&&(n=f.data.byteLength);this.b.Yi(n);if("string"===typeof f.data){if(!(""===f.data.trim()||4>f.data.length))if(l=f.data.substr(0,4),"ping"===l)this.Gi(f.data);else if("pong"===l)this.pk(f.data);else{try{var c=JSON.parse(f.data)}catch(e){this.b.Ia(this,
e);this.b.j()?(console.error("Error parsing message as JSON for peer '"+this.H+"', host kicking: ",e),this.S("data error")):console.error("Error parsing message as JSON for peer '"+this.H+"': ",e);console.log("String that failed to parse from previous error: "+f.data);return}if(c)try{c.c&&"m"!==c.c?this.Qj(c):this.b.lk(this,c)}catch(e){this.b.Ia(this,e),this.b.j()?(console.error("Error handling message for peer '"+this.H+"', host kicking: ",e),this.S("data error")):console.error("Error handling message for peer '"+
this.H+"': ",e)}}}else{!this.$e&&this.b.j()&&"u"===l&&(this.$e=!0,this.b.Si(this.H));try{this.Oj(f.data)}catch(e){this.b.Ia(this,e),this.b.j()?(console.error("Error handling binary update for peer '"+this.H+"', host kicking: ",e),this.S("data error")):console.error("Error handling binary update for peer '"+this.H+"': ",e)}}}}Qj(l){switch(l.c){case "disconnect":l.k&&A(this.b,"peer-kicked");var f=!this.b.j()&&!this.j();this.S(l.r);f&&this.b.pe();break;case "hi":this.b.j()||(this.b.P.sb(l.hn),this.b.O.sb(l.n),
this.b.Ji(l.d),this.b.Oi(l.u),this.b.si(l.objs),this.b.ri(l.cvs));break;case "j":this.b.j()||(f=new w(this.b,l.i,l.a),f.sb(l.n),this.b.qg(f));break;case "l":!this.b.j()&&(f=this.b.Tc(l.i))&&(f.Wc()||this.b.pg(f,l.r),f.S(l.r));break;default:console.error("Unknown control message from peer '"+this.H+"': "+l.c),this.b.Ia(this,"unknown control message '"+l.c+"'")}}Oj(l){this.b.j()?this.ck(l):this.mk(l)}ck(l){l=new DataView(l);let f=0;var n=l.getUint32(f);f+=4;if(1664249200!==n)console.warn("Rejected packet with incorrect magic number (received '"+
n+"', expected '1664249200'");else if(n=l.getFloat64(f),f+=8,n+=this.Dd,!(3E3<=Math.abs(n-performance.now()))){l.getUint8(f);f+=1;var c=l.getUint8(f);f+=1;var e=[],p=this.b.Ja;for(let x=0;x<c;++x)if(x>=p.length)e.push(0);else{var v=p[x];switch(v.jb){case 0:v=l.getFloat64(f);f+=8;break;case 1:v=l.getFloat32(f);f+=4;break;case 2:v=v.Zc(l.getInt16(f));f+=2;break;case 3:v=v.Zc(l.getUint8(f));f+=1;break;default:v=l.getFloat32(f),f+=4}e.push(v)}this.dj(n,e)}}dj(l,f){for(let n=0,c=this.xa.length;n<c;++n){const e=
this.xa[n];if(e.timestamp===l)return;if(e.timestamp>l){this.xa.splice(n,0,new h(l,f));return}}this.xa.push(new h(l,f))}la(l){if(0!==this.xa.length){for(;2<this.xa.length&&this.xa[0]!==this.Ga&&this.xa[0]!==this.C&&this.xa[0]!==this.L;)this.xa.shift();if(!(this.L&&this.L.timestamp>l&&this.C&&this.C.timestamp<l)){this.L=null;for(let f=0,n=this.xa.length;f<n;++f){const c=this.xa[f];if(c.timestamp<=l){if(!this.C||c.timestamp>this.C.timestamp)this.Ga=this.C,this.C=c}else{this.L=c;break}}}}}mk(l){l=new DataView(l);
let f=0;var n=l.getUint32(f);f+=4;1664249200!==n?console.warn("Rejected packet with incorrect magic number (received '"+n+"', expected '1664249200'"):(n=l.getUint32(f),f+=4,0===n?this.Dj(l,f):1===n?this.Cj(l,f):console.warn("Ignoring packet with incorrect flags (received "+n+", expected 0 or 1"))}Dj(l,f){const n=l.getFloat64(f);f+=8;const c=l.getUint16(f);f+=2;for(let x=0;x<c;++x){var e=l.getUint16(f);f+=2;var p=l.getUint8(f);f+=1;let z=null,q=0;const r=this.b.Rf(e);r?(z=r.ya,q=z.length,1===p&&r.kl()):
console.warn("Don't know which object corresponds to NID "+e);e=l.getUint16(f);f+=2;p=l.getUint16(f);f+=2;for(let g=0;g<e;++g){const m=l.getUint16(f);f+=2;if(r){const u=[];let t=f;for(let y=0;y<q;++y){var v=z[y];switch(v.jb){case 0:v=l.getFloat64(t);t+=8;break;case 1:v=l.getFloat32(t);t+=4;break;case 2:v=v.Zc(l.getInt16(t));t+=2;break;case 3:v=v.Zc(l.getUint8(t));t+=1;break;default:v=l.getFloat32(t),t+=4}u.push(v)}r.Vd(n,m,u)}f+=p}}}Cj(l,f){const n=l.getFloat64(f);f+=8;const c=l.getUint16(f);f+=2;
for(let p=0;p<c;++p){var e=l.getUint16(f);f+=2;const v=this.b.Rf(e);v||console.warn("Don't know which object corresponds to NID "+e);e=l.getUint16(f);f+=2;for(let x=0;x<e;++x){const z=l.getUint16(f);f+=2;v&&!v.Kb&&(this.b.dk(v,z,n),v.ke(z))}}}S(l,f){this.Mc||(this.Mc=!0,this.Ij(l),this.cb("o",JSON.stringify({c:"disconnect",r:l,k:!!f})),d(this.ub),d(this.vb),d(this.wb),d(this.J),this.J=this.wb=this.vb=this.ub=null,this.sc=this.rc=this.pc=!1,this.b.Zk(this))}Wh(l){l=l.nc;if(!this.L&&!this.C)return 0;
if(this.L&&!this.C){var f=this.L.data;return 0>l||l>=f.length?0:f[l]}var n=this.b.Uc();let c,e;if(!this.L&&this.C){if(this.Ga){var p=this.Ga.timestamp;f=this.Ga.data[l];c=this.C.timestamp;e=this.C.data[l];n>this.C.timestamp+250&&(n=this.C.timestamp+250);p=p===c?0:(n-p)/(c-p);return a.Vc(this.b.Ja[l].bb(),f,e,p,!0)}f=this.C.data;return 0>l||l>=f.length?0:f[l]}p=this.C.timestamp;f=this.C.data[l];c=this.L.timestamp;e=this.L.data[l];p=p===c?0:(n-p)/(c-p);return a.Vc(this.b.Ja[l].bb(),f,e,p,!1)}}self.Eh=
w}"use strict";
{const h=self.Jf,a=self.Eh,b=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection,d=window.RTCSessionDescription||window.webkitRTCSessionDescription||window.mozRTCSessionDescription||window.msRTCSessionDescription,k=window.RTCIceCandidate||window.webkitRTCIceCandidate||window.mozRTCIceCandidate||window.msRTCIceCandidate,w=window.RTCDataChannel||window.webkitRTCDataChannel||window.mozRTCDataChannel||window.msRTCDataChannel,l=[{urls:"stun:stun.l.google.com:19302"}];
let f=!1;const n=[];self.wa.za(class extends self.ab{constructor(c){super(c,"multiplayer");this.df=[];this.V=null;this.ta=this.Pa=!1;this.Nl={jh:0,version:0,name:"",fh:"",eh:""};this.ma=this.Ye=this.Xe=this.qf=this.rf="";this.Ka=[];this.Wa=new Map;this.Ob=0;this.Qd=new Set;this.P=this.O=null;this.Ca=80;this.Dc=this.cf=30;this.Pg=0;this.Cb={Pc:0,hh:0,Cf:0,gh:0,Ud:0,dh:0,Bf:0,bh:0,Td:0};this.qd=new ArrayBuffer(262144);this.Ve=new DataView(this.qd);this.Ba=[];this.Kl=1;this.Gc=new Map;this.Hc=new Map;
this.wf=this.xf=this.vf=0;this.zb=[];this.da=this.Qa=0;this.na=this.Ya=this.Ca;this.Ja=[];this.pd=new Map;this.uf=!1;this.De(l);setInterval(()=>this.rj(),2E3);window.addEventListener("unload",()=>this.cc("quit"));E(this,"get-supported",()=>this.Zj());E(this,"add-ice-servers",e=>this.De(e.list));E(this,"simulate-latency",e=>this.Li(e.latency,e.pdv,e.loss));E(this,"set-bandwidth-profile",e=>this.Ii(e.updateRate,e.delay));E(this,"tick",e=>this.la(e));E(this,"alert",e=>this.oh(e));E(this,"signalling-connect",
e=>this.Ti(e.url));E(this,"signalling-disconnect",()=>this.cg());E(this,"signalling-login",e=>this.Vi(e.alias));E(this,"signalling-join-room",e=>this.Ui(e.game,e.instance,e.room,e.maxClients));E(this,"signalling-auto-join-room",e=>this.Ri(e.game,e.instance,e.room,e.maxClients,e.lock));E(this,"signalling-leave-room",()=>this.pe());E(this,"signalling-list-game-instances",e=>this.Wi(e.game));E(this,"signalling-list-rooms",e=>this.Xi(e.game,e.instance,e.which));E(this,"disconnect-room",()=>this.Pf(!0));
E(this,"peer-send-message",e=>this.xi(e));E(this,"host-broadcast",e=>this.vi(e));E(this,"kick-peer",e=>this.wi(e));E(this,"sync-object",e=>this.Bi(e));E(this,"sync-inst-var",e=>this.Ai(e));E(this,"associate-object",e=>this.ti(e));E(this,"remove-object-id",e=>this.je(e.uid));E(this,"remove-net-insts",e=>this.yi(e));E(this,"remove-object-nid",e=>this.zi(e));E(this,"set-client-state",e=>this.Zf(e.tag,e.value));E(this,"add-client-input-value",e=>this.kh(e.tag,e.precision,e.interp))}xj(c){return c?"string"===
typeof c?c:"string"===typeof c.message?c.message:"string"===typeof c.details?c.details:"string"===typeof c.data?c.data:"string"===typeof c.type?c.type:"unknown error":"unknown error"}ee(){return this.Pa&&this.ta}ac(){return this.ee()&&this.ma}j(){return this.ac()&&this.O&&this.P===this.O}Rh(){return this.ee()?this.Xe:""}Sh(){return this.ee()?this.Ye:""}Th(){return this.ac()?this.ma:""}Li(c,e,p){this.vf=Math.max(c,0);this.xf=Math.max(e,0);this.wf=Math.max(p,0)}Zj(){return{isSupported:!(!b||!w)}}Ti(c){if(!this.V&&
!this.Pa){try{this.V=new WebSocket(c,"c2multiplayer")}catch(e){this.V=null;this.rb(e);return}this.V.onopen=()=>{-1===this.V.protocol.indexOf("c2multiplayer")?(this.rb("server does not support 'c2multiplayer' protocol"),this.V.close(1002,"'c2multiplayer' protocol required"),this.V=null,this.Pa=!1):this.Pa=!0};this.V.onclose=()=>{this.Bk();this.ta=this.Pa=!1;this.V=null};this.V.onerror=e=>{console.error("Signalling server error: ",e);this.rb(e)};this.V.onmessage=e=>{this.Ck(e)}}}cg(){this.V&&this.Pa&&
(this.V.close(),this.V=null,this.Pa=!1)}Ck(c){let e;try{e=JSON.parse(c.data)}catch(p){this.rb(p);return}switch(e.message){case "welcome":this.Ok(e);break;case "login-ok":this.Jk(e);break;case "join-ok":this.Gk(e);break;case "leave-ok":this.Ik();break;case "kicked":this.Hk();break;case "peer-joined":this.Lk(e);break;case "peer-quit":this.Mk(e);break;case "icecandidate":this.Ek(e);break;case "offer":this.Kk(e);break;case "answer":this.Dk(e);break;case "instance-list":this.Fk(e);break;case "room-list":this.Nk(e);
break;case "error":this.rb(e.details);break;default:this.rb("received unknown signalling message")}}ei(c){for(const e of this.df)if(e.urls===c.urls)return!0;return!1}De(c){if(c)for(let e of c)"string"===typeof e&&(e={urls:e}),this.ei(e)||(e.hasOwnProperty("url")||(e.url=e.urls),this.df.push(e))}rb(c){A(this,"signalling-error",{message:this.xj(c)})}Bk(){A(this,"signalling-close")}Ok(c){if(1>c.protocolrev||1<c.protocolrev)this.rb("signalling server protocol revision not supported"),this.cg();else{this.rf=
c.clientid;var e=this.Nl;e.jh=c.protocolrev;e.version=c.version;e.name=c.name;e.fh=c.operator;e.eh=c.motd;this.De(c.ice_servers);A(this,"signalling-welcome",{myid:this.rf,sigservinfo:{protocolrev:e.jh,version:e.version,name:e.name,operator:e.fh,motd:e.eh}})}}Jk(c){this.qf=c.alias;this.ta=!0;A(this,"signalling-login-ok",{myalias:this.qf})}ai(){return this.Kl++}Ff(){if(this.j()){do this.Ob++,65535<this.Ob&&(this.Ob=0);while(this.Qd.has(this.Ob));var c=this.Ob;this.Qd.add(c);return c}}Oh(c){this.j()&&
this.Qd.delete(c)}Gk(c){this.cc("disconnect");this.Xe=c.game;this.Ye=c.instance;this.ma=c.room;this.O=new a(this,this.rf,this.qf);c.host?(this.P=this.O,this.Ob=0,this.Qd.clear(),this.P.sb(this.Ff())):(this.da=this.Qa=this.zb.length=0,this.Ca=80,this.Dc=this.cf=30,this.na=this.Ya=this.Ca,this.P=new a(this,c.hostid,c.hostalias),this.P.Lf());A(this,"signalling-join-ok",{isHost:!!c.host,hostId:this.P.H,hostAlias:this.P.ea,game:this.Xe,gameInstance:this.Ye,room:this.ma})}Ik(){this.ma="";A(this,"signalling-leave-ok")}Hk(){this.Pf();
this.ma="";A(this,"signalling-kicked")}Lk(c){if(this.ta&&this.ma&&this.j()){var e=this.Wa.get(c.peerid);e&&e.S("rejoin");(new a(this,c.peerid,c.peeralias)).Lf()}}Mk(c){if(this.ta&&this.ma&&this.j()){var e=this.Wa.get(c.id);e&&e.S(c.reason)}}Ek(c){if(this.ta&&this.ma){var e=this.Wa.get(c.from);e&&e.ej(new k(c.icecandidate))}}Kk(c){if(this.ta&&this.ma&&!this.j()&&this.O&&this.P&&this.P.fi()&&c.from===this.P.H){var e=this.P.J;e.setRemoteDescription(new d(c.offer)).then(()=>{e.createAnswer().then(p=>
{e.setLocalDescription(p);this.Ha({message:"answer",toclientid:this.P.H,answer:p})}).catch(p=>{console.error("Peer error creating answer: ",p);this.Ia(this.O,"could not create answer to host offer")})}).catch(p=>{console.error("Peer error setting remote description: ",p);this.Ia(this.O,"could not set remote description")})}}Dk(c){if(this.ta&&this.ma&&this.j()){var e=this.Wa.get(c.from);e&&e.J.setRemoteDescription(new d(c.answer)).catch(p=>{console.error("Host error setting remote description: ",p)})}}Fk(c){A(this,
"signalling-instance-list",{list:c.list})}Nk(c){A(this,"signalling-room-list",{list:c.list})}Ha(c){this.V&&this.Pa&&this.V.send(JSON.stringify(c))}Vi(c){this.ta||this.Ha({message:"login",protocolrev:1,alias:c})}Ui(c,e,p,v){this.ta&&!this.ma&&this.Ha({message:"join",game:c,instance:e,room:p,max_clients:v})}Ri(c,e,p,v,x){this.ta&&!this.ma&&this.Ha({message:"auto-join",game:c,instance:e,room:p,max_clients:v,lock_when_full:x})}pe(){this.ta&&this.Ha({message:"leave"})}Si(c){this.ta&&this.j()&&this.Ha({message:"confirm-peer",
id:c})}Wi(c){this.V&&this.Pa&&this.Ha({message:"list-instances",game:c})}Xi(c,e,p){this.V&&this.Pa&&this.Ha({message:"list-rooms",game:c,instance:e,which:p})}Pf(c){this.da=this.Qa=this.zb.length=0;this.cc("disconnect");for(const e of this.Ba)e.Ih();c&&this.pe()}fj(c){this.Ka.push(c);this.Wa.set(c.H,c);A(this,"add-peer",{id:c.H,alias:c.ea})}Zk(c){A(this,"remove-peer",{id:c.H});this.j()&&this.Oh(c.U);const e=this.Ka.indexOf(c);-1<e&&this.Ka.splice(e,1);this.Wa.delete(c.H);this.P===c&&(this.P=null,this.cc("host quit"));
this.O===c&&(this.O=null,this.ma="",this.cc("disconnect"))}cc(c){if(!f){for(f=!0;this.Ka.length;)this.Ka[0].S(c);f=!1}}Tc(c){return this.Wa.get(c)||null}Ph(c){return(c=this.Wa.get(c))?c.ea:""}vi(c){const e=c.fromId,p=c.tag,v=c.message;c=c.mode;const x=this.Tc(e);this.$b(c,JSON.stringify({c:"m",t:p,f:e,m:v}),x)}$b(c,e,p){if(this.j()){var v=this.Ka.slice(0);for(const x of v)x&&x!==this.O&&x!==p&&x.cb(c,e)}}rj(){const c=performance.now();if(this.j()){n.push(...this.Ka);for(const e of n)e&&e!==this.O&&
e.me(c,!1);n.length=0}else this.P&&this.P.me(c,!1)}nh(c){this.Ba.push(c);this.Hc.set(c.Jc,c);this.Gc.set(c.U,c)}ci(){const c={};for(const [e,p]of this.Gc.entries())c[p.Kc]={nid:e,nvs:p.$h()};return c}si(c){this.Gc.clear();for(const e of this.Ba)if(c.hasOwnProperty(e.Kc.toString())){const p=c[e.Kc.toString()];e.sb(p.nid);this.Gc.set(p.nid,e);e.Mi(p.nvs)}else console.warn("Could not map object SID '"+e.Kc+"' - host did not send NID for it"),e.sb(-1)}Rf(c){return this.Gc.get(c)||null}la(c){if(!this.ac())return null;
c=c.dt;const e=performance.now();e-this.Pg>=1E3/(this.j()?this.cf:this.Dc)-5&&(this.Hi(e),this.Pg=e);const p=this.Cb;1E3<=e-p.Pc&&(p.hh=p.Cf,p.gh=p.Ud,p.dh=p.Bf,p.bh=p.Td,p.Cf=0,p.Ud=0,p.Bf=0,p.Td=0,p.Pc+=1E3,500<e-p.Pc&&(p.Pc=e),A(this,"stats",{stats:{outboundPerSec:p.hh,outboundBandwidthPerSec:p.gh,inboundPerSec:p.dh,inboundBandwidthPerSec:p.bh}}));this.j()||(this.da<this.Qa?(this.da+=10*c,this.da>this.Qa&&(this.da=this.Qa)):this.da>this.Qa&&(this.da-=10*c,this.da<this.Qa&&(this.da=this.Qa)),this.na<
this.Ya?(this.na+=30*c,this.na>this.Ya&&(this.na=this.Ya)):this.na>this.Ya&&(this.na-=30*c,this.na<this.Ya&&(this.na=this.Ya)));c=this.Uc();for(const v of this.Ka)v.la(c);for(const v of this.Ba)v.la();return{simulationTime:this.Uc(),hostInputArrivalTime:this.Vh(),clientDelay:this.Ca,peerData:this.zj(),roData:this.Aj(),isReadyForInput:this.Tf()}}zj(){const c={};for(const e of this.Ka){const p={};for(const v of this.Ja)p[v.$]=e.Wh(v);c[e.H]={nid:e.U,latency:e.Dd,pdv:e.Tg,clientState:p}}return c}Aj(){const c=
{};for(const e of this.Ba)c[e.Jc]=e.Fb();return c}async Hi(c){this.j()?(await this.fl(c),this.el(c)):await this.dl(c)}async Mj(){const c=await B(this,"before-client-update");for(const e of c.clientStateUpdates)this.Zf(e.tag,e.value)}async dl(c){this.Tf()&&await this.Mj();if(this.O&&this.uf){var e=this.Ve,p=0,v=this.Ja,x=this.O.Qg,z=c-this.O.Mg,q=c-this.O.Ng;if(100>z||(1E3>z?95<=q:495<=q)){e.setUint32(p,1664249200);p+=4;e.setFloat64(p,c+this.da);p+=8;e.setUint8(p,0);p+=1;e.setUint8(p,v.length);p+=
1;for(let r=0,g=v.length;r<g;++r)z=v[r],q=0,r<x.length&&(q=z.Kf(x[r])),p=z.dg(e,p,q);this.O.nl(c);this.P.cb("u",new Uint8Array(this.qd,0,p))}}}async fl(c){const e=this.Ve;let p=0,v=0;const x=await B(this,"get-object-info",{ros:this.Ba.map(z=>z.di())});for(const z of this.Ba){const q=z.Jc;x.hasOwnProperty(q)&&(z.re(x[q],c),0<z.Bc&&v++)}if(0!==v){e.setUint32(p,1664249200);p+=4;e.setUint32(p,0);p+=4;e.setFloat64(p,c);p+=8;e.setUint16(p,v);p+=2;for(const z of this.Ba)0<z.Bc&&(p=z.se(e,p,c));this.$b("u",
new Uint8Array(this.qd,0,p),null)}}el(c){const e=this.Ve;let p=0,v=0;for(const x of this.Ba)x.rd.length&&v++;if(0!==v){e.setUint32(p,1664249200);p+=4;e.setUint32(p,1);p+=4;e.setFloat64(p,c);p+=8;e.setUint16(p,v);p+=2;for(const x of this.Ba)if(c=x.rd,c.length){e.setUint16(p,x.U);p+=2;e.setUint16(p,c.length);p+=2;for(const z of c)e.setUint16(p,z),p+=2;c.length=0}this.$b("r",new Uint8Array(this.qd,0,p),null)}}mh(c,e,p,v){if(!this.j()){this.Ya=v+this.Ca;c=c+p-e;0===this.zb.length&&(this.da=c,this.na=
this.Ya);this.zb.push(c);30<this.zb.length&&this.zb.shift();n.push(...this.zb);n.sort((x,z)=>x-z);c=0;e=n.length;4<=n.length&&6>=n.length?(++c,--e):6<n.length&&19>=n.length?(c+=2,e-=2):19<n.length&&(c+=5,e-=5);p=0;for(v=c;v<e;++v)p+=n[v];this.Qa=p/(e-c);n.length=0}}Uc(){return this.j()?performance.now()-this.Ca:performance.now()+this.da-this.na}Vh(){return this.j()?performance.now():performance.now()+this.da+this.na}Zf(c,e){if(!this.j()&&this.O&&this.uf&&(c=this.pd.get(c))){c=c.nc;var p=this.O.Qg;
p.length<c+1&&(p.length=c+1);p[c]!==e&&(p[c]=e,this.O.ml())}}kh(c,e,p){e=new h(this.Ja.length,p,e,c,null);this.pd.set(c,e);this.Ja.push(e)}Qh(){const c=[];for(const e of this.Ja)c.push({tag:e.$,precision:e.jb,interp:e.bb()});return c}ri(c){this.pd.clear();this.Ja.length=0;for(let p=0,v=c.length;p<v;++p){var e=c[p];e=new h(p,e.interp,e.precision,e.tag,null);this.pd.set(e.$,e);this.Ja.push(e)}this.uf=!0}je(c){for(const e of this.Ba)e.je(c)}Tf(){return this.ac()?this.j()?!0:0!==this.Qa:!1}Ii(c,e){this.ac()||
(this.Dc=this.cf=c,this.Ca=e)}qg(c){A(this,"peer-open",{id:c.H,alias:c.ea})}xi(c){const e=c.tag,p=c.message,v=c.mode;(c=this.Tc(c.id))&&c.cb(v,JSON.stringify({c:"m",t:e,m:p}))}pg(c,e){A(this,"peer-close",{id:c.H,alias:c.ea,reason:e||"unknown"})}Ia(c,e){console.error(`[Multiplayer] Peer '${c.ea}' (${c.H}) error: `,e)}lk(c,e){c=e.f||c.H;A(this,"peer-message",{tag:e.t,fromId:c,fromAlias:this.Ph(c),content:e.m})}dk(c,e,p){A(this,"instance-destroyed",{roId:c.Jc,nid:e,timestamp:p})}wi(c){if(this.j()){var e=
c.reason;(c=this.Tc(c.id))&&c.S(e,!0)}}aj(){this.Cb.Cf++}Zi(c){this.Cb.Ud+=c}$i(){this.Cb.Bf++}Yi(c){this.Cb.Td+=c}Ji(c){this.Ca=c}Oi(c){this.Dc=c}Bi(c){const e=c.data,p=c.precision,v=c.bandwidth;for(const x of c.objectClasses)c=new self.Fh(this,x.roId,x.sid,v),1===e?(c.$a(1,p,"x"),c.$a(1,p,"y")):2===e?c.$a(2,p,"a"):3===e&&(c.$a(1,p,"x"),c.$a(1,p,"y"),c.$a(2,p,"a"))}oh(c){alert(c.message)}Ai(c){const e=c.precision,p=c.interp,v=c.cvt;for(const x of c.syncData)this.Hc.get(x.roId).$a(p,e,"iv",x.varIndex,
v)}ti(c){var e=c.peerId;const p=c.instUid;c=this.Hc.get(c.roId);e=this.Wa.get(e);c&&e&&this.j()&&c.Ci(p,e.U)}yi(c){for(const [e,p]of Object.entries(c))if(c=this.Hc.get(parseInt(e,10)))for(const v of p)c.ke(v)}zi(c){const e=c.nid;(c=this.Hc.get(c.roId))&&c.ke(e)}})}"use strict";
async function S(h){if(!h.Bb)try{h.Bb=await navigator.wakeLock.request("screen"),h.Bb.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");h.Bb=null;A(h,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),A(h,"wake-lock-acquired")}catch(a){console.warn("[Construct 3] Failed to acquire screen wake lock: ",a),A(h,"wake-lock-error")}}
function T(){var h=document.body;const a=h.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");h=getComputedStyle(h);h=[h.getPropertyValue("--temp-sai-top"),h.getPropertyValue("--temp-sai-right"),h.getPropertyValue("--temp-sai-bottom"),h.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);
return isFinite(b)?b:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return h}
self.wa.za(class extends self.ab{constructor(h){super(h,"platform-info");F(this,[["get-initial-state",()=>this.Je()],["request-wake-lock",()=>S(this)],["release-wake-lock",()=>{this.Bb&&(this.Bb.release(),this.Bb=null)}]]);window.addEventListener("resize",()=>{A(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:T()})});this.Bb=null}Je(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:T(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";
{const h=180/Math.PI;self.Ra=class extends self.ab{constructor(a){super(a,"audio");this.td=this.o=null;this.xd=this.bf=!1;this.kb=()=>this.Bl();this.Ma=[];this.W=[];this.Ua=null;this.Lg="";this.Og=-1;this.Ec=new Map;this.mf=1;this.gb=!1;this.zf=0;this.Od=1;this.Ze=0;this.Sg="HRTF";this.Eg="inverse";this.Ug=600;this.Rg=1E4;this.Wg=1;this.Gg=this.tf=!1;this.Ol=this.M.ji();this.Na=new Map;this.Ib=new Set;this.ff=!1;this.nf="";this.Ab=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.hk(b,d);this.sd=null;
self.C3Audio_GetOutputStream=()=>this.Yj();self.C3Audio_DOMInterface=this;F(this,[["create-audio-context",b=>this.oj(b)],["play",b=>this.Vk(b)],["stop",b=>this.yl(b)],["stop-all",()=>this.zl()],["set-paused",b=>this.rl(b)],["set-volume",b=>this.wl(b)],["fade-volume",b=>this.uj(b)],["set-master-volume",b=>this.pl(b)],["set-muted",b=>this.ql(b)],["set-silent",b=>this.tl(b)],["set-looping",b=>this.ol(b)],["set-playback-rate",b=>this.sl(b)],["seek",b=>this.cl(b)],["preload",b=>this.Wk(b)],["unload",b=>
this.Cl(b)],["unload-all",()=>this.Dl()],["set-suspended",b=>this.ul(b)],["add-effect",b=>this.eg(b)],["set-effect-param",b=>this.il(b)],["remove-effects",b=>this.Yk(b)],["tick",b=>this.Rk(b)],["load-state",b=>this.Ke(b)]])}async oj(a){a.isiOSCordova&&(this.tf=!0);this.zf=a.timeScaleMode;this.Sg=["equalpower","HRTF","soundfield"][a.panningModel];this.Eg=["linear","inverse","exponential"][a.distanceModel];this.Ug=a.refDistance;this.Rg=a.maxDistance;this.Wg=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.o=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.o=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.fg();this.o.onstatechange=()=>{"running"!==this.o.state&&this.fg()};this.td=this.o.createGain();this.td.connect(this.o.destination);b=a.listenerPos;this.o.listener.setPosition(b[0],b[1],b[2]);this.o.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.Zd();try{await Promise.all(a.preloadList.map(d=>
this.ed(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.o.sampleRate}}fg(){this.xd||(this.bf=!1,window.addEventListener("pointerup",this.kb,!0),window.addEventListener("touchend",this.kb,!0),window.addEventListener("click",this.kb,!0),window.addEventListener("keydown",this.kb,!0),this.xd=!0)}qj(){this.xd&&(this.bf=!0,window.removeEventListener("pointerup",this.kb,!0),window.removeEventListener("touchend",this.kb,!0),window.removeEventListener("click",
this.kb,!0),window.removeEventListener("keydown",this.kb,!0),this.xd=!1)}Bl(){if(!this.bf){var a=this.o;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.qj()}}va(){return this.o}Zd(){return this.o.currentTime}mb(){return this.td}Qf(a){return(a=this.Na.get(a.toLowerCase()))?a[0].ka():this.mb()}lh(a,b){a=a.toLowerCase();let d=this.Na.get(a);d||(d=[],this.Na.set(a,d));b.ll(d.length);
b.vl(a);d.push(b);this.ug(a)}ug(a){let b=this.mb();const d=this.Na.get(a);if(d&&d.length){b=d[0].ka();for(let k=0,w=d.length;k<w;++k){const l=d[k];k+1===w?l.pa(this.mb()):l.pa(d[k+1].ka())}}for(const k of this.Za(a))k.Ei(b);this.Ab&&this.nf===a&&(this.Ab.disconnect(),this.Ab.connect(b))}Sc(){return this.mf}Xc(){return this.gb}jl(){this.Gg=!0}Lh(a,b){return b?this.M.El(a).then(d=>{const k=this.o.createBuffer(1,d.length,48E3);k.getChannelData(0).set(d);return k}):new Promise((d,k)=>{this.o.decodeAudioData(a,
d,k)})}ob(a){this.M.ob(a)}Gb(a){this.M.Gb(a)}Xf(a){let b=0;for(let d=0,k=this.W.length;d<k;++d){const w=this.W[d];this.W[b]=w;w.ga===a?w.l():++b}this.W.length=b}Fi(){let a=0;for(let b=0,d=this.Ma.length;b<d;++b){const k=this.Ma[b];this.Ma[a]=k;k.nb()?k.l():++a}this.Ma.length=a}*Za(a){if(a)for(const b of this.W)self.Ra.Mh(b.$,a)&&(yield b);else this.Ua&&!this.Ua.qa()&&(yield this.Ua)}async ed(a,b,d,k,w){for(const l of this.Ma)if(l.Zb()===b)return await U(l),l;if(w)return null;k&&(this.tf||this.Gg)&&
this.Fi();w="audio/webm; codecs=opus"===d&&!this.Ol;k&&w&&this.jl();a=!k||this.tf||w?new self.Gh(this,a,b,d,k,w):new self.Bh(this,a,b,d,k);this.Ma.push(a);await U(a);return a}async we(a,b,d,k,w){for(const l of this.W)if(l.Zb()===b&&(l.Wd()||w))return l.Pi(k),l;a=await this.ed(a,b,d,w);k="html5"===a.Re?new self.Ch(a.A,a,k):new self.Hh(a.A,a,k);this.W.push(k);return k}gj(a){let b=this.Ec.get(a);if(!b){let d=null;b={Df:0,promise:new Promise(k=>d=k),resolve:d};this.Ec.set(a,b)}b.Df++}$k(a){const b=this.Ec.get(a);
if(!b)throw Error("expected pending tag");b.Df--;0===b.Df&&(b.resolve(),this.Ec.delete(a))}qe(a){a||(a=this.Lg);return(a=this.Ec.get(a))?a.promise:Promise.resolve()}fd(){if(0<this.Ib.size)G(this);else for(const a of this.W)if(a.Sf()){G(this);break}}la(){for(var a of this.Ib)a.la();a=this.Zd();for(var b of this.W)b.la(a);b=this.W.filter(d=>d.Sf()).map(d=>d.Yb());A(this,"state",{tickCount:this.Og,audioInstances:b,analysers:[...this.Ib].map(d=>d.Uh())});0===b.length&&0===this.Ib.size&&this.yd&&(this.M.al(this.Zg),
this.yd=!1)}he(a,b,d){A(this,"trigger",{type:a,tag:b,aiid:d})}async Vk(a){const b=a.originalUrl,d=a.url,k=a.type,w=a.isMusic,l=a.tag,f=a.isLooping,n=a.vol,c=a.pos,e=a.panning;let p=a.off;0<p&&!a.trueClock&&(this.o.getOutputTimestamp?(a=this.o.getOutputTimestamp(),p=p-a.performanceTime/1E3+a.contextTime):p=p-performance.now()/1E3+this.o.currentTime);this.Lg=l;this.gj(l);try{this.Ua=await this.we(b,d,k,l,w),e?(this.Ua.ad(!0),this.Ua.Ni(e.x,e.y,e.angle,e.innerAngle,e.outerAngle,e.outerGain),e.hasOwnProperty("uid")&&
this.Ua.Qi(e.uid)):this.Ua.ad(!1),this.Ua.Play(f,n,c,p)}catch(v){console.error("[Construct 3] Audio: error starting playback: ",v);return}finally{this.$k(l)}G(this)}yl(a){a=a.tag;for(const b of this.Za(a))b.eb()}zl(){for(const a of this.W)a.eb()}rl(a){const b=a.tag;a=a.paused;for(const d of this.Za(b))a?d.bc():d.$c();this.fd()}wl(a){const b=a.tag;a=a.vol;for(const d of this.Za(b))d.cd(a)}async uj(a){const b=a.tag,d=a.vol,k=a.duration;a=a.stopOnEnd;await this.qe(b);for(const w of this.Za(b))w.Nh(d,
k,a);this.fd()}pl(a){this.mf=a.vol;for(const b of this.W)b.md()}ql(a){const b=a.tag;a=a.isMuted;for(const d of this.Za(b))d.$f(a)}tl(a){this.gb=a.isSilent;this.M.bd(this.gb);for(const b of this.W)b.ld()}ol(a){const b=a.tag;a=a.isLooping;for(const d of this.Za(b))d.ne(a)}async sl(a){const b=a.tag;a=a.rate;await this.qe(b);for(const d of this.Za(b))d.bg(a)}async cl(a){const b=a.tag;a=a.pos;await this.qe(b);for(const d of this.Za(b))d.le(a)}async Wk(a){const b=a.originalUrl,d=a.url,k=a.type;a=a.isMusic;
try{await this.we(b,d,k,"",a)}catch(w){console.error("[Construct 3] Audio: error preloading: ",w)}}async Cl(a){if(a=await this.ed("",a.url,a.type,a.isMusic,!0))a.l(),a=this.Ma.indexOf(a),-1!==a&&this.Ma.splice(a,1)}Dl(){for(const a of this.Ma)a.l();this.Ma.length=0}ul(a){a=a.isSuspended;!a&&this.o.resume&&this.o.resume();for(const b of this.W)b.oe(a);a&&this.o.suspend&&this.o.suspend()}Rk(a){this.Od=a.timeScale;this.Ze=a.gameTime;this.Og=a.tickCount;if(0!==this.zf)for(var b of this.W)b.Hb();(b=a.listenerPos)&&
this.o.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const k of this.W)k.Ta===a&&k.ag(d.x,d.y,d.angle)}}async eg(a){var b=a.type;const d=a.tag;var k=a.params;if("filter"===b)k=new self.vh(this,...k);else if("delay"===b)k=new self.th(this,...k);else if("convolution"===b){b=null;try{b=await this.ed(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(w){console.log("[Construct 3] Audio: error loading convolution: ",w);return}k=new self.sh(this,b.La,...k);k.gl(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)k=new self.wh(this,...k);else if("phaser"===b)k=new self.yh(this,...k);else if("gain"===b)k=new self.xh(this,...k);else if("tremolo"===b)k=new self.Ah(this,...k);else if("ringmod"===b)k=new self.zh(this,...k);else if("distortion"===b)k=new self.uh(this,...k);else if("compressor"===b)k=new self.rh(this,...k);else if("analyser"===b)k=new self.qh(this,...k);else throw Error("invalid effect type");this.lh(d,k);this.tg()}il(a){const b=a.index,d=a.param,k=a.value,w=a.ramp,
l=a.time;a=this.Na.get(a.tag);!a||0>b||b>=a.length||(a[b].Aa(d,k,w,l),this.tg())}Yk(a){a=a.tag.toLowerCase();const b=this.Na.get(a);if(b&&b.length){for(const d of b)d.l();this.Na.delete(a);this.ug(a)}}cj(a){this.Ib.add(a);this.fd()}Xk(a){this.Ib.delete(a)}tg(){this.ff||(this.ff=!0,Promise.resolve().then(()=>this.sj()))}sj(){const a={};for(const [b,d]of this.Na)a[b]=d.map(k=>k.Yb());A(this,"fxstate",{fxstate:a});this.ff=!1}async Ke(a){const b=a.saveLoadMode;if(3!==b)for(var d of this.W)d.nb()&&1===
b||(d.nb()||2!==b)&&d.eb();for(const k of this.Na.values())for(const w of k)w.l();this.Na.clear();this.Od=a.timeScale;this.Ze=a.gameTime;d=a.listenerPos;this.o.listener.setPosition(d[0],d[1],d[2]);this.gb=a.isSilent;this.M.bd(this.gb);this.mf=a.masterVolume;d=[];for(const k of Object.values(a.effects))d.push(Promise.all(k.map(w=>this.eg(w))));await Promise.all(d);await Promise.all(a.playing.map(k=>this.Hj(k,b)));this.fd()}async Hj(a,b){if(3!==b){var d=a.bufferOriginalUrl,k=a.bufferUrl,w=a.bufferType,
l=a.isMusic,f=a.tag,n=a.isLooping,c=a.volume,e=a.playbackTime;if(!l||1!==b)if(l||2!==b){b=null;try{b=await this.we(d,k,w,f,l)}catch(p){console.error("[Construct 3] Audio: error loading audio state: ",p);return}b.pi(a.pan);b.Play(n,c,e,0);a.isPlaying||b.bc();b.Ce(a)}}}hk(a,b){this.Ab&&this.Ab.disconnect();this.nf=b.toLowerCase();this.Ab=this.o.createMediaStreamSource(a);this.Ab.connect(this.Qf(this.nf))}Yj(){this.sd||(this.sd=this.o.createMediaStreamDestination(),this.td.connect(this.sd));return this.sd.stream}static Mh(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static bj(a){return a*h}static Kh(a){return Math.pow(10,a/20)}static Nf(a){return Math.max(Math.min(self.Ra.Kh(a),1),0)}static oi(a){return Math.log(a)/Math.log(10)*20}static ni(a){return self.Ra.oi(Math.max(Math.min(a,1),0))}static Ql(a,b){return 1-Math.exp(-b*a)}};self.wa.za(self.Ra)}"use strict";function U(h){h.Ed||(h.Ed=h.Be());return h.Ed}
self.Hf=class{constructor(h,a,b,d,k){this.A=h;this.Ll=a;this.Db=b;this.oa=d;this.Hl=k;this.Re="";this.Ed=null}l(){this.Ed=this.A=null}Be(){}va(){return this.A.va()}ae(){return this.Ll}Zb(){return this.Db}$d(){return this.oa}nb(){return this.Hl}Sa(){}};"use strict";
self.Bh=class extends self.Hf{constructor(h,a,b,d,k){super(h,a,b,d,k);this.Re="html5";this.ba=new Audio;this.ba.crossOrigin="anonymous";this.ba.autoplay=!1;this.ba.preload="auto";this.uc=this.vc=null;this.ba.addEventListener("canplaythrough",()=>!0);this.Cc=this.va().createGain();this.xc=null;this.ba.addEventListener("canplay",()=>{this.vc&&(this.vc(),this.uc=this.vc=null);!this.xc&&this.ba&&(this.xc=this.va().createMediaElementSource(this.ba),this.xc.connect(this.Cc))});this.onended=null;this.ba.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.ba.addEventListener("error",w=>{console.error(`[Construct 3] Audio '${this.Db}' error: `,w);this.uc&&(this.uc(w),this.uc=this.vc=null)})}l(){this.A.Xf(this);this.Cc.disconnect();this.Cc=null;this.xc.disconnect();this.xc=null;this.ba&&!this.ba.paused&&this.ba.pause();this.ba=this.onended=null;super.l()}Be(){return new Promise((h,a)=>{this.vc=h;this.uc=a;this.ba.src=this.Db})}ja(){return this.ba}Sa(){return this.ba.duration}};"use strict";
async function V(h){if(h.tb)return h.tb;var a=h.A.M;if("cordova"===a.T&&a.ki(h.Db)&&"file:"===location.protocol)h.tb=await a.Xd(h.Db);else{a=await fetch(h.Db);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);h.tb=await a.arrayBuffer()}}async function W(h){if(h.La)return h.La;h.La=await h.A.Lh(h.tb,h.Jl);h.tb=null}
self.Gh=class extends self.Hf{constructor(h,a,b,d,k,w){super(h,a,b,d,k);this.Re="webaudio";this.La=this.tb=null;this.Jl=!!w}l(){this.A.Xf(this);this.La=this.tb=null;super.l()}async Be(){try{await V(this),await W(this)}catch(h){console.error(`[Construct 3] Failed to load audio '${this.Db}': `,h)}}Sa(){return this.La?this.La.duration:0}};"use strict";
{let h=0;self.If=class{constructor(a,b,d){this.A=a;this.ga=b;this.$=d;this.nd=h++;this.ha=this.va().createGain();this.ha.connect(this.mb());this.N=null;this.qc=!1;this.Y=!0;this.sa=this.Xa=this.X=!1;this.Lc=1;this.Lb=!1;this.Fa=1;a=this.A.zf;this.gf=1===a&&!this.nb()||2===a;this.jc=this.Ta=-1;this.Yg=!1}l(){this.ga=this.A=null;this.N&&(this.N.disconnect(),this.N=null);this.ha.disconnect();this.ha=null}va(){return this.A.va()}mb(){return this.A.Qf(this.$)}Sc(){return this.A.Sc()}Rc(){return this.gf?
this.A.Ze:performance.now()/1E3}ae(){return this.ga.ae()}Zb(){return this.ga.Zb()}$d(){return this.ga.$d()}nb(){return this.ga.nb()}Pi(a){this.$=a}qa(){}Wd(){}IsPlaying(){return!this.Y&&!this.X&&!this.qa()}Sf(){return!this.Y&&!this.qa()}Eb(){}Sa(){return this.ga.Sa()}Play(){}eb(){}bc(){}$c(){}cd(a){this.Lc=a;this.ha.gain.cancelScheduledValues(0);this.jc=-1;this.ha.gain.value=this.be()}Nh(a,b,d){if(!this.Lb){a*=this.Sc();var k=this.ha.gain;k.cancelScheduledValues(0);var w=this.A.Zd();b=w+b;k.setValueAtTime(k.value,
w);k.linearRampToValueAtTime(a,b);this.Lc=a;this.jc=b;this.Yg=d}}md(){this.cd(this.Lc)}la(a){-1!==this.jc&&a>=this.jc&&(this.jc=-1,this.Yg&&this.eb(),this.A.he("fade-ended",this.$,this.nd))}be(){const a=this.Lc*this.Sc();return isFinite(a)?a:0}$f(a){a=!!a;this.Lb!==a&&(this.Lb=a,this.ld())}Xc(){return this.A.Xc()}ld(){}ne(){}bg(a){this.Fa!==a&&(this.Fa=a,this.Hb())}Hb(){}le(){}oe(){}ad(a){a=!!a;this.qc!==a&&((this.qc=a)?(this.N||(this.N=this.va().createPanner(),this.N.panningModel=this.A.Sg,this.N.distanceModel=
this.A.Eg,this.N.refDistance=this.A.Ug,this.N.maxDistance=this.A.Rg,this.N.rolloffFactor=this.A.Wg),this.ha.disconnect(),this.ha.connect(this.N),this.N.connect(this.mb())):(this.N.disconnect(),this.ha.disconnect(),this.ha.connect(this.mb())))}Ni(a,b,d,k,w,l){this.qc&&(this.ag(a,b,d),a=self.Ra.bj,this.N.coneInnerAngle=a(k),this.N.coneOuterAngle=a(w),this.N.coneOuterGain=l)}ag(a,b,d){this.qc&&(this.N.setPosition(a,b,0),this.N.setOrientation(Math.cos(d),Math.sin(d),0))}Qi(a){this.Ta=a}ce(){}Ei(a){const b=
this.N||this.ha;b.disconnect();b.connect(a)}Yb(){return{aiid:this.nd,tag:this.$,duration:this.Sa(),volume:this.Lc,isPlaying:this.IsPlaying(),playbackTime:this.Eb(),playbackRate:this.Fa,uid:this.Ta,bufferOriginalUrl:this.ae(),bufferUrl:"",bufferType:this.$d(),isMusic:this.nb(),isLooping:this.sa,isMuted:this.Lb,resumePosition:this.ce(),pan:this.bi()}}Ce(a){this.bg(a.playbackRate);this.$f(a.isMuted)}bi(){if(!this.N)return null;const a=this.N;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.Ta}}pi(a){a?(this.ad(!0),a=this.N,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.Ta=a.uid):this.ad(!1)}}}"use strict";
self.Ch=class extends self.If{constructor(h,a,b){super(h,a,b);this.ga.Cc.connect(this.ha);this.ga.onended=()=>this.Ge()}l(){this.eb();this.ga.Cc.disconnect();super.l()}ja(){return this.ga.ja()}Ge(){this.Y=!0;this.Ta=-1;this.A.he("ended",this.$,this.nd)}qa(){return this.ja().ended}Wd(){return this.Y?!0:this.qa()}Eb(h){let a=this.ja().currentTime;h&&(a*=this.Fa);this.sa||(a=Math.min(a,this.Sa()));return a}Play(h,a,b){const d=this.ja();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==h&&(d.loop=h);this.cd(a);
d.muted&&(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(k){console.warn(`[Construct 3] Exception seeking audio '${this.ga.Zb()}' to position '${b}': `,k)}this.A.ob(d);this.X=this.Y=!1;this.sa=h;this.Fa=1}eb(){const h=this.ja();h.paused||h.pause();this.A.Gb(h);this.Y=!0;this.X=!1;this.Ta=-1}bc(){if(!(this.X||this.Y||this.qa())){var h=this.ja();h.paused||h.pause();this.A.Gb(h);this.X=!0}}$c(){!this.X||this.Y||this.qa()||(this.A.ob(this.ja()),this.X=!1)}ld(){this.ja().muted=this.Lb||this.Xc()}ne(h){h=
!!h;this.sa!==h&&(this.sa=h,this.ja().loop=h)}Hb(){let h=this.Fa;this.gf&&(h*=this.A.Od);try{this.ja().playbackRate=h}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${h}':`,a)}}le(h){if(!this.Y&&!this.qa())try{this.ja().currentTime=h}catch(a){console.warn(`[Construct 3] Error seeking audio to '${h}': `,a)}}ce(){return this.Eb()}oe(h){h?this.IsPlaying()?(this.ja().pause(),this.Xa=!0):this.Xa=!1:this.Xa&&(this.A.ob(this.ja()),this.Xa=!1)}};"use strict";
function X(h){h.B&&h.B.disconnect();h.B=null;h.ec=null}
self.Hh=class extends self.If{constructor(h,a,b){super(h,a,b);this.B=null;this.Hd=d=>this.Ge(d);this.af=!0;this.ec=null;this.ia=this.Nd=0;this.pf=1}l(){this.eb();X(this);this.Hd=null;super.l()}Ge(h){this.X||this.Xa||h.target!==this.ec||(this.Y=this.af=!0,this.Ta=-1,X(this),this.A.he("ended",this.$,this.nd))}qa(){return!this.Y&&this.B&&this.B.loop||this.X?!1:this.af}Wd(){return!this.B||this.Y?!0:this.qa()}Eb(h){let a;a=this.X?this.ia:this.Rc()-this.Nd;h&&(a*=this.Fa);this.sa||(a=Math.min(a,this.Sa()));
return a}Play(h,a,b,d){this.pf=1;this.cd(a);X(this);this.B=this.va().createBufferSource();this.B.buffer=this.ga.La;this.B.connect(this.ha);this.ec=this.B;this.B.onended=this.Hd;this.B.loop=h;this.B.start(d,b);this.X=this.Y=this.af=!1;this.sa=h;this.Fa=1;this.Nd=this.Rc()-b}eb(){if(this.B)try{this.B.stop(0)}catch(h){}this.Y=!0;this.X=!1;this.Ta=-1}bc(){this.X||this.Y||this.qa()||(this.ia=this.Eb(!0),this.sa&&(this.ia%=this.Sa()),this.X=!0,this.B.stop(0))}$c(){!this.X||this.Y||this.qa()||(X(this),this.B=
this.va().createBufferSource(),this.B.buffer=this.ga.La,this.B.connect(this.ha),this.ec=this.B,this.B.onended=this.Hd,this.B.loop=this.sa,this.md(),this.Hb(),this.Nd=this.Rc()-this.ia/(this.Fa||.001),this.B.start(0,this.ia),this.X=!1)}be(){return super.be()*this.pf}ld(){this.pf=this.Lb||this.Xc()?0:1;this.md()}ne(h){h=!!h;this.sa!==h&&(this.sa=h,this.B&&(this.B.loop=h))}Hb(){let h=this.Fa;this.gf&&(h*=this.A.Od);this.B&&(this.B.playbackRate.value=h)}le(h){this.Y||this.qa()||(this.X?this.ia=h:(this.bc(),
this.ia=h,this.$c()))}ce(){return this.ia}oe(h){h?this.IsPlaying()?(this.Xa=!0,this.ia=this.Eb(!0),this.sa&&(this.ia%=this.Sa()),this.B.stop(0)):this.Xa=!1:this.Xa&&(X(this),this.B=this.va().createBufferSource(),this.B.buffer=this.ga.La,this.B.connect(this.ha),this.ec=this.B,this.B.onended=this.Hd,this.B.loop=this.sa,this.md(),this.Hb(),this.Nd=this.Rc()-this.ia/(this.Fa||.001),this.B.start(0,this.ia),this.Xa=!1)}Ce(h){super.Ce(h);this.ia=h.resumePosition}};"use strict";
{class h{constructor(a){this.A=a;this.o=a.va();this.nc=-1;this.oa=this.$="";this.s=null}l(){this.o=null}ll(a){this.nc=a}vl(a){this.$=a}G(){return this.o.createGain()}ka(){}pa(){}F(a,b,d,k){a.cancelScheduledValues(0);if(0===k)a.value=b;else{var w=this.o.currentTime;k+=w;switch(d){case 0:a.setValueAtTime(b,k);break;case 1:a.setValueAtTime(a.value,w);a.linearRampToValueAtTime(b,k);break;case 2:a.setValueAtTime(a.value,w),a.exponentialRampToValueAtTime(b,k)}}}Yb(){return{type:this.oa,tag:this.$,params:this.s}}}
self.vh=class extends h{constructor(a,b,d,k,w,l,f){super(a);this.oa="filter";this.s=[b,d,k,w,l,f];this.D=this.G();this.h=this.G();this.h.gain.value=f;this.g=this.G();this.g.gain.value=1-f;this.K=this.o.createBiquadFilter();this.K.type=b;this.K.frequency.value=d;this.K.detune.value=k;this.K.Q.value=w;this.K.gain.vlaue=l;this.D.connect(this.K);this.D.connect(this.g);this.K.connect(this.h)}l(){this.D.disconnect();this.K.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}Aa(a,b,d,k){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[5]=b;this.F(this.h.gain,b,d,k);this.F(this.g.gain,1-b,d,k);break;case 1:this.s[1]=b;this.F(this.K.frequency,b,d,k);break;case 2:this.s[2]=b;this.F(this.K.detune,b,d,k);break;case 3:this.s[3]=b;this.F(this.K.Q,b,d,k);break;case 4:this.s[4]=b,this.F(this.K.gain,b,d,k)}}};self.th=class extends h{constructor(a,b,d,k){super(a);this.oa="delay";this.s=[b,d,k];this.D=
this.G();this.h=this.G();this.h.gain.value=k;this.g=this.G();this.g.gain.value=1-k;this.wc=this.G();this.ra=this.o.createDelay(b);this.ra.delayTime.value=b;this.ic=this.G();this.ic.gain.value=d;this.D.connect(this.wc);this.D.connect(this.g);this.wc.connect(this.h);this.wc.connect(this.ra);this.ra.connect(this.ic);this.ic.connect(this.wc)}l(){this.D.disconnect();this.h.disconnect();this.g.disconnect();this.wc.disconnect();this.ra.disconnect();this.ic.disconnect();super.l()}pa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}Aa(a,b,d,k){const w=self.Ra.Nf;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[2]=b;this.F(this.h.gain,b,d,k);this.F(this.g.gain,1-b,d,k);break;case 4:this.s[1]=w(b);this.F(this.ic.gain,w(b),d,k);break;case 5:this.s[0]=b,this.F(this.ra.delayTime,b,d,k)}}};self.sh=class extends h{constructor(a,b,d,k){super(a);this.oa="convolution";this.s=[d,k];this.Ag=this.zg="";this.D=this.G();this.h=this.G();this.h.gain.value=k;this.g=
this.G();this.g.gain.value=1-k;this.hc=this.o.createConvolver();this.hc.normalize=d;this.hc.buffer=b;this.D.connect(this.hc);this.D.connect(this.g);this.hc.connect(this.h)}l(){this.D.disconnect();this.hc.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}Aa(a,b,d,k){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.s[1]=b,this.F(this.h.gain,b,d,k),this.F(this.g.gain,1-b,d,k)}}gl(a,
b){this.zg=a;this.Ag=b}Yb(){const a=super.Yb();a.bufferOriginalUrl=this.zg;a.bufferUrl="";a.bufferType=this.Ag;return a}};self.wh=class extends h{constructor(a,b,d,k,w,l){super(a);this.oa="flanger";this.s=[b,d,k,w,l];this.D=this.G();this.g=this.G();this.g.gain.value=1-l/2;this.h=this.G();this.h.gain.value=l/2;this.kc=this.G();this.kc.gain.value=w;this.ra=this.o.createDelay(b+d);this.ra.delayTime.value=b;this.I=this.o.createOscillator();this.I.frequency.value=k;this.Z=this.G();this.Z.gain.value=d;
this.D.connect(this.ra);this.D.connect(this.g);this.ra.connect(this.h);this.ra.connect(this.kc);this.kc.connect(this.ra);this.I.connect(this.Z);this.Z.connect(this.ra.delayTime);this.I.start(0)}l(){this.I.stop(0);this.D.disconnect();this.ra.disconnect();this.I.disconnect();this.Z.disconnect();this.g.disconnect();this.h.disconnect();this.kc.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}Aa(a,b,d,k){switch(a){case 0:b=Math.max(Math.min(b/
100,1),0);this.s[4]=b;this.F(this.h.gain,b/2,d,k);this.F(this.g.gain,1-b/2,d,k);break;case 6:this.s[1]=b/1E3;this.F(this.Z.gain,b/1E3,d,k);break;case 7:this.s[2]=b;this.F(this.I.frequency,b,d,k);break;case 8:this.s[3]=b/100,this.F(this.kc.gain,b/100,d,k)}}};self.yh=class extends h{constructor(a,b,d,k,w,l,f){super(a);this.oa="phaser";this.s=[b,d,k,w,l,f];this.D=this.G();this.g=this.G();this.g.gain.value=1-f/2;this.h=this.G();this.h.gain.value=f/2;this.K=this.o.createBiquadFilter();this.K.type="allpass";
this.K.frequency.value=b;this.K.detune.value=d;this.K.Q.value=k;this.I=this.o.createOscillator();this.I.frequency.value=l;this.Z=this.G();this.Z.gain.value=w;this.D.connect(this.K);this.D.connect(this.g);this.K.connect(this.h);this.I.connect(this.Z);this.Z.connect(this.K.frequency);this.I.start(0)}l(){this.I.stop(0);this.D.disconnect();this.K.disconnect();this.I.disconnect();this.Z.disconnect();this.g.disconnect();this.h.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();
this.g.connect(a)}ka(){return this.D}Aa(a,b,d,k){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[5]=b;this.F(this.h.gain,b/2,d,k);this.F(this.g.gain,1-b/2,d,k);break;case 1:this.s[0]=b;this.F(this.K.frequency,b,d,k);break;case 2:this.s[1]=b;this.F(this.K.detune,b,d,k);break;case 3:this.s[2]=b;this.F(this.K.Q,b,d,k);break;case 6:this.s[3]=b;this.F(this.Z.gain,b,d,k);break;case 7:this.s[4]=b,this.F(this.I.frequency,b,d,k)}}};self.xh=class extends h{constructor(a,b){super(a);this.oa="gain";this.s=
[b];this.v=this.G();this.v.gain.value=b}l(){this.v.disconnect();super.l()}pa(a){this.v.disconnect();this.v.connect(a)}ka(){return this.v}Aa(a,b,d,k){const w=self.Ra.Nf;switch(a){case 4:this.s[0]=w(b),this.F(this.v.gain,w(b),d,k)}}};self.Ah=class extends h{constructor(a,b,d){super(a);this.oa="tremolo";this.s=[b,d];this.v=this.G();this.v.gain.value=1-d/2;this.I=this.o.createOscillator();this.I.frequency.value=b;this.Z=this.G();this.Z.gain.value=d/2;this.I.connect(this.Z);this.Z.connect(this.v.gain);
this.I.start(0)}l(){this.I.stop(0);this.I.disconnect();this.Z.disconnect();this.v.disconnect();super.l()}pa(a){this.v.disconnect();this.v.connect(a)}ka(){return this.v}Aa(a,b,d,k){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[1]=b;this.F(this.v.gain.value,1-b/2,d,k);this.F(this.Z.gain.value,b/2,d,k);break;case 7:this.s[0]=b,this.F(this.I.frequency,b,d,k)}}};self.zh=class extends h{constructor(a,b,d){super(a);this.oa="ringmod";this.s=[b,d];this.D=this.G();this.h=this.G();this.h.gain.value=
d;this.g=this.G();this.g.gain.value=1-d;this.Ic=this.G();this.Ic.gain.value=0;this.I=this.o.createOscillator();this.I.frequency.value=b;this.I.connect(this.Ic.gain);this.I.start(0);this.D.connect(this.Ic);this.D.connect(this.g);this.Ic.connect(this.h)}l(){this.I.stop(0);this.I.disconnect();this.Ic.disconnect();this.D.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}Aa(a,b,d,k){switch(a){case 0:b=
Math.max(Math.min(b/100,1),0);this.s[1]=b;this.F(this.h.gain,b,d,k);this.F(this.g.gain,1-b,d,k);break;case 7:this.s[0]=b,this.F(this.I.frequency,b,d,k)}}};self.uh=class extends h{constructor(a,b,d,k,w,l){super(a);this.oa="distortion";this.s=[b,d,k,w,l];this.D=this.G();this.Jd=this.G();this.Id=this.G();this.hl(k,w);this.h=this.G();this.h.gain.value=l;this.g=this.G();this.g.gain.value=1-l;this.Sd=this.o.createWaveShaper();this.Ue=new Float32Array(65536);this.wj(b,d);this.Sd.curve=this.Ue;this.D.connect(this.Jd);
this.D.connect(this.g);this.Jd.connect(this.Sd);this.Sd.connect(this.Id);this.Id.connect(this.h)}l(){this.D.disconnect();this.Jd.disconnect();this.Sd.disconnect();this.Id.disconnect();this.h.disconnect();this.g.disconnect();super.l()}hl(a,b){.01>a&&(a=.01);this.Jd.gain.value=a;this.Id.gain.value=Math.pow(1/a,.6)*b}wj(a,b){for(let d=0;32768>d;++d){let k=d/32768;k=this.xl(k,a,b);this.Ue[32768+d]=k;this.Ue[32768-d-1]=-k}}xl(a,b,d){d=1.05*d*b-b;const k=0>a?-a:a;return(k<b?k:b+d*self.Ra.Ql(k-b,1/d))*(0>
a?-1:1)}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}Aa(a,b,d,k){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.s[4]=b,this.F(this.h.gain,b,d,k),this.F(this.g.gain,1-b,d,k)}}};self.rh=class extends h{constructor(a,b,d,k,w,l){super(a);this.oa="compressor";this.s=[b,d,k,w,l];this.v=this.o.createDynamicsCompressor();this.v.threshold.value=b;this.v.knee.value=d;this.v.ratio.value=k;this.v.attack.value=w;this.v.release.value=l}l(){this.v.disconnect();
super.l()}pa(a){this.v.disconnect();this.v.connect(a)}ka(){return this.v}Aa(){}};self.qh=class extends h{constructor(a,b,d){super(a);this.oa="analyser";this.s=[b,d];this.v=this.o.createAnalyser();this.v.fftSize=b;this.v.smoothingTimeConstant=d;this.Fg=new Float32Array(this.v.frequencyBinCount);this.Xg=new Uint8Array(b);this.Vg=this.Pb=0;this.A.cj(this)}l(){this.A.Xk(this);this.v.disconnect();super.l()}la(){this.v.getFloatFrequencyData(this.Fg);this.v.getByteTimeDomainData(this.Xg);const a=this.v.fftSize;
let b=this.Pb=0;for(var d=0;d<a;++d){let k=(this.Xg[d]-128)/128;0>k&&(k=-k);this.Pb<k&&(this.Pb=k);b+=k*k}d=self.Ra.ni;this.Pb=d(this.Pb);this.Vg=d(Math.sqrt(b/a))}pa(a){this.v.disconnect();this.v.connect(a)}ka(){return this.v}Aa(){}Uh(){return{tag:this.$,index:this.nc,peak:this.Pb,rms:this.Vg,binCount:this.v.frequencyBinCount,freqBins:this.Fg}}}}"use strict";self.wa.za(class extends self.ab{constructor(h){super(h,"mouse");E(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
function Y(h){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>A(h,"sw-message",a.data))}
function Z(h){h=h.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(h).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(h):screen.webkitLockOrientation?a=screen.webkitLockOrientation(h):screen.mozLockOrientation?a=screen.mozLockOrientation(h):screen.msLockOrientation&&(a=screen.msLockOrientation(h));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.wa.za(class extends self.ab{constructor(h){super(h,"browser");this.T="";F(this,[["get-initial-state",a=>this.Je(a)],["ready-for-sw-messages",()=>Y(this)],["alert",a=>this.Ee(a)],["close",()=>this.Fe()],["set-focus",a=>this.Ne(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Z(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var d=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a?window.open(b,"_blank"):this.bm||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,d=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,d))}],["request-fullscreen",
a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():
document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{A(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{A(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{A(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",
()=>{A(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;A(this,"backbutton")})}Je(h){this.T=h.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==
typeof window.is_scirra_arcade}}Ee(h){alert(h.message)}Fe(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}Ne(h){h=h.isFocus;if("nwjs"===this.T){const a="nwjs"===this.T?nw.Window.get():null;h?a.focus():a.blur()}else h?window.focus():window.blur()}});"use strict";
{const h=window.speechSynthesis||window.webkitSpeechSynthesis||window.mozSpeechSynthesis||window.msSpeechSynthesis,a=window.SpeechSynthesisUtterance||window.webkitSpeechSynthesisUtterance||window.mozSpeechSynthesisUtterance||window.msSpeechSynthesisUtterance;self.wa.za(class extends self.ab{constructor(b){super(b,"speech-synthesis");this.Af=[];E(this,"get-voices",()=>this.ak());E(this,"speak-text",d=>this.Pk(d));E(this,"stop-speaking",()=>this.Qk());E(this,"pause-speaking",()=>this.kk());E(this,"resume-speaking",
()=>this.vk())}ak(){h&&(this.Af=h.getVoices());return{isSupported:!!h,voices:this.Af.map(b=>({name:b.name,lang:b.lang,voiceURI:b.voiceURI}))}}Bj(b){for(const d of this.Af)if(d.voiceURI===b)return d;return null}Pk(b){const d=new a(b.text);b.lang&&(d.lang=b.lang);b.voiceURI&&(d.voice=this.Bj(b.voiceURI),d.voiceURI=b.voiceURI);d.volume=b.volume;d.rate=b.rate;d.pitch=b.pitch;d.onend=()=>A(this,"speech-ended");d.onerror=()=>A(this,"speech-error");h.speak(d)}Qk(){h.cancel()}kk(){h.pause()}vk(){h.resume()}})};